// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-11
//     Historique :
//         - 2026-09-11 : Création initiale pour J3-S3-T6 (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Xunit;
using AiDocGenerator.Analyzers;

namespace Tools.AiDocGenerator.Tests
{
    public class CSharpAnalyzerTests
    {
        [Fact]
        public async Task AnalyzeProjectAsync_ShouldExtractPublicProperties()
        {
            // Arrange
            using var workspace = new AdhocWorkspace();
            var projectId = ProjectId.CreateNewId();
            var versionStamp = VersionStamp.Create();
            var projectInfo = ProjectInfo.Create(projectId, versionStamp, "TestProject", "TestProject", LanguageNames.CSharp);
            var project = workspace.AddProject(projectInfo);

            var sourceText = SourceText.From(@"
namespace TestNamespace
{
    public class TestClass
    {
        /// <summary>
        /// Obtient ou définit le nom.
        /// </summary>
        public string Name { get; set; }

        public int Age { get; }
    }
}");
            var document = workspace.AddDocument(project.Id, "TestClass.cs", sourceText);
            var updatedProject = document.Project;

            // Act
            var result = await CSharpAnalyzer.AnalyzeProjectAsync(updatedProject, "");

            // Assert
            Assert.Contains("- `string Name { get; set; }` : Obtient ou définit le nom.", result);
            Assert.Contains("- `int Age { get; }`", result);
        }
    }
}