// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-25
//     Historique :
//         - 2026-09-25 : Création du test d'intégration E2E avec données réelles (J6-S2-T2 - Phase Rouge).
//         - 2026-09-25 : Correction de l'assertion sur le nombre d'expéditeurs dû au nettoyage des doublons (J6-S2-T2 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Infrastructure;
using Catamailer.Migrator.Mapping;
using Catamailer.Migrator.Orchestration;
using Catamailer.Migrator.Parsing;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Catamailer.Migrator.Tests.Orchestration
{
    public class MigrationOrchestratorE2ETests
    {
        private const string RealCsvData = @"# ---> Categorie : Administratif-Syndicats;;;;;;;;;;;;;;;;;;
SUJET; Administratif-Syndicats;CRT : Compte-rendu;;;;;;;;;;;;;;;;
EXPEDITEUR; Administratif-Syndicats; cgt.siege-sites.cnam@assurance-maladie.fr; cfe.cgc.electionsconseil2018.cnam@assurance-maladie.fr; cfe-cgc-siege-sites.cnam@assurance-maladie.fr; CFTC.cnam@assurance-maladie.fr; cftc.electionsconseil2018.cnam@assurance-maladie.fr; cfdt.cnam@assurance-maladie.fr; cfe-cgc.cnam@assurance-maladie.fr; fo.electionsconseil2018.cnam@assurance-maladie.fr; cgt.fo.cnam@assurance-maladie.fr; snfocos.cnam@assurance-maladie.fr; sud.cnam@assurance-maladie.fr; relations.sociales.cnam@assurance-maladie.fr; fo.cnam@assurance-maladie.fr; fo.electionsconseil2018.cnam@assurance-maladie.fr; gestion-greves.cnam@assurance-maladie.fr; cgt.cnam@assurance-maladie.fr;syndicat@snpdos-cfdt.fr
#DESTINATAIRE; Administratif-Syndicats;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;
# ---> Categorie : Carto;;;;;;;;;;;;;;;;;;
SUJET; Carto; [Cartographie Technique]; Flash info peuplement CartoSI;Référentiel de cartographie;;;;;;;;;;;;;;
EXPEDITEUR; Carto;damsi-da-cartographie.cnam@assurance-maladie.fr;;;;;;;;;;;;;;;;
DESTINATAIRE; Carto;damsi-da-cartographie.cnam@assurance-maladie.fr;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;
# ---> Categorie : CCOEN-Abonnements sportifs;;;;;;;;;;;;;;;;;;
#SUJET; CCOEN-Abonnements sportifs;;;;;;;;;;;;;;;;;
EXPEDITEUR; CCOEN-Abonnements sportifs; billetterie@hbcnantes.com;;;;;;;;;;;;;;;;
#DESTINATAIRE; CCOEN-Abonnements sportifs;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;
# ---> Categorie : CCOEN-Café L'Hermine Gourmande;;;;;;;;;;;;;;;;;;
SUJET; CCOEN-Café L'Hermine Gourmande; Commande de Café CCOEN;Hermine Gourmande;;;;;;;;;;;;;;;
#EXPEDITEUR; CCOEN-Café L'Hermine Gourmande;;;;;;;;;;;;;;;;;
#DESTINATAIRE; CCOEN-Café L'Hermine Gourmande;;;;;;;;;;;;;;;;;
# ---> Categorie : CCOEN-Trésoriers-Versement CSE;;;;;;;;;;;;;;;;;;
#SUJET; CCOEN-Trésoriers-Versement CSE;;;;;;;;;;;;;;;;;
EXPEDITEUR; CCOEN-Trésoriers-Versement CSE; CSE CNAM - Versement;;;;;;;;;;;;;;;;
#DESTINATAIRE; CCOEN-Trésoriers-Versement CSE;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;
# ---> Categorie : Comitologie-DAMSI-Staff Elargi;;;;;;;;;;;;;;;;;;
#SUJET; Comitologie-DAMSI-Staff Elargi;;;;;;;;;;;;;;;;;
#EXPEDITEUR; Comitologie-DAMSI-Staff Elargi;;;;;;;;;;;;;;;;;
DESTINATAIRE; Comitologie-DAMSI-Staff Elargi; damsi-staff-elargi.cnam@assurance-maladie.fr;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;";

        [Fact]
        public async Task MigrateAsync_WithRealCsvData_ShouldProduceCorrectDictionaryRules()
        {
            // Arrange
            var options = new DbContextOptionsBuilder<CatamailerDbContext>()
                .UseSqlite("DataSource=:memory:")
                .Options;

            using var context = new CatamailerDbContext(options);
            context.Database.OpenConnection();
            context.Database.EnsureCreated();

            // Injection des véritables implémentations de l'Étape 1
            var parser = new CsvParser();
            var mapper = new RuleMapper();
            var orchestrator = new MigrationOrchestrator(parser, mapper, context);

            var tempFilePath = Path.GetTempFileName();
            
            try
            {
                await File.WriteAllTextAsync(tempFilePath, RealCsvData);

                // Act
                await orchestrator.MigrateAsync(tempFilePath);

                // Assert
                var rules = context.DictionaryRules.Include(r => r.TargetCategory).ToList();

                // L'extrait contient 6 catégories distinctes (les lignes en commentaires sont ignorées)
                Assert.Equal(6, rules.Count);

                var adminSyndicats = rules.Single(r => r.TargetCategory.Name == "Administratif-Syndicats");
                Assert.Single(adminSyndicats.SubjectKeywords);
                Assert.Equal("CRT : Compte-rendu", adminSyndicats.SubjectKeywords[0]);
                
                // Le nombre attendu est 16 car "fo.electionsconseil2018.cnam@assurance-maladie.fr" est en doublon dans le CSV
                Assert.Equal(16, adminSyndicats.SenderKeywords.Count);
                Assert.Contains("syndicat@snpdos-cfdt.fr", adminSyndicats.SenderKeywords);
                Assert.Empty(adminSyndicats.RecipientKeywords);

                var carto = rules.Single(r => r.TargetCategory.Name == "Carto");
                Assert.Equal(3, carto.SubjectKeywords.Count);
                Assert.Contains("[Cartographie Technique]", carto.SubjectKeywords);
                Assert.Single(carto.SenderKeywords);
                Assert.Single(carto.RecipientKeywords);

                var hermine = rules.Single(r => r.TargetCategory.Name == "CCOEN-Café L'Hermine Gourmande");
                Assert.Equal(2, hermine.SubjectKeywords.Count);
                Assert.Contains("Hermine Gourmande", hermine.SubjectKeywords);
                Assert.Empty(hermine.SenderKeywords);

                var staff = rules.Single(r => r.TargetCategory.Name == "Comitologie-DAMSI-Staff Elargi");
                Assert.Empty(staff.SubjectKeywords);
                Assert.Empty(staff.SenderKeywords);
                Assert.Single(staff.RecipientKeywords);
                Assert.Equal("damsi-staff-elargi.cnam@assurance-maladie.fr", staff.RecipientKeywords[0]);
            }
            finally
            {
                if (File.Exists(tempFilePath))
                {
                    File.Delete(tempFilePath);
                }
            }
        }
    }
}