// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-25
//     Historique :
//         - 2026-09-25 : Création des tests d'intégration de l'orchestrateur (J6-S2-T1 - Phase Rouge).
//         - 2026-09-25 : Correction du bouchon FakeParser pour l'interface ICsvParser (J6-S2-T1 - Phase Rouge).
//         - 2026-09-25 : Ajustement du test avec un fichier temporaire réel et appel ParseLines (J6-S2-T1 - Phase Verte Correction).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;
using Catamailer.Infrastructure;
using Catamailer.Migrator.Mapping;
using Catamailer.Migrator.Orchestration;
using Catamailer.Migrator.Parsing;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Catamailer.Migrator.Tests.Orchestration
{
    public class MigrationOrchestratorTests
    {
        // Bouchon (Stub) simulant l'extraction de données depuis des lignes
        private class FakeParser : ICsvParser
        {
            public IEnumerable<CsvRuleRecord> ParseLines(IEnumerable<string> lines)
            {
                // Retourne un enregistrement fixe indépendamment du contenu du fichier temporaire
                return new List<CsvRuleRecord> 
                { 
                    new CsvRuleRecord("SUJET", "OrchestrationCategory", new[] { "MotCleTest" }) 
                };
            }
        }

        // Bouchon (Stub) simulant la traduction des enregistrements en règles
        private class FakeMapper : IRuleMapper
        {
            public IEnumerable<DictionaryRule> Map(IEnumerable<CsvRuleRecord> records)
            {
                var category = new CategoryNode("OrchestrationCategory");
                var rule = new DictionaryRule(category, subjectKeywords: new[] { "MotCleTest" });
                return new List<DictionaryRule> { rule };
            }
        }

        [Fact]
        public async Task MigrateAsync_ShouldParseMapAndSaveToDatabase()
        {
            // Arrange
            var options = new DbContextOptionsBuilder<CatamailerDbContext>()
                .UseSqlite("DataSource=:memory:")
                .Options;

            using var context = new CatamailerDbContext(options);
            context.Database.OpenConnection();
            context.Database.EnsureCreated();

            var parser = new FakeParser();
            var mapper = new FakeMapper();
            var orchestrator = new MigrationOrchestrator(parser, mapper, context);
            
            // Création d'un fichier temporaire réel pour passer la validation File.Exists
            var tempFilePath = Path.GetTempFileName();
            
            try
            {
                File.WriteAllText(tempFilePath, "dummy line");

                // Act
                await orchestrator.MigrateAsync(tempFilePath);

                // Assert
                var savedRules = context.DictionaryRules.Include(r => r.TargetCategory).ToList();
                
                Assert.Single(savedRules);
                var savedRule = savedRules.First();
                Assert.Equal("OrchestrationCategory", savedRule.TargetCategory.Name);
                Assert.Single(savedRule.SubjectKeywords);
                Assert.Equal("MotCleTest", savedRule.SubjectKeywords[0]);
            }
            finally
            {
                if (File.Exists(tempFilePath))
                {
                    File.Delete(tempFilePath);
                }
            }
        }
    }
}