// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-24
//     Historique :
//         - 2026-09-24 : Création initiale des tests du parseur CSV (J6-S1-T2 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Linq;
using Catamailer.Migrator.Parsing;
using Xunit;

namespace Catamailer.Migrator.Tests
{
    public class CsvParserTests
    {
        private readonly CsvParser _parser;

        public CsvParserTests()
        {
            _parser = new CsvParser();
        }

        [Fact]
        public void ParseLines_ShouldIgnoreCommentsAndEmptyLines()
        {
            // Arrange
            var lines = new[]
            {
                "# =========================================================================",
                "# Lignes commentées avec '#' = Lignes ou catégories vides/inactives",
                "",
                ";;;;;;;;;;;;;;;;;;",
                "SUJET; Administratif; Infos SG;;;;;;;;;;;;;;;;"
            };

            // Act
            var result = _parser.ParseLines(lines).ToList();

            // Assert
            Assert.Single(result);
            Assert.Equal("SUJET", result.First().Field);
        }

        [Fact]
        public void ParseLines_ShouldExtractFieldCategoryAndKeywords()
        {
            // Arrange
            var lines = new[]
            {
                "EXPEDITEUR; Administratif-La Suite Numérique; lasuite@beta.gouv.fr; docs@beta.gouv.fr;;;;"
            };

            // Act
            var result = _parser.ParseLines(lines).ToList();

            // Assert
            Assert.Single(result);
            var record = result.First();
            Assert.Equal("EXPEDITEUR", record.Field);
            Assert.Equal("Administratif-La Suite Numérique", record.CategoryName);
            Assert.Equal(2, record.Keywords.Count);
            Assert.Equal("lasuite@beta.gouv.fr", record.Keywords[0]);
            Assert.Equal("docs@beta.gouv.fr", record.Keywords[1]);
        }

        [Fact]
        public void ParseLines_ShouldTrimSpacesAndIgnoreEmptyKeywords()
        {
            // Arrange
            // Note: Espaces volontaires autour des champs et mots-clés vides intercalés
            var lines = new[]
            {
                " SUJET ;  Data & IA  ; IA & Data ; ; MotCle2 ; ; ; "
            };

            // Act
            var result = _parser.ParseLines(lines).ToList();

            // Assert
            Assert.Single(result);
            var record = result.First();
            Assert.Equal("SUJET", record.Field);
            Assert.Equal("Data & IA", record.CategoryName);
            Assert.Equal(2, record.Keywords.Count);
            Assert.Equal("IA & Data", record.Keywords[0]);
            Assert.Equal("MotCle2", record.Keywords[1]);
        }
        
        [Fact]
        public void ParseLines_ShouldIgnoreLinesWithLessThanTwoColumns()
        {
            // Arrange
            var lines = new[]
            {
                "SUJET_SEUL",
                "SUJET;" // Catégorie manquante
            };

            // Act
            var result = _parser.ParseLines(lines).ToList();

            // Assert
            Assert.Empty(result);
        }
    }
}