// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-25
//     Historique :
//         - 2026-09-25 : Création des tests de conteneur IoC (J6-S2-T3 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using Catamailer.Migrator;
using Catamailer.Migrator.Orchestration;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Catamailer.Migrator.Tests
{
    public class DependencyInjectionTests
    {
        [Fact]
        public void AddMigratorServices_ShouldRegisterAllRequiredDependencies()
        {
            // Arrange
            var services = new ServiceCollection();
            var dummyDbPath = "dummy.db";

            // Act
            services.AddMigratorServices(dummyDbPath);
            var provider = services.BuildServiceProvider();

            // Assert
            var orchestrator = provider.GetService<IMigrationOrchestrator>();
            
            // Si le DbContext, le CsvParser, le RuleMapper ou l'orchestrateur manquent,
            // GetService retournera null ou lèvera une exception selon la façon dont il est résolu.
            Assert.NotNull(orchestrator);
        }
    }
}