// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-24
//     Historique :
//         - 2026-09-24 : Création des tests unitaires du RuleMapper (J6-S1-T3 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Linq;
using Catamailer.Domain;
using Catamailer.Migrator.Mapping;
using Catamailer.Migrator.Parsing;
using Xunit;

namespace Catamailer.Migrator.Tests
{
    public class RuleMapperTests
    {
        private readonly RuleMapper _mapper;

        public RuleMapperTests()
        {
            _mapper = new RuleMapper();
        }

        [Fact]
        public void Map_ShouldGroupRecordsBySameCategory_IntoSingleDictionaryRule()
        {
            // Arrange
            var records = new List<CsvRuleRecord>
            {
                new CsvRuleRecord("SUJET", "Administratif", new[] { "Infos SG" }),
                new CsvRuleRecord("EXPEDITEUR", "Administratif", new[] { "admin@domaine.fr" })
            };

            // Act
            var result = _mapper.Map(records).ToList();

            // Assert
            Assert.Single(result);
            Assert.Equal("Administratif", result.First().TargetCategory.Name);
        }

        [Fact]
        public void Map_ShouldDispatchKeywordsToCorrectFields()
        {
            // Arrange
            var records = new List<CsvRuleRecord>
            {
                new CsvRuleRecord("SUJET", "Urba", new[] { "Architecture", "Design" }),
                new CsvRuleRecord("EXPEDITEUR", "Urba", new[] { "architecte@domaine.fr" }),
                new CsvRuleRecord("DESTINATAIRE", "Urba", new[] { "equipe-urba@domaine.fr", "boss@domaine.fr" })
            };

            // Act
            var result = _mapper.Map(records).ToList();

            // Assert
            Assert.Single(result);
            var rule = result.First();
            
            Assert.Equal(2, rule.SubjectKeywords.Count);
            Assert.Contains("Architecture", rule.SubjectKeywords);
            
            Assert.Single(rule.SenderKeywords);
            Assert.Contains("architecte@domaine.fr", rule.SenderKeywords);
            
            Assert.Equal(2, rule.RecipientKeywords.Count);
            Assert.Contains("boss@domaine.fr", rule.RecipientKeywords);
        }

        [Fact]
        public void Map_ShouldIgnoreRecordsWithUnknownFields()
        {
            // Arrange
            var records = new List<CsvRuleRecord>
            {
                new CsvRuleRecord("SUJET", "Valide", new[] { "Mot1" }),
                new CsvRuleRecord("CHAMP_INCONNU", "Valide", new[] { "IgnoreMoi" })
            };

            // Act
            var result = _mapper.Map(records).ToList();

            // Assert
            Assert.Single(result);
            var rule = result.First();
            Assert.Single(rule.SubjectKeywords);
            Assert.Empty(rule.SenderKeywords);
            Assert.Empty(rule.RecipientKeywords);
        }
    }
}