// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-24
//     Historique :
//         - 2026-09-24 : Création de l'interface IRuleMapper (J6-S1-T3 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using Catamailer.Domain;
using Catamailer.Migrator.Parsing;

namespace Catamailer.Migrator.Mapping
{
    /// <summary>
    /// Définit le contrat pour la transformation des enregistrements CSV bruts en règles de domaine (DictionaryRule).
    /// </summary>
    public interface IRuleMapper
    {
        /// <summary>
        /// Convertit et regroupe les enregistrements CSV en règles de dictionnaire.
        /// </summary>
        /// <param name="records">La liste des enregistrements issus du parsing CSV.</param>
        /// <returns>Une énumération de règles de dictionnaire consolidées par catégorie.</returns>
        IEnumerable<DictionaryRule> Map(IEnumerable<CsvRuleRecord> records);
    }
}