// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-24
//     Historique :
//         - 2026-09-24 : Création de la classe avec exception pour TDD (J6-S1-T3 - Phase Rouge).
//         - 2026-09-24 : Implémentation du regroupement et de la ventilation des champs (J6-S1-T3 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using Catamailer.Domain;
using Catamailer.Migrator.Parsing;

namespace Catamailer.Migrator.Mapping
{
    /// <summary>
    /// Implémentation du mappeur traduisant les enregistrements CSV en DictionaryRule.
    /// </summary>
    public class RuleMapper : IRuleMapper
    {
        /// <inheritdoc />
        public IEnumerable<DictionaryRule> Map(IEnumerable<CsvRuleRecord> records)
        {
            var dictionaryRules = new List<DictionaryRule>();

            // Regroupement des enregistrements par nom de catégorie
            var groupedRecords = records.GroupBy(r => r.CategoryName, StringComparer.OrdinalIgnoreCase);

            foreach (var group in groupedRecords)
            {
                var categoryName = group.Key;
                var categoryNode = new CategoryNode(categoryName); // Création à plat pour la migration

                var subjectKeywords = new List<string>();
                var senderKeywords = new List<string>();
                var recipientKeywords = new List<string>();

                foreach (var record in group)
                {
                    // Validation et ventilation par type de champ connu
                    if (string.Equals(record.Field, "SUJET", StringComparison.OrdinalIgnoreCase))
                    {
                        subjectKeywords.AddRange(record.Keywords);
                    }
                    else if (string.Equals(record.Field, "EXPEDITEUR", StringComparison.OrdinalIgnoreCase))
                    {
                        senderKeywords.AddRange(record.Keywords);
                    }
                    else if (string.Equals(record.Field, "DESTINATAIRE", StringComparison.OrdinalIgnoreCase))
                    {
                        recipientKeywords.AddRange(record.Keywords);
                    }
                    // Tout autre champ (ex: "#EXPEDITEUR" mal parsé ou champ inconnu) est ignoré
                }

                // On ne crée une règle que s'il y a au moins un mot-clé (pour éviter les règles vides)
                if (subjectKeywords.Any() || senderKeywords.Any() || recipientKeywords.Any())
                {
                    dictionaryRules.Add(new DictionaryRule(
                        categoryNode,
                        subjectKeywords.Distinct().ToList(), // Distinct pour éviter les doublons accidentels
                        senderKeywords.Distinct().ToList(),
                        recipientKeywords.Distinct().ToList()
                    ));
                }
            }

            return dictionaryRules;
        }
    }
}