#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale des modèles de synchronisation (J4-S1-T1).
//         - 2026-09-16 : Ajout de OptimizedColor (J4-S4-T2).
//         - 2026-09-17 : Ajout de IsImplicit pour un tracking formel des parents virtuels (J4-S4-T2).
//         - 2026-09-17 : Ajout de la méthode CreateSynchronized (J4-S4-T4 - Phase Verte).
//         - 2026-09-23 : Ajout de la méthode CreateDeletedInCatamailer (J4-S4-T6 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Catamailer.Domain.Sync
{
    /// <summary>
    /// Représente un écart détecté lors de la comparaison entre la Master Category List d'Outlook et la base Catamailer.
    /// </summary>
    public class CategoryDelta
    {
        public string CategoryName { get; }
        public string? OutlookColor { get; }
        public string? OptimizedColor { get; }
        public string? CatamailerColor { get; }
        public bool IsImplicit { get; }
        public DeltaStatus Status { get; }

        private CategoryDelta(string categoryName, string? outlookColor, string? catamailerColor, string? optimizedColor, bool isImplicit, DeltaStatus status)
        {
            CategoryName = categoryName;
            OutlookColor = outlookColor;
            CatamailerColor = catamailerColor;
            OptimizedColor = optimizedColor;
            IsImplicit = isImplicit;
            Status = status;
        }

        public static CategoryDelta CreateMissingInCatamailer(string categoryName, string? outlookColor, string? optimizedColor, bool isImplicit = false)
        {
            return new CategoryDelta(categoryName, outlookColor, null, optimizedColor, isImplicit, DeltaStatus.MissingInCatamailer);
        }

        public static CategoryDelta CreateMissingInOutlook(string categoryName, string? catamailerColor)
        {
            return new CategoryDelta(categoryName, null, catamailerColor, null, false, DeltaStatus.MissingInOutlook);
        }

        public static CategoryDelta CreateColorMismatch(string categoryName, string outlookColor, string catamailerColor)
        {
            return new CategoryDelta(categoryName, outlookColor, catamailerColor, null, false, DeltaStatus.ColorMismatch);
        }

        public static CategoryDelta CreateSynchronized(string categoryName, string color)
        {
            return new CategoryDelta(categoryName, color, color, null, false, DeltaStatus.Synchronized);
        }

        public static CategoryDelta CreateDeletedInCatamailer(string categoryName, string? outlookColor)
        {
            return new CategoryDelta(categoryName, outlookColor, null, null, false, DeltaStatus.DeletedInCatamailer);
        }
    }
}