#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale des modèles de synchronisation (J4-S1-T1 - Phase Verte/Orange).
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Catamailer.Domain.Sync
{
    /// <summary>
    /// Représente un écart détecté lors de la comparaison entre la Master Category List d'Outlook et la base Catamailer.
    /// </summary>
    public class CategoryDelta
    {
        /// <summary>
        /// Obtient le nom de la catégorie concernée par l'écart.
        /// </summary>
        public string CategoryName { get; }

        /// <summary>
        /// Obtient la couleur de la catégorie telle que définie dans Outlook (le cas échéant).
        /// </summary>
        public string? OutlookColor { get; }

        /// <summary>
        /// Obtient la couleur de la catégorie telle que définie dans Catamailer (le cas échéant).
        /// </summary>
        public string? CatamailerColor { get; }

        /// <summary>
        /// Obtient le type de conflit détecté.
        /// </summary>
        public DeltaStatus Status { get; }

        private CategoryDelta(string categoryName, string? outlookColor, string? catamailerColor, DeltaStatus status)
        {
            CategoryName = categoryName;
            OutlookColor = outlookColor;
            CatamailerColor = catamailerColor;
            Status = status;
        }

        /// <summary>
        /// Crée un delta signalant qu'une catégorie d'Outlook n'est pas connue dans Catamailer.
        /// </summary>
        /// <param name="categoryName">Le nom de la catégorie.</param>
        /// <param name="outlookColor">La couleur définie dans Outlook.</param>
        /// <returns>Une instance configurée de CategoryDelta.</returns>
        public static CategoryDelta CreateMissingInCatamailer(string categoryName, string? outlookColor)
        {
            return new CategoryDelta(categoryName, outlookColor, null, DeltaStatus.MissingInCatamailer);
        }

        /// <summary>
        /// Crée un delta signalant qu'une catégorie de Catamailer n'existe pas dans Outlook.
        /// </summary>
        /// <param name="categoryName">Le nom de la catégorie.</param>
        /// <param name="catamailerColor">La couleur définie dans Catamailer.</param>
        /// <returns>Une instance configurée de CategoryDelta.</returns>
        public static CategoryDelta CreateMissingInOutlook(string categoryName, string? catamailerColor)
        {
            return new CategoryDelta(categoryName, null, catamailerColor, DeltaStatus.MissingInOutlook);
        }

        /// <summary>
        /// Crée un delta signalant une différence de couleur pour une même catégorie.
        /// </summary>
        /// <param name="categoryName">Le nom de la catégorie.</param>
        /// <param name="outlookColor">La couleur définie dans Outlook.</param>
        /// <param name="catamailerColor">La couleur définie dans Catamailer.</param>
        /// <returns>Une instance configurée de CategoryDelta.</returns>
        public static CategoryDelta CreateColorMismatch(string categoryName, string outlookColor, string catamailerColor)
        {
            return new CategoryDelta(categoryName, outlookColor, catamailerColor, DeltaStatus.ColorMismatch);
        }
    }
}