// ------------------------------------------------------------------------------
// <auto-generated>
//     Catamailer - Clean Architecture
//     Création : 2026-09-15
//     Description : Énumération des types de conflits lors de la synchronisation
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Catamailer.Domain.Sync
{
    /// <summary>
    /// Définit les différents états possibles d'un écart de synchronisation entre Outlook et Catamailer.
    /// </summary>
    public enum DeltaStatus
    {
        /// <summary>
        /// La catégorie existe dans Outlook mais est absente de la base Catamailer.
        /// </summary>
        MissingInCatamailer,

        /// <summary>
        /// La catégorie existe dans la base Catamailer mais est absente d'Outlook.
        /// </summary>
        MissingInOutlook,

        /// <summary>
        /// La catégorie existe des deux côtés mais possède des couleurs différentes.
        /// </summary>
        ColorMismatch
    }
}