#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-17
//     Historique :
//         - 2026-09-17 : Création de l'énumération pour la résolution des conflits (J4-S4-T4 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Catamailer.Domain.Sync
{
    /// <summary>
    /// Définit la direction de résolution pour un écart de synchronisation (notamment les couleurs).
    /// </summary>
    public enum SyncResolutionDirection
    {
        OutlookToCatamailer,
        CatamailerToOutlook
    }
}