// ------------------------------------------------------------------------------
// <auto-generated>
//     Catamailer - Clean Architecture
//     Création : 2026-09-15
//     Description : Résultat global d'une analyse de synchronisation
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Catamailer.Domain.Sync
{
    /// <summary>
    /// Représente le résultat global de la comparaison des référentiels de catégories.
    /// </summary>
    public class SyncResult
    {
        private readonly List<CategoryDelta> _deltas = new List<CategoryDelta>();

        /// <summary>
        /// Obtient la liste en lecture seule de tous les écarts détectés.
        /// </summary>
        public IReadOnlyList<CategoryDelta> Deltas => _deltas.AsReadOnly();

        /// <summary>
        /// Indique si au moins un écart a été détecté lors de la synchronisation.
        /// </summary>
        public bool HasConflicts => _deltas.Count > 0;

        /// <summary>
        /// Ajoute un nouvel écart au résultat de la synchronisation.
        /// </summary>
        /// <param name="delta">L'écart détecté.</param>
        public void AddDelta(CategoryDelta delta)
        {
            _deltas.Add(delta);
        }

        /// <summary>
        /// Récupère la liste des catégories présentes dans Outlook mais absentes de Catamailer.
        /// </summary>
        public IEnumerable<CategoryDelta> GetMissingInCatamailer()
        {
            return _deltas.Where(d => d.Status == DeltaStatus.MissingInCatamailer);
        }

        /// <summary>
        /// Récupère la liste des catégories présentes dans Catamailer mais absentes d'Outlook.
        /// </summary>
        public IEnumerable<CategoryDelta> GetMissingInOutlook()
        {
            return _deltas.Where(d => d.Status == DeltaStatus.MissingInOutlook);
        }

        /// <summary>
        /// Récupère la liste des catégories présentant un conflit de couleur.
        /// </summary>
        public IEnumerable<CategoryDelta> GetColorConflicts()
        {
            return _deltas.Where(d => d.Status == DeltaStatus.ColorMismatch);
        }
    }
}