#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Catamailer - Clean Architecture
//     Création : 2026-09-15
//     Description : Tests unitaires validant la modélisation des entités de synchronisation
//     Historique :
//         - 2026-09-16 : Mise à jour de la signature CreateMissingInCatamailer avec optimizedColor (J4-S4-T2).
//         - 2026-09-17 : Ajout de la propriété IsImplicit pour tracker formellement les parents virtuels (J4-S4-T2).
//         - 2026-09-17 : Ajout des tests pour le statut Synchronized (J4-S4-T4 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Linq;
using Catamailer.Domain.Sync;
using Xunit;

namespace Catamailer.Domain.Tests
{
    public class SyncModelsTests
    {
        [Fact]
        public void CategoryDelta_CreateMissingInCatamailer_ShouldSetProperties()
        {
            // Arrange
            string categoryName = "NewFromOutlook";
            string outlookColor = "#FFFFFF";
            string optimizedColor = "#CCCCCC";

            // Act
            var delta = CategoryDelta.CreateMissingInCatamailer(categoryName, outlookColor, optimizedColor, isImplicit: true);

            // Assert
            Assert.Equal(categoryName, delta.CategoryName);
            Assert.Equal(outlookColor, delta.OutlookColor);
            Assert.Equal(optimizedColor, delta.OptimizedColor);
            Assert.Null(delta.CatamailerColor);
            Assert.True(delta.IsImplicit);
            Assert.Equal(DeltaStatus.MissingInCatamailer, delta.Status);
        }

        [Fact]
        public void CategoryDelta_CreateMissingInOutlook_ShouldSetProperties()
        {
            // Arrange
            string categoryName = "OrphanInCatamailer";
            string catamailerColor = "#000000";

            // Act
            var delta = CategoryDelta.CreateMissingInOutlook(categoryName, catamailerColor);

            // Assert
            Assert.Equal(categoryName, delta.CategoryName);
            Assert.Equal(catamailerColor, delta.CatamailerColor);
            Assert.Null(delta.OutlookColor);
            Assert.False(delta.IsImplicit);
            Assert.Equal(DeltaStatus.MissingInOutlook, delta.Status);
        }

        [Fact]
        public void CategoryDelta_CreateColorMismatch_ShouldSetBothColors()
        {
            // Arrange
            string categoryName = "ConflictCat";
            string outlookColor = "#000000";
            string catamailerColor = "#FFFFFF";

            // Act
            var delta = CategoryDelta.CreateColorMismatch(categoryName, outlookColor, catamailerColor);

            // Assert
            Assert.Equal(categoryName, delta.CategoryName);
            Assert.Equal(outlookColor, delta.OutlookColor);
            Assert.Equal(catamailerColor, delta.CatamailerColor);
            Assert.False(delta.IsImplicit);
            Assert.Equal(DeltaStatus.ColorMismatch, delta.Status);
        }

        [Fact]
        public void CategoryDelta_CreateSynchronized_ShouldSetProperties()
        {
            // Arrange
            string categoryName = "InSyncCat";
            string color = "#123456";

            // Act
            var delta = CategoryDelta.CreateSynchronized(categoryName, color);

            // Assert
            Assert.Equal(categoryName, delta.CategoryName);
            Assert.Equal(color, delta.OutlookColor);
            Assert.Equal(color, delta.CatamailerColor);
            Assert.False(delta.IsImplicit);
            Assert.Equal(DeltaStatus.Synchronized, delta.Status);
        }

        [Fact]
        public void SyncResult_GetSynchronized_ShouldReturnOnlySynchronizedDeltas()
        {
            // Arrange
            var syncResult = new SyncResult();
            syncResult.AddDelta(CategoryDelta.CreateMissingInCatamailer("Cat1", null, null, false));
            syncResult.AddDelta(CategoryDelta.CreateSynchronized("Cat2", "#000000"));

            // Act
            var synchronized = syncResult.GetSynchronized().ToList();

            // Assert
            Assert.Single(synchronized);
            Assert.Equal("Cat2", synchronized[0].CategoryName);
        }

        [Fact]
        public void SyncResult_AddDelta_ShouldUpdateConflictsAndLists()
        {
            // Arrange
            var syncResult = new SyncResult();
            var delta1 = CategoryDelta.CreateMissingInCatamailer("Cat1", null, null, false);
            var delta2 = CategoryDelta.CreateColorMismatch("Cat2", "#000000", "#FFFFFF");

            // Act
            syncResult.AddDelta(delta1);
            syncResult.AddDelta(delta2);

            // Assert
            Assert.True(syncResult.HasConflicts);
            Assert.Equal(2, syncResult.Deltas.Count);
            
            var missingInCatamailer = syncResult.GetMissingInCatamailer().ToList();
            Assert.Single(missingInCatamailer);
            Assert.Equal("Cat1", missingInCatamailer[0].CategoryName);

            var colorConflicts = syncResult.GetColorConflicts().ToList();
            Assert.Single(colorConflicts);
            Assert.Equal("Cat2", colorConflicts[0].CategoryName);
        }
    }
}