// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-07 : Implémentation EF Core (Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;
using Catamailer.Domain;
using Microsoft.EntityFrameworkCore;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Implémentation EF Core pour le dépôt des paramètres d'application.
    /// </summary>
    public class AppSettingsRepository : IAppSettingsRepository
    {
        private readonly CatamailerDbContext _context;

        public AppSettingsRepository(CatamailerDbContext context)
        {
            _context = context;
        }

        public async Task<string?> GetSettingAsync(string key)
        {
            var setting = await _context.AppSettings.FirstOrDefaultAsync(s => s.Key == key);
            return setting?.Value;
        }

        public async Task SetSettingAsync(string key, string value)
        {
            var setting = await _context.AppSettings.FirstOrDefaultAsync(s => s.Key == key);
            
            if (setting == null)
            {
                setting = new AppSetting { Key = key, Value = value };
                await _context.AppSettings.AddAsync(setting);
            }
            else
            {
                setting.Value = value;
                _context.AppSettings.Update(setting);
            }

            await _context.SaveChangesAsync();
        }
    }
}