// ------------------------------------------------------------------------------
// <auto-generated>
//     Historique :
//     2026-09-07 : Création de l'implémentation CategoryRepository (J1-S1-T3).
//     2026-09-08 : Implémentation de GetAllAsync (J3-S2-T1).
//     2026-09-08 : Ajout du chargement explicite (Include) du Parent dans GetAllAsync (J3-S2-T1).
//     2026-09-17 : Implémentation de UpdateAsync (J4-S4-T4).
//     2026-09-17 : Ajout de SaveChangesAsync dans AddAsync et UpdateAsync pour garantir la persistance (J4-S4-T4 - Bugfix).
//     2026-09-23 : Ajout des bouchons pour AddRangeAsync et UpdateRangeAsync (J4-S4-T7 - Phase Rouge).
//     2026-09-23 : Implémentation de AddRangeAsync et UpdateRangeAsync pour les performances (J4-S4-T7 - Phase Verte).
//     2026-09-23 : Mise à jour de GetAllAsync avec le filtre QueryFilter (includeDeleted) (J4-S4-T6 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;
using Microsoft.EntityFrameworkCore;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Implémentation SQLite du dépôt pour les catégories utilisant Entity Framework Core.
    /// </summary>
    public class CategoryRepository : ICategoryRepository
    {
        private readonly CatamailerDbContext _context;

        /// <summary>
        /// Initialise une nouvelle instance de la classe <see cref="CategoryRepository"/>.
        /// </summary>
        /// <param name="context">Le contexte de base de données EF Core.</param>
        public CategoryRepository(CatamailerDbContext context)
        {
            _context = context;
        }

        /// <inheritdoc />
        public async Task AddAsync(CategoryNode category)
        {
            await _context.Categories.AddAsync(category);
            await _context.SaveChangesAsync();
        }

        /// <inheritdoc />
        public async Task AddRangeAsync(IEnumerable<CategoryNode> categories)
        {
            await _context.Categories.AddRangeAsync(categories);
            await _context.SaveChangesAsync();
        }

        /// <inheritdoc />
        public async Task UpdateAsync(CategoryNode category)
        {
            _context.Categories.Update(category);
            await _context.SaveChangesAsync();
        }

        /// <inheritdoc />
        public async Task UpdateRangeAsync(IEnumerable<CategoryNode> categories)
        {
            _context.Categories.UpdateRange(categories);
            await _context.SaveChangesAsync();
        }

        /// <inheritdoc />
        public async Task<CategoryNode?> GetByNameAsync(string name)
        {
            return await _context.Categories
                .IgnoreQueryFilters() // On veut pouvoir retrouver un élément supprimé par nom
                .FirstOrDefaultAsync(c => c.Name == name);
        }

        /// <inheritdoc />
        public async Task<IEnumerable<CategoryNode>> GetAllAsync(bool includeDeleted = false)
        {
            var query = _context.Categories.Include(c => c.Parent).AsQueryable();

            // Note: EF Core applique souvent un filtre global sur IsDeleted. 
            // Si includeDeleted est vrai, on force l'annulation du filtre global s'il existe.
            if (includeDeleted)
            {
                query = query.IgnoreQueryFilters();
            }
            else
            {
                // Par sécurité (au cas où on n'a pas configuré le filtre global), on filtre manuellement
                query = query.Where(c => !c.IsDeleted);
            }

            return await query.ToListAsync();
        }
    }
}