// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-07 : Implémentation EF Core (Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;
using Catamailer.Domain;
using Microsoft.EntityFrameworkCore;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Implémentation EF Core pour le dépôt des états systèmes.
    /// </summary>
    public class HistoryStateRepository : IHistoryStateRepository
    {
        private readonly CatamailerDbContext _context;

        public HistoryStateRepository(CatamailerDbContext context)
        {
            _context = context;
        }

        public async Task<string?> GetStateAsync(string key)
        {
            var state = await _context.SystemStates.FirstOrDefaultAsync(s => s.Key == key);
            return state?.Value;
        }

        public async Task SetStateAsync(string key, string value)
        {
            var state = await _context.SystemStates.FirstOrDefaultAsync(s => s.Key == key);
            
            if (state == null)
            {
                state = new SystemState { Key = key, Value = value };
                await _context.SystemStates.AddAsync(state);
            }
            else
            {
                state.Value = value;
                _context.SystemStates.Update(state);
            }

            await _context.SaveChangesAsync();
        }
    }
}