// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using Catamailer.Domain;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Interface d'abstraction pour l'application COM Outlook, facilitant les tests unitaires.
    /// </summary>
    public interface IOutlookApplicationWrapper
    {
        /// <summary>
        /// Événement déclenché nativement par Outlook via NewMailEx.
        /// </summary>
        event Action<string> OnNewMailEx;

        /// <summary>
        /// Récupère les métadonnées d'un e-mail à partir de son EntryID.
        /// </summary>
        /// <param name="entryId">L'identifiant unique de l'e-mail.</param>
        /// <returns>Les métadonnées agnostiques de l'e-mail.</returns>
        MailMetadata GetMailMetadata(string entryId);
    }
}