// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-07 : Ajout de GetSelectedEntryId pour J2-S1-T2 (Phase Rouge).
//         - 2026-09-07 : Ajout des méthodes CRUD pour les catégories J2-S1-T3 (Phase Rouge).
//         - 2026-09-07 : Ajout de ReplaceCategoryOnAllItems pour J2-S1-T4 (Phase Rouge).
//         - 2026-09-07 : Ajout de GetNextUnprocessedMailEntryIds pour J2-S2-T3 (Phase Rouge).
//         - 2026-09-15 : Ajout de GetMasterCategories pour J4-S3-T1 (Phase Rouge).
//         - 2026-09-17 : Ajout de RenameCategory pour J4-S4-T3 (Phase Verte).
//         - 2026-09-23 : Ajout de IDisposable pour libération explicite COM (J4-S4-T7 - Phase Orange).
//         - 2026-09-23 : Ajout des signatures pour les actions physiques (J5-S2-T1 - Phase Rouge).
//         - 2026-09-24 : Ajout de la lecture de l'arborescence des dossiers (J5-S2-T2 - Phase Rouge).
//         - 2026-09-24 : Implémentation de IExternalResourceProvider (J6-S1-T1 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using Catamailer.Domain;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Interface d'abstraction pour l'application COM Outlook, facilitant les tests unitaires.
    /// </summary>
    public interface IOutlookApplicationWrapper : IDisposable, IExternalResourceProvider
    {
        /// <summary>
        /// Événement déclenché nativement par Outlook via NewMailEx.
        /// </summary>
        event Action<string>? OnNewMailEx;

        /// <summary>
        /// Récupère les métadonnées d'un e-mail à partir de son EntryID.
        /// </summary>
        MailMetadata GetMailMetadata(string entryId);

        /// <summary>
        /// Récupère l'EntryID de l'élément actuellement sélectionné dans l'explorateur actif.
        /// </summary>
        string? GetSelectedEntryId();

        /// <summary>
        /// Lit l'intégralité de la Master Category List d'Outlook.
        /// </summary>
        IEnumerable<(string Name, string? ColorCode)> GetMasterCategories();

        /// <summary>
        /// Vérifie si une catégorie existe dans la Master Category List.
        /// </summary>
        bool CategoryExists(string name);

        /// <summary>
        /// Ajoute une catégorie à la Master Category List.
        /// </summary>
        void AddCategory(string name, string colorCode);

        /// <summary>
        /// Met à jour la couleur d'une catégorie existante.
        /// </summary>
        void UpdateCategory(string name, string newColorCode);
        
        /// <summary>
        /// Renomme une catégorie existante dans la Master Category List.
        /// </summary>
        void RenameCategory(string oldName, string newName);

        /// <summary>
        /// Supprime une catégorie de la Master Category List.
        /// </summary>
        void RemoveCategory(string name);

        /// <summary>
        /// Remplace une catégorie par une autre sur l'ensemble des éléments de la messagerie en utilisant une recherche avancée (DASL).
        /// </summary>
        void ReplaceCategoryOnAllItems(string oldCategoryName, string newCategoryName);

        /// <summary>
        /// Récupère un lot d'EntryIDs d'e-mails à traiter dans l'historique à partir du dernier EntryID connu.
        /// </summary>
        IEnumerable<string> GetNextUnprocessedMailEntryIds(string? lastEntryId, int maxItems);

        // ====================================================================================
        // LECTURE DE L'ENVIRONNEMENT ET ARBORESCENCE (J5-S2-T2 / J6-S1-T1)
        // ====================================================================================

        /// <summary>
        /// Récupère l'arborescence complète des chemins de dossiers disponibles sous la Boîte de réception.
        /// </summary>
        IEnumerable<string> GetAvailableFolderPaths();

        /// <summary>
        /// Récupère la liste des signatures configurées sur le poste (lecture fichiers .htm).
        /// </summary>
        IEnumerable<string> GetAvailableSignatures();

        // ====================================================================================
        // ACTIONS PHYSIQUES D'EXÉCUTION (J5-S2-T1)
        // ====================================================================================

        /// <summary>
        /// Déplace l'e-mail vers le dossier spécifié.
        /// </summary>
        void MoveToFolder(string entryId, string folderPath);

        /// <summary>
        /// Marque l'e-mail comme lu.
        /// </summary>
        void MarkAsRead(string entryId);

        /// <summary>
        /// Assure le suivi de l'e-mail (Drapeau classique).
        /// </summary>
        void FlagForFollowUp(string entryId);

        /// <summary>
        /// Transfère l'e-mail aux destinataires spécifiés.
        /// </summary>
        void Forward(string entryId, string recipients);

        /// <summary>
        /// Définit le niveau d'importance de l'e-mail.
        /// </summary>
        void SetImportance(string entryId, string importanceLevel);

        /// <summary>
        /// Ajoute un rappel à l'e-mail pour une date et heure spécifiques.
        /// </summary>
        void AddReminder(string entryId, DateTime reminderTime);

        /// <summary>
        /// Assure un suivi pour aujourd'hui (Drapeau de tâche Outlook).
        /// </summary>
        void FlagToday(string entryId);

        /// <summary>
        /// Insère une signature HTML spécifique.
        /// </summary>
        void InsertHtmlSignature(string entryId, string signatureName);
    }
}