// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-07 : Implémentation des opérations CRUD avec le wrapper (Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using Catamailer.Domain;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Implémentation du fournisseur de gestion des catégories via l'Interop COM Outlook.
    /// </summary>
    public class OutlookCategoryManagerProvider : ICategoryManagerProvider
    {
        private readonly IOutlookApplicationWrapper _outlookWrapper;

        /// <summary>
        /// Initialise une nouvelle instance de OutlookCategoryManagerProvider.
        /// </summary>
        /// <param name="outlookWrapper">L'abstraction de l'application Outlook.</param>
        public OutlookCategoryManagerProvider(IOutlookApplicationWrapper outlookWrapper)
        {
            _outlookWrapper = outlookWrapper;
        }

        public void AddCategory(string name, string colorCode)
        {
            if (!_outlookWrapper.CategoryExists(name))
            {
                _outlookWrapper.AddCategory(name, colorCode);
            }
        }

        public void UpdateCategoryColor(string name, string newColorCode)
        {
            if (_outlookWrapper.CategoryExists(name))
            {
                _outlookWrapper.UpdateCategory(name, newColorCode);
            }
        }

        public void RemoveCategory(string name)
        {
            if (_outlookWrapper.CategoryExists(name))
            {
                _outlookWrapper.RemoveCategory(name);
            }
        }
    }
}