// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-07 : Implémentation de la mise à jour en masse (Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using Catamailer.Domain;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Implémentation du fournisseur de mise à jour en masse via l'Interop COM Outlook.
    /// </summary>
    public class OutlookMassUpdateProvider : IMassUpdateProvider
    {
        private readonly IOutlookApplicationWrapper _outlookWrapper;

        /// <summary>
        /// Initialise une nouvelle instance de OutlookMassUpdateProvider.
        /// </summary>
        /// <param name="outlookWrapper">L'abstraction de l'application Outlook.</param>
        public OutlookMassUpdateProvider(IOutlookApplicationWrapper outlookWrapper)
        {
            _outlookWrapper = outlookWrapper;
        }

        public void UpdateCategoryNameOnItems(string oldCategoryName, string newCategoryName)
        {
            _outlookWrapper.ReplaceCategoryOnAllItems(oldCategoryName, newCategoryName);
        }
    }
}