// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-07 : Ajout du contexte nullable explicite (Correction CS8669).
//         - 2026-09-07 : Implémentation de l'écoute COM (Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using Catamailer.Domain;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Implémentation du fournisseur de messagerie basée sur l'Interop COM Outlook.
    /// </summary>
    public class OutlookMailProvider : IMailProvider
    {
        private readonly IOutlookApplicationWrapper _outlookWrapper;

        public event EventHandler<MailMetadata>? NewMailReceived;

        /// <summary>
        /// Initialise une nouvelle instance de OutlookMailProvider.
        /// </summary>
        /// <param name="outlookWrapper">L'abstraction de l'application Outlook.</param>
        public OutlookMailProvider(IOutlookApplicationWrapper outlookWrapper)
        {
            _outlookWrapper = outlookWrapper;
        }

        public void StartListening()
        {
            _outlookWrapper.OnNewMailEx += OutlookWrapper_OnNewMailEx;
        }

        public void StopListening()
        {
            _outlookWrapper.OnNewMailEx -= OutlookWrapper_OnNewMailEx;
        }

        private void OutlookWrapper_OnNewMailEx(string entryId)
        {
            var metadata = _outlookWrapper.GetMailMetadata(entryId);
            NewMailReceived?.Invoke(this, metadata);
        }
    }
}