#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-07 : Implémentation des opérations CRUD avec le wrapper (Phase Verte).
//         - 2026-09-15 : Implémentation de GetAllCategories avec NotImplementedException (J4-S1-T2).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Catamailer.Domain;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Implémentation du fournisseur de gestion des catégories via l'Interop COM Outlook.
    /// </summary>
    public class OutlookCategoryManagerProvider : ICategoryManagerProvider
    {
        private readonly IOutlookApplicationWrapper _outlookWrapper;

        /// <summary>
        /// Initialise une nouvelle instance de OutlookCategoryManagerProvider.
        /// </summary>
        /// <param name="outlookWrapper">L'abstraction de l'application Outlook.</param>
        public OutlookCategoryManagerProvider(IOutlookApplicationWrapper outlookWrapper)
        {
            _outlookWrapper = outlookWrapper;
        }

        /// <inheritdoc />
        public IEnumerable<(string Name, string? ColorCode)> GetAllCategories()
        {
            // TODO: Implémenter via IOutlookApplicationWrapper lors de la phase Infrastructure COM
            throw new NotImplementedException("L'implémentation COM pour lire la Master Category List sera faite ultérieurement.");
        }

        /// <inheritdoc />
        public void AddCategory(string name, string colorCode)
        {
            if (!_outlookWrapper.CategoryExists(name))
            {
                _outlookWrapper.AddCategory(name, colorCode);
            }
        }

        /// <inheritdoc />
        public void UpdateCategoryColor(string name, string newColorCode)
        {
            if (_outlookWrapper.CategoryExists(name))
            {
                _outlookWrapper.UpdateCategory(name, newColorCode);
            }
        }

        /// <inheritdoc />
        public void RemoveCategory(string name)
        {
            if (_outlookWrapper.CategoryExists(name))
            {
                _outlookWrapper.RemoveCategory(name);
            }
        }
    }
}