#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création de la classe concrète (J4-S3-T1 - Phase Verte).
//         - 2026-09-16 : Remplacement de new Application() par GetTypeFromProgID (Phase Orange).
//         - 2026-09-16 : Passage en 100% Late Binding (dynamic) pour supprimer la dépendance à office.dll (Phase Orange).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Catamailer.Domain;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Implémentation concrète de l'abstraction COM Outlook via Late Binding (dynamic).
    /// </summary>
    public class OutlookApplicationWrapper : IOutlookApplicationWrapper
    {
        private readonly dynamic _application;

#pragma warning disable CS0067 // L'événement n'est jamais utilisé
        /// <inheritdoc />
        public event Action<string>? OnNewMailEx;
#pragma warning restore CS0067

        /// <summary>
        /// Initialise une nouvelle instance de OutlookApplicationWrapper et attache l'application COM dynamiquement.
        /// </summary>
        public OutlookApplicationWrapper()
        {
            Type? outlookType = Type.GetTypeFromProgID("Outlook.Application");
            if (outlookType == null)
            {
                throw new InvalidOperationException("Impossible de localiser Outlook sur ce système.");
            }

            object? instance = Activator.CreateInstance(outlookType);
            if (instance == null)
            {
                throw new InvalidOperationException("Impossible d'instancier l'application Outlook via COM.");
            }

            _application = instance;
            
            // TODO: L'abonnement natif à l'événement NewMailEx devra être implémenté ici
        }

        /// <inheritdoc />
        public IEnumerable<(string Name, string? ColorCode)> GetMasterCategories()
        {
            var categoriesList = new List<(string Name, string? ColorCode)>();
            var categories = _application.Session.Categories;
            
            // En Late Binding COM, on favorise la boucle for à base 1 plutôt que foreach pour éviter les erreurs d'énumérateur
            int count = categories.Count;

            for (int i = 1; i <= count; i++)
            {
                dynamic category = categories[i];
                categoriesList.Add((category.Name, MapOlCategoryColorToHex((int)category.Color)));
            }

            return categoriesList;
        }

        /// <summary>
        /// Convertit l'énumération native OlCategoryColor en code couleur hexadécimal standard.
        /// </summary>
        private string? MapOlCategoryColorToHex(int olColor)
        {
            return olColor switch
            {
                1 => "#E74C3C",  // olCategoryColorRed
                2 => "#E67E22",  // olCategoryColorOrange
                3 => "#FFDAB9",  // olCategoryColorPeach
                4 => "#F1C40F",  // olCategoryColorYellow
                5 => "#2ECC71",  // olCategoryColorGreen
                6 => "#1ABC9C",  // olCategoryColorTeal
                7 => "#808000",  // olCategoryColorOlive
                8 => "#3498DB",  // olCategoryColorBlue
                9 => "#9B59B6",  // olCategoryColorPurple
                10 => "#800000", // olCategoryColorMaroon
                11 => "#4682B4", // olCategoryColorSteel
                12 => "#2F4F4F", // olCategoryColorDarkSteel
                13 => "#808080", // olCategoryColorGray
                14 => "#A9A9A9", // olCategoryColorDarkGray
                15 => "#000000", // olCategoryColorBlack
                16 => "#8B0000", // olCategoryColorDarkRed
                17 => "#FF8C00", // olCategoryColorDarkOrange
                18 => "#FFDAB9", // olCategoryColorDarkPeach (Approximation)
                19 => "#B8860B", // olCategoryColorDarkYellow
                20 => "#006400", // olCategoryColorDarkGreen
                21 => "#008080", // olCategoryColorDarkTeal
                22 => "#556B2F", // olCategoryColorDarkOlive
                23 => "#00008B", // olCategoryColorDarkBlue
                24 => "#800080", // olCategoryColorDarkPurple
                25 => "#800000", // olCategoryColorDarkMaroon
                _ => null        // 0 = olCategoryColorNone ou couleur inconnue
            };
        }

        // ====================================================================================
        // MÉTHODES EN ATTENTE D'IMPLÉMENTATION NATIVE (BOUCHONS POUR COMPILATION)
        // ====================================================================================

        /// <inheritdoc />
        public MailMetadata GetMailMetadata(string entryId)
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }

        /// <inheritdoc />
        public string? GetSelectedEntryId()
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }

        /// <inheritdoc />
        public bool CategoryExists(string name)
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }

        /// <inheritdoc />
        public void AddCategory(string name, string colorCode)
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }

        /// <inheritdoc />
        public void UpdateCategory(string name, string newColorCode)
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }

        /// <inheritdoc />
        public void RemoveCategory(string name)
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }

        /// <inheritdoc />
        public void ReplaceCategoryOnAllItems(string oldCategoryName, string newCategoryName)
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }

        /// <inheritdoc />
        public IEnumerable<string> GetNextUnprocessedMailEntryIds(string? lastEntryId, int maxItems)
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }
    }
}