#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création de la classe concrète (J4-S3-T1 - Phase Verte).
//         - 2026-09-16 : Remplacement de new Application() par GetTypeFromProgID (Phase Orange).
//         - 2026-09-16 : Passage en 100% Late Binding (dynamic) pour supprimer la dépendance à office.dll (Phase Orange).
//         - 2026-09-17 : Implémentation des méthodes CRUD de la MCL et RenameCategory (J4-S4-T3 - Phase Verte).
//         - 2026-09-17 : Ajustement de la palette hexadécimale pour correspondre aux couleurs natives d'Outlook (J4-S4-T3 - Phase Orange).
//         - 2026-09-23 : Implémentation de IDisposable pour libération COM (J4-S4-T7 - Phase Orange).
//         - 2026-09-23 : Remplacement des boucles en O(N) par l'indexeur string en O(1) pour éradiquer la saturation RPC (J4-S4-T7 - Phase Orange).
//         - 2026-09-23 : Ajout des bouchons pour les actions physiques (J5-S2-T1 - Phase Rouge).
//         - 2026-09-23 : Implémentation des actions physiques via Late Binding COM (J5-S2-T1 - Phase Verte).
//         - 2026-09-24 : Ajout du bouchon pour l'arborescence des dossiers (J5-S2-T2 - Phase Rouge).
//         - 2026-09-24 : Implémentation de GetAvailableFolderPaths récursive à la racine (J5-S2-T2 - Phase Verte).
//         - 2026-09-24 : Implémentation de la lecture des fichiers de signature HTML (J5-S2-T3 - Phase Verte).
//         - 2026-09-24 : Implémentation de IExternalResourceProvider (J6-S1-T1 - Phase Rouge).
//         - 2026-09-24 : Implémentation de GetAvailableSignatures (J6-S1-T1 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Implémentation concrète de l'abstraction COM Outlook via Late Binding (dynamic).
    /// </summary>
    public class OutlookApplicationWrapper : IOutlookApplicationWrapper
    {
        private readonly dynamic _application;

#pragma warning disable CS0067 // L'événement n'est jamais utilisé
        /// <inheritdoc />
        public event Action<string>? OnNewMailEx;
#pragma warning restore CS0067

        /// <summary>
        /// Initialise une nouvelle instance de OutlookApplicationWrapper et attache l'application COM dynamiquement.
        /// </summary>
        public OutlookApplicationWrapper()
        {
            Type? outlookType = Type.GetTypeFromProgID("Outlook.Application");
            if (outlookType == null)
            {
                throw new InvalidOperationException("Impossible de localiser Outlook sur ce système.");
            }

            object? instance = Activator.CreateInstance(outlookType);
            if (instance == null)
            {
                throw new InvalidOperationException("Impossible d'instancier l'application Outlook via COM.");
            }

            _application = instance;
            
            // TODO: L'abonnement natif à l'événement NewMailEx devra être implémenté ici
        }

        /// <summary>
        /// Récupère un élément Outlook depuis son EntryID via la session courante.
        /// </summary>
        private dynamic GetItemFromId(string entryId)
        {
            return _application.Session.GetItemFromID(entryId);
        }

        /// <inheritdoc />
        public IEnumerable<(string Name, string? ColorCode)> GetMasterCategories()
        {
            var categoriesList = new List<(string Name, string? ColorCode)>();
            var categories = _application.Session.Categories;
            
            // En Late Binding COM, on favorise la boucle for à base 1 plutôt que foreach pour éviter les erreurs d'énumérateur
            int count = categories.Count;

            for (int i = 1; i <= count; i++)
            {
                dynamic category = categories[i];
                categoriesList.Add((category.Name, MapOlCategoryColorToHex((int)category.Color)));
            }

            return categoriesList;
        }
        
        /// <inheritdoc />
        public bool CategoryExists(string name)
        {
             try
             {
                 // Utilisation de l'indexeur direct O(1) au lieu d'une boucle O(N) coûteuse en RPC
                 var category = _application.Session.Categories[name];
                 return category != null;
             }
             catch
             {
                 return false;
             }
        }

        /// <inheritdoc />
        public void AddCategory(string name, string colorCode)
        {
            if (CategoryExists(name))
            {
                return;
            }
            
            int olColor = MapHexToOlCategoryColor(colorCode);
            _application.Session.Categories.Add(name, olColor);
        }

        /// <inheritdoc />
        public void UpdateCategory(string name, string newColorCode)
        {
             try
             {
                 var category = _application.Session.Categories[name];
                 category.Color = MapHexToOlCategoryColor(newColorCode);
             }
             catch
             {
                 // Ignorer si la catégorie n'existe pas
             }
        }
        
        /// <inheritdoc />
        public void RenameCategory(string oldName, string newName)
        {
             try
             {
                 var category = _application.Session.Categories[oldName];
                 category.Name = newName;
             }
             catch
             {
                 // Ignorer si la catégorie n'existe pas
             }
        }

        /// <inheritdoc />
        public void RemoveCategory(string name)
        {
             try
             {
                 var category = _application.Session.Categories[name];
                 if (category != null)
                 {
                     _application.Session.Categories.Remove(name);
                 }
             }
             catch
             {
                 // Ignorer si la catégorie n'existe pas
             }
        }

        /// <summary>
        /// Convertit l'énumération native OlCategoryColor en code couleur hexadécimal standard.
        /// </summary>
        private string? MapOlCategoryColorToHex(int olColor)
        {
            return olColor switch
            {
                1 => "#DC626D",
                2 => "#E8825D",
                3 => "#FFCD8F",
                4 => "#FDEE65",
                5 => "#52CE90",
                6 => "#57D2DA",
                7 => "#B6D767",
                8 => "#5CA9E5",
                9 => "#B1AAEB",
                10 => "#E3008C",
                11 => "#C5CED1",
                12 => "#4497A9",
                13 => "#C3C5BB",
                14 => "#9FADB1",
                15 => "#8F8F8F",
                16 => "#AC4E5E",
                17 => "#DF8E64",
                18 => "#BC8F6F",
                19 => "#DAC257",
                20 => "#4CA64C",
                21 => "#4BB4B7",
                22 => "#85B44C",
                23 => "#4179A3",
                24 => "#A589CB",
                25 => "#C34E98",
                _ => null
            };
        }
        
        /// <summary>
        /// Convertit un code couleur hexadécimal en entier correspondant à OlCategoryColor.
        /// </summary>
        private int MapHexToOlCategoryColor(string? hexColor)
        {
             if (string.IsNullOrEmpty(hexColor)) return 0; // olCategoryColorNone
             
             return hexColor.ToUpperInvariant() switch
             {
                 "#DC626D" => 1,
                 "#E8825D" => 2,
                 "#FFCD8F" => 3,
                 "#FDEE65" => 4,
                 "#52CE90" => 5,
                 "#57D2DA" => 6,
                 "#B6D767" => 7,
                 "#5CA9E5" => 8,
                 "#B1AAEB" => 9,
                 "#E3008C" => 10,
                 "#C5CED1" => 11,
                 "#4497A9" => 12,
                 "#C3C5BB" => 13,
                 "#9FADB1" => 14,
                 "#8F8F8F" => 15,
                 "#AC4E5E" => 16,
                 "#DF8E64" => 17,
                 "#BC8F6F" => 18,
                 "#DAC257" => 19,
                 "#4CA64C" => 20,
                 "#4BB4B7" => 21,
                 "#85B44C" => 22,
                 "#4179A3" => 23,
                 "#A589CB" => 24,
                 "#C34E98" => 25,
                 _ => 0
             };
        }

        // ====================================================================================
        // LECTURE DE L'ENVIRONNEMENT ET ARBORESCENCE (J5-S2-T2 / J6-S1-T1)
        // ====================================================================================

        /// <inheritdoc />
        public IEnumerable<string> GetAvailableFolderPaths()
        {
            var folderPaths = new List<string>();
            try
            {
                dynamic inbox = _application.Session.GetDefaultFolder(6);
                dynamic rootStore = inbox.Parent;
                TraverseFolders(rootStore.Folders, "", folderPaths);
            }
            catch
            {
                // En cas d'erreur COM
            }
            return folderPaths;
        }

        private void TraverseFolders(dynamic foldersCollection, string currentPath, List<string> folderPaths)
        {
            int count = foldersCollection.Count;
            for (int i = 1; i <= count; i++)
            {
                dynamic folder = foldersCollection[i];
                string folderName = folder.Name;
                string fullPath = string.IsNullOrEmpty(currentPath) ? folderName : $"{currentPath}/{folderName}";
                folderPaths.Add(fullPath);

                if (folder.Folders.Count > 0)
                {
                    TraverseFolders(folder.Folders, fullPath, folderPaths);
                }
            }
        }

        /// <inheritdoc />
        public IEnumerable<string> GetAvailableSignatures()
        {
            var signatures = new List<string>();
            try
            {
                string appDataPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
                string signatureDir = Path.Combine(appDataPath, "Microsoft", "Signatures");

                if (Directory.Exists(signatureDir))
                {
                    var files = Directory.GetFiles(signatureDir, "*.htm");
                    foreach (var file in files)
                    {
                        signatures.Add(Path.GetFileNameWithoutExtension(file));
                    }
                }
            }
            catch
            {
                // Ignorer en cas d'erreur d'accès au système de fichiers
            }
            return signatures;
        }

        // Implémentation explicite de l'interface IExternalResourceProvider
        Task<IEnumerable<string>> IExternalResourceProvider.GetAvailableFolderPathsAsync()
        {
            return Task.FromResult(GetAvailableFolderPaths());
        }

        Task<IEnumerable<string>> IExternalResourceProvider.GetAvailableSignaturesAsync()
        {
            return Task.FromResult(GetAvailableSignatures());
        }

        // ====================================================================================
        // ACTIONS PHYSIQUES D'EXÉCUTION (J5-S2-T1)
        // ====================================================================================

        /// <inheritdoc />
        public void MoveToFolder(string entryId, string folderPath)
        {
            var item = GetItemFromId(entryId);
            
            dynamic rootStore = _application.Session.GetDefaultFolder(6).Parent;
            dynamic? targetFolder = ResolveFolderFromPath(rootStore.Folders, folderPath);
            
            if (targetFolder != null)
            {
                item.Move(targetFolder);
            }
            else
            {
                dynamic fallbackFolder = _application.Session.GetDefaultFolder(6);
                item.Move(fallbackFolder);
            }
        }
        
        private dynamic? ResolveFolderFromPath(dynamic rootFolders, string path)
        {
            var parts = path.Split('/', StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length == 0) return null;

            dynamic currentCollection = rootFolders;
            dynamic? currentFolder = null;

            foreach (var part in parts)
            {
                bool found = false;
                int count = currentCollection.Count;
                
                for (int i = 1; i <= count; i++)
                {
                    dynamic f = currentCollection[i];
                    if (string.Equals(f.Name, part, StringComparison.OrdinalIgnoreCase))
                    {
                        currentFolder = f;
                        currentCollection = f.Folders;
                        found = true;
                        break;
                    }
                }
                
                if (!found) return null;
            }

            return currentFolder;
        }

        /// <inheritdoc />
        public void MarkAsRead(string entryId)
        {
            var item = GetItemFromId(entryId);
            item.UnRead = false;
            item.Save();
        }

        /// <inheritdoc />
        public void FlagForFollowUp(string entryId)
        {
            var item = GetItemFromId(entryId);
            item.MarkAsTask(1); // olMarkNoDate
            item.Save();
        }

        /// <inheritdoc />
        public void Forward(string entryId, string recipients)
        {
            var item = GetItemFromId(entryId);
            var forwardItem = item.Forward();
            forwardItem.Recipients.Add(recipients);
            forwardItem.Send();
        }

        /// <inheritdoc />
        public void SetImportance(string entryId, string importanceLevel)
        {
            var item = GetItemFromId(entryId);
            item.Importance = importanceLevel.ToLowerInvariant() switch
            {
                "haute" => 2,   // olImportanceHigh
                "faible" => 0,  // olImportanceLow
                _ => 1          // olImportanceNormal
            };
            item.Save();
        }

        /// <inheritdoc />
        public void AddReminder(string entryId, DateTime reminderTime)
        {
            var item = GetItemFromId(entryId);
            item.ReminderSet = true;
            item.ReminderTime = reminderTime;
            item.Save();
        }

        /// <inheritdoc />
        public void FlagToday(string entryId)
        {
            var item = GetItemFromId(entryId);
            item.MarkAsTask(2); // olMarkToday
            item.Save();
        }

        /// <inheritdoc />
        public void InsertHtmlSignature(string entryId, string signatureName)
        {
            string appDataPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            string signatureDir = Path.Combine(appDataPath, "Microsoft", "Signatures");
            string signatureFilePath = Path.Combine(signatureDir, $"{signatureName}.htm");

            if (!File.Exists(signatureFilePath))
            {
                throw new FileNotFoundException($"Signature introuvable sur le disque : {signatureFilePath}");
            }

            string htmlContent = File.ReadAllText(signatureFilePath);

            string imageFolderRelative = $"{signatureName}_files/";
            string imageFolderRelativeEncoded = $"{signatureName.Replace(" ", "%20")}_files/";
            string imageFolderAbsolute = Path.Combine(signatureDir, $"{signatureName}_files/");

            htmlContent = htmlContent.Replace(imageFolderRelative, imageFolderAbsolute);
            htmlContent = htmlContent.Replace(imageFolderRelativeEncoded, imageFolderAbsolute);

            var item = GetItemFromId(entryId);
            item.HTMLBody = item.HTMLBody + "<br/><br/>" + htmlContent;
            item.Save();
        }

        // ====================================================================================
        // MÉTHODES EN ATTENTE D'IMPLÉMENTATION NATIVE (BOUCHONS POUR COMPILATION)
        // ====================================================================================

        /// <inheritdoc />
        public MailMetadata GetMailMetadata(string entryId)
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }

        /// <inheritdoc />
        public string? GetSelectedEntryId()
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }

        /// <inheritdoc />
        public void ReplaceCategoryOnAllItems(string oldCategoryName, string newCategoryName)
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }

        /// <inheritdoc />
        public IEnumerable<string> GetNextUnprocessedMailEntryIds(string? lastEntryId, int maxItems)
        {
            throw new NotImplementedException("Implémentation COM manquante.");
        }

        /// <inheritdoc />
        public void Dispose()
        {
            if (_application != null)
            {
                try
                {
                    Marshal.ReleaseComObject(_application);
                }
                catch
                {
                    // Ignorer les erreurs de libération COM
                }
            }
            GC.SuppressFinalize(this);
        }
    }
}