// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-07 : Implémentation (Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using Catamailer.Domain;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Implémentation du fournisseur de sélection basée sur l'Interop COM Outlook.
    /// </summary>
    public class OutlookSelectionProvider : ISelectionProvider
    {
        private readonly IOutlookApplicationWrapper _outlookWrapper;

        /// <summary>
        /// Initialise une nouvelle instance de OutlookSelectionProvider.
        /// </summary>
        /// <param name="outlookWrapper">L'abstraction de l'application Outlook.</param>
        public OutlookSelectionProvider(IOutlookApplicationWrapper outlookWrapper)
        {
            _outlookWrapper = outlookWrapper;
        }

        /// <summary>
        /// Récupère les métadonnées de l'e-mail actuellement sélectionné.
        /// </summary>
        /// <returns>Les métadonnées de l'e-mail, ou null si aucun e-mail n'est sélectionné.</returns>
        public MailMetadata? GetSelectedMail()
        {
            var entryId = _outlookWrapper.GetSelectedEntryId();
            
            if (string.IsNullOrEmpty(entryId))
            {
                return null;
            }

            return _outlookWrapper.GetMailMetadata(entryId);
        }
    }
}