// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-25
//     Historique :
//         - 2026-09-25 : Création initiale de l'implémentation bouchonnée (J6-S3-T5 - Phase Rouge).
//         - 2026-09-25 : Implémentation EF Core des méthodes CRUD (J6-S3-T5 - Phase Verte).
//         - 2026-09-25 : Ajout de UpdateDictionaryRuleAsync bouchonné (J6-S3-T6 - Phase Rouge).
//         - 2026-09-25 : Implémentation EF Core de UpdateDictionaryRuleAsync (J6-S3-T6 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Catamailer.Domain;
using Microsoft.EntityFrameworkCore;

namespace Catamailer.Infrastructure
{
    /// <summary>
    /// Implémentation Entity Framework Core du dépôt des règles de classification et d'exécution.
    /// </summary>
    public class RuleRepository : IRuleRepository
    {
        private readonly CatamailerDbContext _dbContext;

        /// <summary>
        /// Initialise une nouvelle instance de la classe <see cref="RuleRepository"/>.
        /// </summary>
        /// <param name="dbContext">Le contexte de base de données.</param>
        public RuleRepository(CatamailerDbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        /// <inheritdoc />
        public async Task<IEnumerable<DictionaryRule>> GetAllDictionaryRulesAsync()
        {
            return await _dbContext.DictionaryRules
                .Include(r => r.TargetCategory)
                .ToListAsync();
        }

        /// <inheritdoc />
        public async Task AddDictionaryRuleAsync(DictionaryRule rule)
        {
            await _dbContext.DictionaryRules.AddAsync(rule);
            await _dbContext.SaveChangesAsync();
        }

        /// <inheritdoc />
        public async Task UpdateDictionaryRuleAsync(DictionaryRule rule)
        {
            _dbContext.DictionaryRules.Update(rule);
            await _dbContext.SaveChangesAsync();
        }

        /// <inheritdoc />
        public async Task DeleteDictionaryRuleAsync(DictionaryRule rule)
        {
            _dbContext.DictionaryRules.Remove(rule);
            await _dbContext.SaveChangesAsync();
        }

        /// <inheritdoc />
        public async Task<IEnumerable<ExecutionRule>> GetAllExecutionRulesAsync()
        {
            return await _dbContext.ExecutionRules.ToListAsync();
        }

        /// <inheritdoc />
        public async Task AddExecutionRuleAsync(ExecutionRule rule)
        {
            await _dbContext.ExecutionRules.AddAsync(rule);
            await _dbContext.SaveChangesAsync();
        }

        /// <inheritdoc />
        public async Task DeleteExecutionRuleAsync(ExecutionRule rule)
        {
            _dbContext.ExecutionRules.Remove(rule);
            await _dbContext.SaveChangesAsync();
        }
    }
}