// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-23
//     Historique :
//         - 2026-09-23 : Création du test d'intégration de performance (J4-S4-T7 - Phase Orange).
//         - 2026-09-23 : Ajout du pattern using sur IOutlookApplicationWrapper pour corriger la fuite COM (J4-S4-T7).
//         - 2026-09-23 : Injection de 250 catégories pour simuler une charge réelle de synchronisation vers Outlook (J4-S4-T7).
//         - 2026-09-24 : Suppression des traces de diagnostic interne (ITestOutputHelper) pour rendre le succès silencieux (J5-S2-T2 - Phase Orange).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using Catamailer.Application.Services;
using Catamailer.Application.ViewModels;
using Catamailer.Domain;
using Catamailer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Catamailer.Infrastructure.IntegrationTests
{
    public class CategorySyncPerformanceTests : IDisposable
    {
        private readonly string _dbPath;
        private readonly CatamailerDbContext _context;

        public CategorySyncPerformanceTests()
        {
            // Création d'une base SQLite temporaire dédiée au test pour ne pas impacter tes données
            _dbPath = Path.Combine(Path.GetTempPath(), $"catamailer_perf_{Guid.NewGuid()}.db");
            var options = new DbContextOptionsBuilder<CatamailerDbContext>()
                .UseSqlite($"Data Source={_dbPath}")
                .Options;

            _context = new CatamailerDbContext(options);
            _context.Database.EnsureCreated();
        }

        [Fact]
        public async Task SyncCategories_ShouldExecute_WithinAcceptableTimeframe()
        {
            // Arrange
            for (int i = 0; i < 50; i++)
            {
                var parent = new CategoryNode($"TestParent_{i}", "#111111");
                _context.Categories.Add(parent);
                for (int j = 0; j < 4; j++)
                {
                    var child = new CategoryNode($"TestChild_{i}_{j}", "#222222");
                    parent.AddChild(child);
                    _context.Categories.Add(child);
                }
            }
            await _context.SaveChangesAsync();

            var repository = new CategoryRepository(_context);
            
            // Attention : Nécessite qu'Outlook soit lancé sur le poste exécutant le test. Utilisation de using pour libérer l'objet COM.
            using var outlookWrapper = new OutlookApplicationWrapper(); 
            var outlookProvider = new OutlookCategoryManagerProvider(outlookWrapper);
            var syncService = new CategorySyncService(repository, outlookProvider);
            var viewModel = new CategorySyncViewModel(syncService, repository, outlookProvider);

            var sw = Stopwatch.StartNew();
            
            // Act 1 : Analyse
            await viewModel.InitializeAsync();

            // On simule que l'utilisateur a tout coché pour pousser les 250 catégories SQLite vers la MCL Outlook
            viewModel.SelectAllMissingInOutlook = true;

            // Act 2 : Résolution
            await viewModel.ApplyResolutionsAsync();
            
            sw.Stop();

            // Assert : On valide que le traitement complet prend moins de 10 secondes (10000 ms)
            // Note: Le temps sera dominé par les appels COM, mais le blocage SQLite a été éliminé.
            Assert.True(sw.ElapsedMilliseconds < 10000, $"La synchronisation est trop lente : {sw.ElapsedMilliseconds} ms (limite fixée à 10000 ms).");
        }

        public void Dispose()
        {
            // Nettoyage complet après le test
            _context.Database.EnsureDeleted();
            _context.Dispose();
            if (File.Exists(_dbPath))
            {
                File.Delete(_dbPath);
            }
        }
    }
}