// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-23
//     Historique :
//         - 2026-09-23 : Création initiale des tests d'intégration des actions (J5-S2-T1 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using Xunit;

namespace Catamailer.Infrastructure.IntegrationTests
{
    /// <summary>
    /// Classe de tests d'intégration pour les actions physiques COM. 
    /// En Phase Rouge, ces tests s'attendent à ce que l'appel N'ÉCHOUE PAS avec une NotImplementedException.
    /// </summary>
    public class OutlookActionsIntegrationTests : IDisposable
    {
        private readonly OutlookApplicationWrapper _wrapper;

        public OutlookActionsIntegrationTests()
        {
            _wrapper = new OutlookApplicationWrapper();
        }

        [Fact]
        public void MoveToFolder_ShouldNotThrowNotImplementedException()
        {
            var exception = Record.Exception(() => _wrapper.MoveToFolder("dummy_id", "Inbox"));
            Assert.IsNotType<NotImplementedException>(exception);
        }

        [Fact]
        public void MarkAsRead_ShouldNotThrowNotImplementedException()
        {
            var exception = Record.Exception(() => _wrapper.MarkAsRead("dummy_id"));
            Assert.IsNotType<NotImplementedException>(exception);
        }

        [Fact]
        public void FlagForFollowUp_ShouldNotThrowNotImplementedException()
        {
            var exception = Record.Exception(() => _wrapper.FlagForFollowUp("dummy_id"));
            Assert.IsNotType<NotImplementedException>(exception);
        }

        [Fact]
        public void Forward_ShouldNotThrowNotImplementedException()
        {
            var exception = Record.Exception(() => _wrapper.Forward("dummy_id", "test@domain.com"));
            Assert.IsNotType<NotImplementedException>(exception);
        }

        [Fact]
        public void SetImportance_ShouldNotThrowNotImplementedException()
        {
            var exception = Record.Exception(() => _wrapper.SetImportance("dummy_id", "Haute"));
            Assert.IsNotType<NotImplementedException>(exception);
        }

        [Fact]
        public void AddReminder_ShouldNotThrowNotImplementedException()
        {
            var exception = Record.Exception(() => _wrapper.AddReminder("dummy_id", DateTime.Now.AddDays(1)));
            Assert.IsNotType<NotImplementedException>(exception);
        }

        [Fact]
        public void FlagToday_ShouldNotThrowNotImplementedException()
        {
            var exception = Record.Exception(() => _wrapper.FlagToday("dummy_id"));
            Assert.IsNotType<NotImplementedException>(exception);
        }

        [Fact]
        public void InsertHtmlSignature_ShouldNotThrowNotImplementedException()
        {
            var exception = Record.Exception(() => _wrapper.InsertHtmlSignature("dummy_id", "Signature_Default"));
            Assert.IsNotType<NotImplementedException>(exception);
        }

        public void Dispose()
        {
            _wrapper.Dispose();
        }
    }
}