// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-24
//     Historique :
//         - 2026-09-24 : Création du parseur avec exception pour TDD (J6-S1-T2 - Phase Rouge).
//         - 2026-09-24 : Implémentation de l'algorithme de nettoyage et d'extraction (J6-S1-T2 - Phase Verte).
//         - 2026-09-24 : Correction du nettoyage pour ignorer les lignes sans champ ou catégorie valides (J6-S1-T2 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;

namespace Catamailer.Migrator.Parsing
{
    /// <summary>
    /// Implémentation du parseur CSV spécifique au format historique de Catamailer.
    /// </summary>
    public class CsvParser : ICsvParser
    {
        /// <inheritdoc />
        public IEnumerable<CsvRuleRecord> ParseLines(IEnumerable<string> lines)
        {
            var records = new List<CsvRuleRecord>();

            foreach (var line in lines)
            {
                if (string.IsNullOrWhiteSpace(line))
                {
                    continue;
                }

                var trimmedLine = line.Trim();

                if (trimmedLine.StartsWith("#"))
                {
                    continue;
                }

                var parts = trimmedLine.Split(';');

                // Une ligne valide doit au moins contenir le Champ et la Catégorie
                if (parts.Length < 2)
                {
                    continue;
                }

                var field = parts[0].Trim();
                var categoryName = parts[1].Trim();

                // On ignore les lignes constituées uniquement de points-virgules ou incomplètes
                if (string.IsNullOrWhiteSpace(field) || string.IsNullOrWhiteSpace(categoryName))
                {
                    continue;
                }

                var keywords = new List<string>();

                // Extraction des mots-clés à partir de la 3ème colonne
                for (int i = 2; i < parts.Length; i++)
                {
                    var keyword = parts[i].Trim();
                    if (!string.IsNullOrEmpty(keyword))
                    {
                        keywords.Add(keyword);
                    }
                }

                records.Add(new CsvRuleRecord(field, categoryName, keywords));
            }

            return records;
        }
    }
}