// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-24
//     Historique :
//         - 2026-09-24 : Création du DTO pour le parsing CSV (J6-S1-T2 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;

namespace Catamailer.Migrator.Parsing
{
    /// <summary>
    /// Représente une ligne brute extraite du fichier CSV de configuration des règles.
    /// </summary>
    public class CsvRuleRecord
    {
        /// <summary>
        /// Obtient le champ d'application (SUJET, EXPEDITEUR, DESTINATAIRE).
        /// </summary>
        public string Field { get; }

        /// <summary>
        /// Obtient le nom de la catégorie associée.
        /// </summary>
        public string CategoryName { get; }

        /// <summary>
        /// Obtient la liste des mots-clés nettoyés.
        /// </summary>
        public IReadOnlyList<string> Keywords { get; }

        /// <summary>
        /// Initialise une nouvelle instance de <see cref="CsvRuleRecord"/>.
        /// </summary>
        /// <param name="field">Le champ d'application.</param>
        /// <param name="categoryName">Le nom de la catégorie.</param>
        /// <param name="keywords">La liste des mots-clés.</param>
        public CsvRuleRecord(string field, string categoryName, IReadOnlyList<string> keywords)
        {
            Field = field;
            CategoryName = categoryName;
            Keywords = keywords;
        }
    }
}