// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-24
//     Historique :
//         - 2026-09-24 : Création de l'interface du parseur CSV (J6-S1-T2 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;

namespace Catamailer.Migrator.Parsing
{
    /// <summary>
    /// Définit le contrat pour l'extraction brute des règles depuis un format CSV.
    /// </summary>
    public interface ICsvParser
    {
        /// <summary>
        /// Parse un ensemble de lignes textuelles issues d'un fichier CSV pour en extraire les règles.
        /// </summary>
        /// <param name="lines">Les lignes brutes du fichier CSV.</param>
        /// <returns>Une énumération d'enregistrements parsés et nettoyés.</returns>
        IEnumerable<CsvRuleRecord> ParseLines(IEnumerable<string> lines);
    }
}