// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-09
//     Historique :
//         - 2026-09-09 : Création pour externaliser l'amorçage EF Core (J3-S3-T0 - Phase Orange).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using Catamailer.Infrastructure;
using Microsoft.Extensions.DependencyInjection;

namespace Catamailer.UI
{
    /// <summary>
    /// Gère l'initialisation de l'infrastructure de base de données.
    /// </summary>
    public static class DatabaseBootstrapper
    {
        /// <summary>
        /// S'assure que le schéma de la base de données est créé.
        /// </summary>
        /// <param name="serviceProvider">Le fournisseur de services de l'application.</param>
        public static void EnsureDatabaseCreated(this IServiceProvider serviceProvider)
        {
            using var scope = serviceProvider.CreateScope();
            var dbContext = scope.ServiceProvider.GetRequiredService<CatamailerDbContext>();
            
            dbContext.Database.EnsureCreated();
        }
    }
}