// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-08 : Configuration du démarrage et ajout de H.NotifyIcon (J3-S1-T1).
//         - 2026-09-08 : Injection de IGlobalHotkeyService (J3-S1-T2).
//         - 2026-09-08 : Injection de QuickCategorizeViewModel, EF Core et Infrastructure (J3-S2-T1).
//         - 2026-09-08 : Injection de QuickRuleBuilderViewModel et d'un DummySelectionProvider (J3-S2-T2).
//         - 2026-09-09 : Injection de IRuleRepository et ClassificationEngine (J3-S2-T2-ST2).
//         - 2026-09-09 : Injection de ShadowModeDashboardViewModel et IShadowModeService (J3-S3-T1).
//         - 2026-09-09 : Refactoring de l'initialisation et extraction des Dummies (J3-S3-T0).
//         - 2026-09-09 : Injection de CategoryTreeViewModel (J3-S3-T2).
//         - 2026-09-11 : Injection de DictionaryEditorViewModel (J3-S3-T3-ST1).
//         - 2026-09-11 : Injection de RuleBuilderViewModel (J3-S3-T3-ST2).
//         - 2026-09-15 : Injection de PreferencesViewModel (J3-S3-T4).
//         - 2026-09-15 : Injection de IBlazorNavigationService (J3-S3-T7).
//         - 2026-09-15 : Injection de ActivationPromptViewModel (J3-S3-T5).
//         - 2026-09-15 : Injection de ICategorySyncService et CategorySyncViewModel (J4-S2).
//         - 2026-09-16 : Remplacement du Dummy par l'intégration COM réelle via OutlookApplicationWrapper (J4-S3-T1).
//         - 2026-09-24 : Injection de IExternalResourceProvider (J6-S1-T1 - Phase Orange).
//         - 2026-09-25 : Nettoyage final des Dummies et injection de RuleRepository et OutlookSelectionProvider (J6-S3-T5 - Phase Bleue).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.IO;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.Maui.Storage;
using H.NotifyIcon;
using Catamailer.Domain;
using Catamailer.Infrastructure;
using Catamailer.Application;
using Catamailer.Application.ViewModels;
using Catamailer.Application.Services;
using Microsoft.Extensions.DependencyInjection;

namespace Catamailer.UI
{
    /// <summary>
    /// Classe statique responsable de l'amorçage et de la configuration de l'application MAUI Blazor.
    /// </summary>
    public static class MauiProgram
    {
        /// <summary>
        /// Crée et configure l'instance principale de l'application MAUI.
        /// Injecte les dépendances Blazor et initialise le composant de zone de notification (Tray Icon).
        /// </summary>
        /// <returns>Une instance configurée de <see cref="MauiApp"/>.</returns>
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .UseNotifyIcon() // Enregistrement du composant Tray Icon
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                });

            // Configuration de la base de données SQLite dans le dossier local de l'application
            string dbPath = Path.Combine(FileSystem.AppDataDirectory, "catamailer.db");
            builder.Services.AddDbContext<CatamailerDbContext>(options =>
                options.UseSqlite($"Data Source={dbPath}"));

            // Injection des services de domaine et d'application
            builder.Services.AddTransient<ClassificationEngine>();
            builder.Services.AddScoped<IShadowModeService, ShadowModeService>();
            builder.Services.AddScoped<ICategorySyncService, CategorySyncService>();
            
            // Le service de navigation doit être Singleton pour faire le pont entre l'hôte global et Blazor
            builder.Services.AddSingleton<IBlazorNavigationService, BlazorNavigationService>();

            // Injection des services d'infrastructure
            builder.Services.AddScoped<ICategoryRepository, CategoryRepository>();
            builder.Services.AddScoped<IAppSettingsRepository, AppSettingsRepository>();
            builder.Services.AddScoped<IHistoryStateRepository, HistoryStateRepository>();
            builder.Services.AddScoped<IRuleRepository, RuleRepository>();
            builder.Services.AddSingleton<IGlobalHotkeyService, Win32GlobalHotkeyService>();
            
            // Injection COM Réelle
            builder.Services.AddSingleton<IOutlookApplicationWrapper, OutlookApplicationWrapper>();
            builder.Services.AddScoped<ICategoryManagerProvider, OutlookCategoryManagerProvider>();
            builder.Services.AddScoped<ISelectionProvider, OutlookSelectionProvider>();
            
            // Injection de l'interface de ressources externes liée à l'instance COM d'Outlook
            builder.Services.AddSingleton<IExternalResourceProvider>(sp => sp.GetRequiredService<IOutlookApplicationWrapper>());
            
            // Injection des ViewModels (Transient pour réinitialiser l'état à chaque appel)
            builder.Services.AddTransient<QuickCategorizeViewModel>();
            builder.Services.AddTransient<QuickRuleBuilderViewModel>();
            builder.Services.AddTransient<ShadowModeDashboardViewModel>();
            builder.Services.AddTransient<CategoryTreeViewModel>();
            builder.Services.AddTransient<DictionaryEditorViewModel>();
            builder.Services.AddTransient<RuleBuilderViewModel>();
            builder.Services.AddTransient<PreferencesViewModel>();
            builder.Services.AddTransient<ActivationPromptViewModel>();
            builder.Services.AddTransient<CategorySyncViewModel>();

            builder.Services.AddMauiBlazorWebView();

#if DEBUG
            builder.Services.AddBlazorWebViewDeveloperTools();
            builder.Logging.AddDebug();
#endif

            var app = builder.Build();

            // Initialisation de l'infrastructure
            app.Services.EnsureDatabaseCreated();

            return app;
        }
    }
}