// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-08 : Configuration du démarrage et ajout de H.NotifyIcon (J3-S1-T1).
//         - 2026-09-08 : Injection de IGlobalHotkeyService (J3-S1-T2).
//         - 2026-09-08 : Injection de QuickCategorizeViewModel, EF Core et Infrastructure (J3-S2-T1).
//         - 2026-09-08 : Injection de QuickRuleBuilderViewModel et d'un DummySelectionProvider (J3-S2-T2).
//         - 2026-09-09 : Injection de IRuleRepository et ClassificationEngine (J3-S2-T2-ST2).
//         - 2026-09-09 : Injection de ShadowModeDashboardViewModel et IShadowModeService (J3-S3-T1).
//         - 2026-09-09 : Refactoring de l'initialisation et extraction des Dummies (J3-S3-T0).
//         - 2026-09-09 : Injection de CategoryTreeViewModel (J3-S3-T2 - Phase Bleue).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.IO;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.Maui.Storage;
using H.NotifyIcon;
using Catamailer.Domain;
using Catamailer.Infrastructure;
using Catamailer.Application;
using Catamailer.Application.ViewModels;
using Catamailer.UI.Dummies;
using Microsoft.Extensions.DependencyInjection;

namespace Catamailer.UI
{
    /// <summary>
    /// Classe statique responsable de l'amorçage et de la configuration de l'application MAUI Blazor.
    /// </summary>
    public static class MauiProgram
    {
        /// <summary>
        /// Crée et configure l'instance principale de l'application MAUI.
        /// Injecte les dépendances Blazor et initialise le composant de zone de notification (Tray Icon).
        /// </summary>
        /// <returns>Une instance configurée de <see cref="MauiApp"/>.</returns>
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .UseNotifyIcon() // Enregistrement du composant Tray Icon
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                });

            // Configuration de la base de données SQLite dans le dossier local de l'application
            string dbPath = Path.Combine(FileSystem.AppDataDirectory, "catamailer.db");
            builder.Services.AddDbContext<CatamailerDbContext>(options =>
                options.UseSqlite($"Data Source={dbPath}"));

            // Injection des services de domaine et d'application
            builder.Services.AddTransient<ClassificationEngine>();
            builder.Services.AddScoped<IShadowModeService, ShadowModeService>();

            // Injection des services d'infrastructure
            builder.Services.AddScoped<ICategoryRepository, CategoryRepository>();
            builder.Services.AddScoped<IAppSettingsRepository, AppSettingsRepository>();
            builder.Services.AddScoped<IHistoryStateRepository, HistoryStateRepository>();
            builder.Services.AddSingleton<IGlobalHotkeyService, Win32GlobalHotkeyService>();
            
            // Faux fournisseurs pour le test de l'IHM (TODO: À remplacer en production)
            builder.Services.AddScoped<IRuleRepository, DummyRuleRepository>();
            builder.Services.AddScoped<ISelectionProvider, DummySelectionProvider>();
            
            // Injection des ViewModels (Transient pour réinitialiser l'état à chaque appel)
            builder.Services.AddTransient<QuickCategorizeViewModel>();
            builder.Services.AddTransient<QuickRuleBuilderViewModel>();
            builder.Services.AddTransient<ShadowModeDashboardViewModel>();
            builder.Services.AddTransient<CategoryTreeViewModel>();

            builder.Services.AddMauiBlazorWebView();

#if DEBUG
            builder.Services.AddBlazorWebViewDeveloperTools();
            builder.Logging.AddDebug();
#endif

            var app = builder.Build();

            // Initialisation de l'infrastructure
            app.Services.EnsureDatabaseCreated();
            
            // Amorçage des données factices pour le développement
            app.Services.SeedDummyCategories();

            return app;
        }
    }
}