// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale de ActivationPromptViewModel (J3-S3-T5 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.Application.ViewModels
{
    /// <summary>
    /// ViewModel gérant l'affichage et les actions de la notification d'activation du Shadow Mode.
    /// </summary>
    public class ActivationPromptViewModel
    {
        private readonly IShadowModeService _shadowModeService;

        /// <summary>
        /// Indique si la popup d'activation doit être affichée à l'utilisateur.
        /// </summary>
        public bool ShouldShowPrompt { get; private set; }

        /// <summary>
        /// Initialise une nouvelle instance de la classe <see cref="ActivationPromptViewModel"/>.
        /// </summary>
        /// <param name="shadowModeService">Le service gérant le Shadow Mode.</param>
        public ActivationPromptViewModel(IShadowModeService shadowModeService)
        {
            _shadowModeService = shadowModeService;
        }

        /// <summary>
        /// Initialise le ViewModel en vérifiant si le palier de télémétrie nécessite une notification.
        /// </summary>
        public async Task InitializeAsync()
        {
            ShouldShowPrompt = await _shadowModeService.ShouldPromptForActivationAsync();
        }

        /// <summary>
        /// Active l'écriture automatique et masque la notification.
        /// </summary>
        public async Task ActivateAsync()
        {
            await _shadowModeService.SetAutoWriteEnabledAsync(true);
            ShouldShowPrompt = false;
        }

        /// <summary>
        /// Acquitte la notification pour le palier courant et la masque.
        /// </summary>
        public async Task AcknowledgeAsync()
        {
            await _shadowModeService.AcknowledgeActivationPromptAsync();
            ShouldShowPrompt = false;
        }
    }
}