// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-09
//     Historique :
//         - 2026-09-09 : Création initiale pour J3-S3-T2 (Phase Verte).
//         - 2026-09-09 : Correction de la propriété Parent (J3-S3-T2).
//         - 2026-09-22 : Ajout de la méthode DeleteCategoryAsync pour la suppression logique (J4-S4-T6 - Phase Bleue).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.Application.ViewModels
{
    /// <summary>
    /// ViewModel responsable de la gestion et de l'affichage de l'arborescence des catégories.
    /// </summary>
    public class CategoryTreeViewModel
    {
        private readonly ICategoryRepository _categoryRepository;

        /// <summary>
        /// Obtient la liste des catégories de niveau racine (n'ayant aucun parent).
        /// </summary>
        public IReadOnlyList<CategoryNode> RootCategories { get; private set; } = new List<CategoryNode>();

        /// <summary>
        /// Initialise une nouvelle instance de <see cref="CategoryTreeViewModel"/>.
        /// </summary>
        /// <param name="categoryRepository">Le dépôt permettant d'accéder aux catégories.</param>
        public CategoryTreeViewModel(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        /// <summary>
        /// Charge l'ensemble des catégories depuis le dépôt et construit la liste des nœuds racines.
        /// </summary>
        public async Task InitializeAsync()
        {
            var allCategories = await _categoryRepository.GetAllAsync();
            
            // On ne conserve que les catégories qui n'ont pas de parent pour affichage en racine
            RootCategories = allCategories
                .Where(c => c.Parent == null)
                .OrderBy(c => c.Name)
                .ToList();
        }

        /// <summary>
        /// Marque la catégorie comme supprimée logiquement, met à jour le dépôt et rafraîchit l'arbre.
        /// </summary>
        /// <param name="node">Le nœud de catégorie à supprimer.</param>
        public async Task DeleteCategoryAsync(CategoryNode node)
        {
            node.MarkAsDeleted();
            await _categoryRepository.UpdateAsync(node);
            await InitializeAsync();
        }
    }
}