#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale du CategorySyncViewModel (J4-S2-T1).
//         - 2026-09-16 : Refonte pour gérer l'affichage hiérarchique, le séparateur dynamique et les tris/sélections (J4-S4-T2).
//         - 2026-09-17 : Refonte ApplyResolutionsAsync pour reconstruire l'arbre avant l'import SQLite (J4-S4-T4).
//         - 2026-09-17 : Gestion de la direction de résolution des conflits de couleur (J4-S4-T4).
//         - 2026-09-17 : Ajout de la mécanique de Healing pour récupérer et ré-attacher les nœuds orphelins existants (J4-S4-T4 - Phase Bleue).
//         - 2026-09-17 : Inclusion des ColorMismatch pour maintenir la continuité visuelle de l'arbre (J4-S4-T5 - Phase Bleue).
//         - 2026-09-17 : Direction par défaut "Écraser Outlook" si Outlook n'a pas de couleur et Catamailer en a une (J4-S4-T5 - Phase Bleue).
//         - 2026-09-17 : Ajout de traces Stopwatch et optimisation O(1) de la boucle IsFolder (Refacto Perf).
//         - 2026-09-23 : Remplacement de Debug.WriteLine par Console.WriteLine pour diagnostic terminal (J4-S4-T7 - Phase Jaune).
//         - 2026-09-23 : Optimisation des performances via l'utilisation des opérations de lots (AddRangeAsync, UpdateRangeAsync) (J4-S4-T7 - Phase Orange).
//         - 2026-09-23 : Ajout de traces Stopwatch unitaires pour mesurer le bottleneck RPC COM (J4-S4-T7).
//         - 2026-09-23 : Ajout de la liste DeletedInCatamailerOptions et résolution bidirectionnelle (J4-S4-T6 - Phase Bleue).
//         - 2026-09-24 : Nettoyage des traces de performance pour respecter le silence sur succès (J5-S2-T2 - Phase Orange).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Application.Services;
using Catamailer.Domain;
using Catamailer.Domain.Sync;

namespace Catamailer.Application.ViewModels
{
    public class CategorySyncViewModel
    {
        private readonly ICategorySyncService _syncService;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ICategoryManagerProvider _outlookProvider;

        public string Separator { get; set; } = "-";
        public bool HasConflicts { get; private set; }

        public List<SyncDeltaOption> MissingInCatamailerOptions { get; private set; } = new();
        public List<SyncDeltaOption> MissingInOutlookOptions { get; private set; } = new();
        public List<SyncDeltaOption> ColorMismatchOptions { get; private set; } = new();
        public List<SyncDeltaOption> DeletedInCatamailerOptions { get; private set; } = new();

        public bool SelectAllMissingInCatamailer
        {
            get => MissingInCatamailerOptions.Any() && MissingInCatamailerOptions.All(o => o.IsSelected);
            set { foreach (var o in MissingInCatamailerOptions) { if (o.Delta.Status == DeltaStatus.MissingInCatamailer) o.IsSelected = value; } }
        }

        public bool SelectAllMissingInOutlook
        {
            get => MissingInOutlookOptions.Any() && MissingInOutlookOptions.All(o => o.IsSelected);
            set { foreach (var o in MissingInOutlookOptions) o.IsSelected = value; }
        }

        public bool SelectAllColorMismatch
        {
            get => ColorMismatchOptions.Any() && ColorMismatchOptions.All(o => o.IsSelected);
            set { foreach (var o in ColorMismatchOptions) o.IsSelected = value; }
        }
        
        public bool SelectAllDeletedInCatamailer
        {
            get => DeletedInCatamailerOptions.Any() && DeletedInCatamailerOptions.All(o => o.IsSelected);
            set { foreach (var o in DeletedInCatamailerOptions) o.IsSelected = value; }
        }

        public CategorySyncViewModel(
            ICategorySyncService syncService,
            ICategoryRepository categoryRepository,
            ICategoryManagerProvider outlookProvider)
        {
            _syncService = syncService;
            _categoryRepository = categoryRepository;
            _outlookProvider = outlookProvider;
        }

        public async Task InitializeAsync()
        {
            var syncResult = await _syncService.AnalyzeSyncDeltasAsync(Separator);
            HasConflicts = syncResult.HasConflicts;

            var combinedCatamailerList = syncResult.Deltas
                .Where(d => d.Status == DeltaStatus.MissingInCatamailer || 
                            d.Status == DeltaStatus.Synchronized || 
                            d.Status == DeltaStatus.ColorMismatch)
                .OrderBy(d => d.CategoryName, StringComparer.OrdinalIgnoreCase)
                .Select(d => new SyncDeltaOption(d, Separator)
                {
                    IsSelected = d.Status == DeltaStatus.MissingInCatamailer
                })
                .ToList();

            MissingInCatamailerOptions = combinedCatamailerList;

            var parentPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var opt in MissingInCatamailerOptions)
            {
                int lastSep = opt.Delta.CategoryName.LastIndexOf(Separator);
                if (lastSep >= 0)
                {
                    parentPaths.Add(opt.Delta.CategoryName.Substring(0, lastSep).Trim());
                }
            }

            foreach (var opt in MissingInCatamailerOptions)
            {
                opt.IsFolder = parentPaths.Contains(opt.Delta.CategoryName);
            }

            MissingInOutlookOptions = syncResult.GetMissingInOutlook()
                .OrderBy(d => d.CategoryName, StringComparer.OrdinalIgnoreCase)
                .Select(d => new SyncDeltaOption(d, Separator))
                .ToList();

            ColorMismatchOptions = syncResult.GetColorConflicts()
                .OrderBy(d => d.CategoryName, StringComparer.OrdinalIgnoreCase)
                .Select(d => new SyncDeltaOption(d, Separator)
                {
                    Direction = (string.IsNullOrEmpty(d.OutlookColor) && !string.IsNullOrEmpty(d.CatamailerColor)) 
                        ? SyncResolutionDirection.CatamailerToOutlook 
                        : SyncResolutionDirection.OutlookToCatamailer
                })
                .ToList();
                
            DeletedInCatamailerOptions = syncResult.GetDeletedInCatamailer()
                .OrderBy(d => d.CategoryName, StringComparer.OrdinalIgnoreCase)
                .Select(d => new SyncDeltaOption(d, Separator)
                {
                    IsSelected = false // Non sélectionné par défaut comme demandé
                })
                .ToList();
        }

        public async Task ApplyResolutionsAsync()
        {
            var existingNodes = (await _categoryRepository.GetAllAsync(includeDeleted: true) ?? Enumerable.Empty<CategoryNode>()).ToList();
            var existingMapByFullName = existingNodes.ToDictionary(
                n => n.GetFullName(Separator), 
                n => n, 
                StringComparer.OrdinalIgnoreCase);

            var selectedToCatamailer = MissingInCatamailerOptions
                .Where(o => o.IsSelected && o.Delta.Status == DeltaStatus.MissingInCatamailer)
                .OrderBy(o => o.Depth)
                .ToList();

            var nodesToAdd = new List<CategoryNode>();
            var nodesToUpdate = new HashSet<CategoryNode>();

            foreach (var option in selectedToCatamailer)
            {
                var targetNode = existingNodes.FirstOrDefault(n => string.Equals(n.Name, option.ShortName, StringComparison.OrdinalIgnoreCase));
                bool isNew = false;

                if (targetNode == null)
                {
                    targetNode = new CategoryNode(option.ShortName, option.Delta.OptimizedColor);
                    isNew = true;
                    existingNodes.Add(targetNode);
                }
                else
                {
                    targetNode.UpdateColor(option.Delta.OptimizedColor);
                    nodesToUpdate.Add(targetNode);
                }

                existingMapByFullName[option.Delta.CategoryName] = targetNode;

                if (option.Depth > 0)
                {
                    int lastSep = option.Delta.CategoryName.LastIndexOf(Separator);
                    if (lastSep >= 0)
                    {
                        string parentFullName = option.Delta.CategoryName.Substring(0, lastSep).Trim();
                        
                        if (existingMapByFullName.TryGetValue(parentFullName, out var parentNode))
                        {
                            if (targetNode.Parent != parentNode)
                            {
                                parentNode.AddChild(targetNode);
                                nodesToUpdate.Add(parentNode);
                            }
                        }
                    }
                }

                if (isNew && targetNode.Parent == null)
                {
                    nodesToAdd.Add(targetNode);
                }
                else if (!isNew)
                {
                    nodesToUpdate.Add(targetNode);
                }
            }

            if (nodesToAdd.Any())
            {
                await _categoryRepository.AddRangeAsync(nodesToAdd);
            }

            if (nodesToUpdate.Any())
            {
                await _categoryRepository.UpdateRangeAsync(nodesToUpdate);
            }

            foreach (var option in MissingInOutlookOptions.Where(o => o.IsSelected))
            {
                _outlookProvider.AddCategory(option.Delta.CategoryName, option.Delta.CatamailerColor ?? "");
            }

            var colorNodesToAdd = new List<CategoryNode>();
            var colorNodesToUpdate = new HashSet<CategoryNode>();

            foreach (var option in ColorMismatchOptions.Where(o => o.IsSelected))
            {
                if (option.Direction == SyncResolutionDirection.CatamailerToOutlook)
                {
                    _outlookProvider.UpdateCategoryColor(option.Delta.CategoryName, option.Delta.CatamailerColor ?? "");
                }
                else
                {
                    var dbNode = existingNodes.FirstOrDefault(n => string.Equals(n.Name, option.ShortName, StringComparison.OrdinalIgnoreCase));
                    
                    if (dbNode == null)
                    {
                        dbNode = new CategoryNode(option.ShortName, option.Delta.OutlookColor);
                        existingNodes.Add(dbNode);
                        colorNodesToAdd.Add(dbNode);
                    }
                    else
                    {
                        dbNode.UpdateColor(option.Delta.OutlookColor);
                        colorNodesToUpdate.Add(dbNode);
                    }
                }
            }

            // --- Résolution des suppressions logiques ---
            var deletedNodesToRestore = new HashSet<CategoryNode>();
            
            foreach (var option in DeletedInCatamailerOptions.Where(o => o.IsSelected))
            {
                if (option.Direction == SyncResolutionDirection.CatamailerToOutlook)
                {
                    // L'utilisateur donne raison à Catamailer : on supprime physiquement dans Outlook
                    _outlookProvider.RemoveCategory(option.Delta.CategoryName);
                }
                else
                {
                    // L'utilisateur donne raison à Outlook : on restaure la catégorie dans Catamailer
                    if (existingMapByFullName.TryGetValue(option.Delta.CategoryName, out var deletedNode))
                    {
                        deletedNode.Restore(); // Passe IsDeleted à false
                        deletedNodesToRestore.Add(deletedNode);
                    }
                }
            }

            if (colorNodesToAdd.Any())
            {
                await _categoryRepository.AddRangeAsync(colorNodesToAdd);
            }

            if (colorNodesToUpdate.Any() || deletedNodesToRestore.Any())
            {
                var combinedUpdates = colorNodesToUpdate.Union(deletedNodesToRestore).ToList();
                await _categoryRepository.UpdateRangeAsync(combinedUpdates);
            }
        }
        
        public async Task RefreshAsync()
        {
            await InitializeAsync();
        }
    }
}