#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale du CategorySyncViewModel (J4-S2-T1).
//         - 2026-09-16 : Refonte pour gérer l'affichage hiérarchique, le séparateur dynamique et les tris/sélections (J4-S4-T2).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Application.Services;
using Catamailer.Domain;

namespace Catamailer.Application.ViewModels
{
    public class CategorySyncViewModel
    {
        private readonly ICategorySyncService _syncService;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ICategoryManagerProvider _outlookProvider;

        public string Separator { get; set; } = "-";
        public bool HasConflicts { get; private set; }

        public List<SyncDeltaOption> MissingInCatamailerOptions { get; private set; } = new();
        public List<SyncDeltaOption> MissingInOutlookOptions { get; private set; } = new();
        public List<SyncDeltaOption> ColorMismatchOptions { get; private set; } = new();

        // Propriétés bidirectionnelles pour les cases "Tout cocher"
        public bool SelectAllMissingInCatamailer
        {
            get => MissingInCatamailerOptions.Any() && MissingInCatamailerOptions.All(o => o.IsSelected);
            set { foreach (var o in MissingInCatamailerOptions) o.IsSelected = value; }
        }

        public bool SelectAllMissingInOutlook
        {
            get => MissingInOutlookOptions.Any() && MissingInOutlookOptions.All(o => o.IsSelected);
            set { foreach (var o in MissingInOutlookOptions) o.IsSelected = value; }
        }

        public bool SelectAllColorMismatch
        {
            get => ColorMismatchOptions.Any() && ColorMismatchOptions.All(o => o.IsSelected);
            set { foreach (var o in ColorMismatchOptions) o.IsSelected = value; }
        }

        public CategorySyncViewModel(
            ICategorySyncService syncService,
            ICategoryRepository categoryRepository,
            ICategoryManagerProvider outlookProvider)
        {
            _syncService = syncService;
            _categoryRepository = categoryRepository;
            _outlookProvider = outlookProvider;
        }

        public async Task InitializeAsync()
        {
            var syncResult = await _syncService.AnalyzeSyncDeltasAsync(Separator);
            HasConflicts = syncResult.HasConflicts;

            MissingInCatamailerOptions = syncResult.GetMissingInCatamailer()
                .OrderBy(d => d.CategoryName, StringComparer.OrdinalIgnoreCase)
                .Select(d => new SyncDeltaOption(d, Separator))
                .ToList();

            // Calcul de la nature du nœud (Dossier ou Feuille) pour l'icône UI
            foreach (var opt in MissingInCatamailerOptions)
            {
                string prefix = opt.Delta.CategoryName + Separator;
                opt.IsFolder = MissingInCatamailerOptions.Any(o => o.Delta.CategoryName.StartsWith(prefix));
            }

            MissingInOutlookOptions = syncResult.GetMissingInOutlook()
                .OrderBy(d => d.CategoryName, StringComparer.OrdinalIgnoreCase)
                .Select(d => new SyncDeltaOption(d, Separator))
                .ToList();

            ColorMismatchOptions = syncResult.GetColorConflicts()
                .OrderBy(d => d.CategoryName, StringComparer.OrdinalIgnoreCase)
                .Select(d => new SyncDeltaOption(d, Separator))
                .ToList();
        }

        public async Task ApplyResolutionsAsync()
        {
            // 1. Ajouter à Catamailer avec la couleur OPTIMISÉE (pour respecter l'héritage)
            foreach (var option in MissingInCatamailerOptions.Where(o => o.IsSelected))
            {
                var newNode = new CategoryNode(option.Delta.CategoryName, option.Delta.OptimizedColor);
                await _categoryRepository.AddAsync(newNode);
            }

            // 2. Ajouter à Outlook les catégories manquantes
            foreach (var option in MissingInOutlookOptions.Where(o => o.IsSelected))
            {
                _outlookProvider.AddCategory(option.Delta.CategoryName, option.Delta.CatamailerColor ?? "");
            }

            // 3. Pousser la couleur Catamailer vers Outlook
            foreach (var option in ColorMismatchOptions.Where(o => o.IsSelected))
            {
                _outlookProvider.UpdateCategoryColor(option.Delta.CategoryName, option.Delta.CatamailerColor ?? "");
            }
        }
        
        public async Task RefreshAsync()
        {
            await InitializeAsync();
        }
    }
}