// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-11
//     Historique :
//         - 2026-09-11 : Création initiale (J3-S3-T3-ST1 - Phase Verte).
//         - 2026-09-11 : Ajout du formulaire de création et injection de ICategoryRepository (Phase Verte).
//         - 2026-09-11 : Ajout des champs Expéditeur et Destinataire (Phase Orange/Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.Application.ViewModels
{
    /// <summary>
    /// ViewModel responsable de la gestion (CRUD) des règles de dictionnaires (Étape 1).
    /// </summary>
    public class DictionaryEditorViewModel
    {
        private readonly IRuleRepository _ruleRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ObservableCollection<DictionaryRule> _rules = new();
        private readonly ObservableCollection<CategoryNode> _availableCategories = new();

        /// <summary>
        /// Obtient la liste observable des règles de dictionnaire.
        /// </summary>
        public IEnumerable<DictionaryRule> Rules => _rules;

        /// <summary>
        /// Obtient la liste des catégories disponibles pour la création d'une règle.
        /// </summary>
        public IEnumerable<CategoryNode> AvailableCategories => _availableCategories;

        /// <summary>
        /// Obtient ou définit la catégorie sélectionnée dans le formulaire.
        /// </summary>
        public CategoryNode? SelectedCategory { get; set; }

        /// <summary>
        /// Obtient ou définit les mots-clés du sujet saisis dans le formulaire (séparés par des virgules).
        /// </summary>
        public string SubjectKeywordsInput { get; set; } = string.Empty;

        /// <summary>
        /// Obtient ou définit les mots-clés de l'expéditeur saisis dans le formulaire (séparés par des virgules).
        /// </summary>
        public string SenderKeywordsInput { get; set; } = string.Empty;

        /// <summary>
        /// Obtient ou définit les mots-clés du destinataire saisis dans le formulaire (séparés par des virgules).
        /// </summary>
        public string RecipientKeywordsInput { get; set; } = string.Empty;

        /// <summary>
        /// Initialise une nouvelle instance de <see cref="DictionaryEditorViewModel"/>.
        /// </summary>
        /// <param name="ruleRepository">Le dépôt des règles.</param>
        /// <param name="categoryRepository">Le dépôt des catégories.</param>
        public DictionaryEditorViewModel(IRuleRepository ruleRepository, ICategoryRepository categoryRepository)
        {
            _ruleRepository = ruleRepository;
            _categoryRepository = categoryRepository;
        }

        /// <summary>
        /// Charge l'ensemble des règles de dictionnaire et des catégories depuis les dépôts.
        /// </summary>
        public async Task InitializeAsync()
        {
            var rules = await _ruleRepository.GetAllDictionaryRulesAsync();
            _rules.Clear();
            foreach (var rule in rules)
            {
                _rules.Add(rule);
            }

            var categories = await _categoryRepository.GetAllAsync();
            _availableCategories.Clear();
            foreach (var cat in categories)
            {
                _availableCategories.Add(cat);
            }
        }

        /// <summary>
        /// Ajoute une nouvelle règle au dépôt et met à jour la liste en mémoire.
        /// </summary>
        /// <param name="rule">La règle à ajouter.</param>
        public async Task AddRuleAsync(DictionaryRule rule)
        {
            await _ruleRepository.AddDictionaryRuleAsync(rule);
            _rules.Add(rule);
        }

        /// <summary>
        /// Supprime une règle du dépôt et met à jour la liste en mémoire.
        /// </summary>
        /// <param name="rule">La règle à supprimer.</param>
        public async Task DeleteRuleAsync(DictionaryRule rule)
        {
            await _ruleRepository.DeleteDictionaryRuleAsync(rule);
            _rules.Remove(rule);
        }

        /// <summary>
        /// Crée une nouvelle règle à partir des données saisies dans le formulaire.
        /// </summary>
        public async Task CreateRuleFromFormAsync()
        {
            if (SelectedCategory == null) return;

            var subjectKeywords = SubjectKeywordsInput
                .Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(k => k.Trim())
                .Where(k => !string.IsNullOrEmpty(k))
                .ToArray();

            var senderKeywords = SenderKeywordsInput
                .Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(k => k.Trim())
                .Where(k => !string.IsNullOrEmpty(k))
                .ToArray();

            var recipientKeywords = RecipientKeywordsInput
                .Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(k => k.Trim())
                .Where(k => !string.IsNullOrEmpty(k))
                .ToArray();

            var newRule = new DictionaryRule(SelectedCategory, subjectKeywords, senderKeywords, recipientKeywords);
            
            await AddRuleAsync(newRule);

            SelectedCategory = null;
            SubjectKeywordsInput = string.Empty;
            SenderKeywordsInput = string.Empty;
            RecipientKeywordsInput = string.Empty;
        }
    }
}