// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale de PreferencesViewModel (J3-S3-T4 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.Application.ViewModels
{
    /// <summary>
    /// ViewModel gérant l'écran des préférences globales de l'application.
    /// </summary>
    public class PreferencesViewModel
    {
        private const string DebounceDelayKey = "HistoryDebounceDelayMinutes";
        private readonly IAppSettingsRepository _appSettingsRepository;

        /// <summary>
        /// Obtient ou définit le délai (en minutes) avant la reprise de l'historique suite à une modification.
        /// </summary>
        public int DebounceDelayMinutes { get; set; } = 30;

        /// <summary>
        /// Initialise une nouvelle instance de la classe <see cref="PreferencesViewModel"/>.
        /// </summary>
        /// <param name="appSettingsRepository">Le dépôt des paramètres d'application.</param>
        public PreferencesViewModel(IAppSettingsRepository appSettingsRepository)
        {
            _appSettingsRepository = appSettingsRepository;
        }

        /// <summary>
        /// Charge les paramètres depuis la base de données.
        /// </summary>
        public async Task InitializeAsync()
        {
            var delayString = await _appSettingsRepository.GetSettingAsync(DebounceDelayKey);
            if (int.TryParse(delayString, out var delay))
            {
                DebounceDelayMinutes = delay;
            }
            else
            {
                // Valeur métier par défaut
                DebounceDelayMinutes = 30;
            }
        }

        /// <summary>
        /// Sauvegarde les paramètres modifiés dans la base de données.
        /// </summary>
        public async Task SaveAsync()
        {
            await _appSettingsRepository.SetSettingAsync(DebounceDelayKey, DebounceDelayMinutes.ToString());
        }
    }
}