// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-11
//     Historique :
//         - 2026-09-11 : Création initiale (J3-S3-T3-ST2).
//         - 2026-09-11 : Ajout des méthodes de mutation et sauvegarde (J3-S3-T3-ST2).
//         - 2026-09-11 : Ajout du flattening pour l'affichage hiérarchique UI (J3-S3-T3-ST2 - Phase Verte).
//         - 2026-09-23 : Ajout de la gestion d'état des actions complexes (J5-S1-T2 - Phase Verte).
//         - 2026-09-24 : Remplacement de l'action unique par une ObservableCollection d'actions (J5-S3-T1 - Phase Verte).
//         - 2026-09-24 : Ajout de IExternalResourceProvider (J6-S1-T1 - Phase Rouge).
//         - 2026-09-24 : Peuplement des listes de dossiers et signatures (J6-S1-T1 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.Application.ViewModels
{
    /// <summary>
    /// Représente une option de catégorie aplatie et formatée pour l'IHM.
    /// </summary>
    public record CategoryOption(CategoryNode Node, string FullName, string DisplayName);

    /// <summary>
    /// ViewModel responsable de la création visuelle des règles d'exécution (Étape 2).
    /// </summary>
    public class RuleBuilderViewModel
    {
        private readonly IRuleRepository _ruleRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IExternalResourceProvider _externalResourceProvider;

        /// <summary>
        /// Obtient ou définit le nom descriptif de la règle à sauvegarder.
        /// </summary>
        public string RuleName { get; set; } = string.Empty;

        /// <summary>
        /// Obtient le nœud racine de l'arbre des conditions.
        /// </summary>
        public RuleNode RootNode { get; }

        /// <summary>
        /// Obtient la liste observable des actions séquentielles à exécuter.
        /// </summary>
        public ObservableCollection<RuleAction> Actions { get; } = new ObservableCollection<RuleAction>();

        /// <summary>
        /// Obtient la liste brute des catégories disponibles.
        /// </summary>
        public IEnumerable<CategoryNode> AvailableCategories { get; private set; } = Enumerable.Empty<CategoryNode>();

        /// <summary>
        /// Obtient la liste aplatie et indentée des catégories prête pour l'affichage UI.
        /// </summary>
        public IEnumerable<CategoryOption> FlatCategories { get; private set; } = Enumerable.Empty<CategoryOption>();

        /// <summary>
        /// Obtient la liste des chemins de dossiers Outlook disponibles.
        /// </summary>
        public IEnumerable<string> AvailableFolders { get; private set; } = Enumerable.Empty<string>();

        /// <summary>
        /// Obtient la liste des signatures HTML disponibles.
        /// </summary>
        public IEnumerable<string> AvailableSignatures { get; private set; } = Enumerable.Empty<string>();

        /// <summary>
        /// Initialise une nouvelle instance de <see cref="RuleBuilderViewModel"/>.
        /// </summary>
        /// <param name="ruleRepository">Le dépôt pour sauvegarder les règles.</param>
        /// <param name="categoryRepository">Le dépôt pour récupérer les catégories de référence.</param>
        /// <param name="externalResourceProvider">Le fournisseur des ressources externes (dossiers, signatures).</param>
        public RuleBuilderViewModel(
            IRuleRepository ruleRepository, 
            ICategoryRepository categoryRepository,
            IExternalResourceProvider externalResourceProvider)
        {
            _ruleRepository = ruleRepository;
            _categoryRepository = categoryRepository;
            _externalResourceProvider = externalResourceProvider;
            RootNode = new RuleNode(LogicalOperator.And);
        }

        /// <summary>
        /// Charge les données de référence nécessaires à l'IHM (catégories et ressources externes) et construit l'arborescence visuelle.
        /// </summary>
        public async Task InitializeAsync()
        {
            var categoriesTask = _categoryRepository.GetAllAsync();
            var foldersTask = _externalResourceProvider.GetAvailableFolderPathsAsync();
            var signaturesTask = _externalResourceProvider.GetAvailableSignaturesAsync();

            await Task.WhenAll(categoriesTask, foldersTask, signaturesTask);

            AvailableCategories = categoriesTask.Result.ToList();
            AvailableFolders = foldersTask.Result.OrderBy(f => f).ToList();
            AvailableSignatures = signaturesTask.Result.OrderBy(s => s).ToList();

            var flatList = new List<CategoryOption>();
            var rootNodes = AvailableCategories.Where(c => c.Parent == null).OrderBy(c => c.Name);

            void Traverse(CategoryNode node)
            {
                var indent = new string('\u00A0', node.Depth * 4); // 4 espaces insécables par niveau de profondeur
                var fullName = node.GetFullName("-"); // Génération avec tiret sans espaces autour
                
                flatList.Add(new CategoryOption(node, fullName, $"{indent}{node.Name}"));

                foreach (var child in node.Children.OrderBy(c => c.Name))
                {
                    Traverse(child);
                }
            }

            foreach (var root in rootNodes)
            {
                Traverse(root);
            }

            FlatCategories = flatList;
        }

        /// <summary>
        /// Modifie l'opérateur logique d'un nœud spécifique.
        /// </summary>
        /// <param name="targetNode">Le nœud cible.</param>
        /// <param name="newOperator">Le nouvel opérateur logique.</param>
        public void SetOperator(RuleNode targetNode, LogicalOperator newOperator)
        {
            targetNode.SetOperator(newOperator);
        }

        /// <summary>
        /// Ajoute un critère à un nœud spécifique.
        /// </summary>
        /// <param name="targetNode">Le nœud cible.</param>
        /// <param name="criterion">Le critère à ajouter.</param>
        public void AddCriterion(RuleNode targetNode, RuleCriterion criterion)
        {
            targetNode.AddCriterion(criterion);
        }

        /// <summary>
        /// Met à jour un critère existant dans un nœud spécifique.
        /// </summary>
        /// <param name="targetNode">Le nœud parent du critère.</param>
        /// <param name="oldCriterion">L'ancien critère à remplacer.</param>
        /// <param name="newCriterion">Le nouveau critère.</param>
        public void UpdateCriterion(RuleNode targetNode, RuleCriterion oldCriterion, RuleCriterion newCriterion)
        {
            targetNode.UpdateCriterion(oldCriterion, newCriterion);
        }

        /// <summary>
        /// Supprime un critère d'un nœud spécifique.
        /// </summary>
        /// <param name="targetNode">Le nœud cible.</param>
        /// <param name="criterion">Le critère à supprimer.</param>
        public void RemoveCriterion(RuleNode targetNode, RuleCriterion criterion)
        {
            targetNode.RemoveCriterion(criterion);
        }

        /// <summary>
        /// Ajoute un sous-nœud à un nœud spécifique.
        /// </summary>
        /// <param name="targetNode">Le nœud parent cible.</param>
        /// <param name="childNode">Le nœud enfant à ajouter.</param>
        public void AddChildNode(RuleNode targetNode, RuleNode childNode)
        {
            targetNode.AddChildNode(childNode);
        }

        /// <summary>
        /// Ajoute une nouvelle action à la fin de la liste d'exécution.
        /// </summary>
        /// <param name="action">L'action à ajouter.</param>
        public void AddAction(RuleAction action)
        {
            Actions.Add(action);
        }

        /// <summary>
        /// Met à jour une action existante dans la liste.
        /// </summary>
        /// <param name="oldAction">L'ancienne action.</param>
        /// <param name="newAction">La nouvelle action.</param>
        public void UpdateAction(RuleAction oldAction, RuleAction newAction)
        {
            int index = Actions.IndexOf(oldAction);
            if (index >= 0)
            {
                Actions[index] = newAction;
            }
        }

        /// <summary>
        /// Supprime une action de la liste d'exécution.
        /// </summary>
        /// <param name="action">L'action à supprimer.</param>
        public void RemoveAction(RuleAction action)
        {
            Actions.Remove(action);
        }

        /// <summary>
        /// Réinitialise complètement la liste des actions.
        /// Utilisé principalement pour la rétrocompatibilité ou le ré-amorçage.
        /// </summary>
        /// <param name="action">L'action unique de remplacement.</param>
        public void SetAction(RuleAction action)
        {
            Actions.Clear();
            Actions.Add(action);
        }

        /// <summary>
        /// Sauvegarde la règle en base de données si elle est correctement configurée.
        /// </summary>
        public async Task SaveRuleAsync()
        {
            if (string.IsNullOrWhiteSpace(RuleName) || !Actions.Any())
            {
                return;
            }

            var executionRule = new ExecutionRule(RuleName, RootNode, Actions.ToList());
            await _ruleRepository.AddExecutionRuleAsync(executionRule);
        }
    }
}