// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-11
//     Historique :
//         - 2026-09-11 : Création initiale (J3-S3-T3-ST2).
//         - 2026-09-11 : Ajout des méthodes de mutation et sauvegarde (J3-S3-T3-ST2).
//         - 2026-09-11 : Ajout du flattening pour l'affichage hiérarchique UI (J3-S3-T3-ST2 - Phase Verte).
//         - 2026-09-23 : Ajout de la gestion d'état des actions complexes (J5-S1-T2 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.Application.ViewModels
{
    /// <summary>
    /// Représente une option de catégorie aplatie et formatée pour l'IHM.
    /// </summary>
    public record CategoryOption(CategoryNode Node, string FullName, string DisplayName);

    /// <summary>
    /// ViewModel responsable de la création visuelle des règles d'exécution (Étape 2).
    /// </summary>
    public class RuleBuilderViewModel
    {
        private readonly IRuleRepository _ruleRepository;
        private readonly ICategoryRepository _categoryRepository;
        private ActionType? _selectedActionType;

        /// <summary>
        /// Obtient ou définit le nom descriptif de la règle à sauvegarder.
        /// </summary>
        public string RuleName { get; set; } = string.Empty;

        /// <summary>
        /// Obtient le nœud racine de l'arbre des conditions.
        /// </summary>
        public RuleNode RootNode { get; }

        /// <summary>
        /// Obtient ou définit le type d'action sélectionné, en appliquant les règles de réinitialisation des paramètres.
        /// </summary>
        public ActionType? SelectedActionType
        {
            get => _selectedActionType;
            set
            {
                _selectedActionType = value;
                if (_selectedActionType == ActionType.SetImportance)
                {
                    ActionParameter = "Normale";
                }
                else if (_selectedActionType == ActionType.FlagToday || _selectedActionType == ActionType.MarkAsRead)
                {
                    ActionParameter = string.Empty;
                }
            }
        }

        /// <summary>
        /// Obtient ou définit le paramètre de l'action sélectionnée.
        /// </summary>
        public string ActionParameter { get; set; } = string.Empty;

        /// <summary>
        /// Obtient l'action finale calculée en fonction des sélections en cours.
        /// </summary>
        public RuleAction? FinalAction => SelectedActionType.HasValue 
            ? new RuleAction(SelectedActionType.Value, ActionParameter) 
            : null;

        /// <summary>
        /// Obtient la liste brute des catégories disponibles.
        /// </summary>
        public IEnumerable<CategoryNode> AvailableCategories { get; private set; } = Enumerable.Empty<CategoryNode>();

        /// <summary>
        /// Obtient la liste aplatie et indentée des catégories prête pour l'affichage UI.
        /// </summary>
        public IEnumerable<CategoryOption> FlatCategories { get; private set; } = Enumerable.Empty<CategoryOption>();

        /// <summary>
        /// Initialise une nouvelle instance de <see cref="RuleBuilderViewModel"/>.
        /// </summary>
        /// <param name="ruleRepository">Le dépôt pour sauvegarder les règles.</param>
        /// <param name="categoryRepository">Le dépôt pour récupérer les catégories de référence.</param>
        public RuleBuilderViewModel(IRuleRepository ruleRepository, ICategoryRepository categoryRepository)
        {
            _ruleRepository = ruleRepository;
            _categoryRepository = categoryRepository;
            RootNode = new RuleNode(LogicalOperator.And);
        }

        /// <summary>
        /// Charge les données de référence nécessaires à l'IHM (catégories) et construit l'arborescence visuelle.
        /// </summary>
        public async Task InitializeAsync()
        {
            var categories = await _categoryRepository.GetAllAsync();
            AvailableCategories = categories.ToList();

            var flatList = new List<CategoryOption>();
            var rootNodes = AvailableCategories.Where(c => c.Parent == null).OrderBy(c => c.Name);

            void Traverse(CategoryNode node)
            {
                var indent = new string('\u00A0', node.Depth * 4); // 4 espaces insécables par niveau de profondeur
                var fullName = node.GetFullName("-"); // Génération avec tiret sans espaces autour
                
                flatList.Add(new CategoryOption(node, fullName, $"{indent}{node.Name}"));

                foreach (var child in node.Children.OrderBy(c => c.Name))
                {
                    Traverse(child);
                }
            }

            foreach (var root in rootNodes)
            {
                Traverse(root);
            }

            FlatCategories = flatList;
        }

        /// <summary>
        /// Modifie l'opérateur logique d'un nœud spécifique.
        /// </summary>
        /// <param name="targetNode">Le nœud cible.</param>
        /// <param name="newOperator">Le nouvel opérateur logique.</param>
        public void SetOperator(RuleNode targetNode, LogicalOperator newOperator)
        {
            targetNode.SetOperator(newOperator);
        }

        /// <summary>
        /// Ajoute un critère à un nœud spécifique.
        /// </summary>
        /// <param name="targetNode">Le nœud cible.</param>
        /// <param name="criterion">Le critère à ajouter.</param>
        public void AddCriterion(RuleNode targetNode, RuleCriterion criterion)
        {
            targetNode.AddCriterion(criterion);
        }

        /// <summary>
        /// Met à jour un critère existant dans un nœud spécifique.
        /// </summary>
        /// <param name="targetNode">Le nœud parent du critère.</param>
        /// <param name="oldCriterion">L'ancien critère à remplacer.</param>
        /// <param name="newCriterion">Le nouveau critère.</param>
        public void UpdateCriterion(RuleNode targetNode, RuleCriterion oldCriterion, RuleCriterion newCriterion)
        {
            targetNode.UpdateCriterion(oldCriterion, newCriterion);
        }

        /// <summary>
        /// Supprime un critère d'un nœud spécifique.
        /// </summary>
        /// <param name="targetNode">Le nœud cible.</param>
        /// <param name="criterion">Le critère à supprimer.</param>
        public void RemoveCriterion(RuleNode targetNode, RuleCriterion criterion)
        {
            targetNode.RemoveCriterion(criterion);
        }

        /// <summary>
        /// Ajoute un sous-nœud à un nœud spécifique.
        /// </summary>
        /// <param name="targetNode">Le nœud parent cible.</param>
        /// <param name="childNode">Le nœud enfant à ajouter.</param>
        public void AddChildNode(RuleNode targetNode, RuleNode childNode)
        {
            targetNode.AddChildNode(childNode);
        }

        /// <summary>
        /// Définit l'action finale de la règle.
        /// </summary>
        /// <param name="action">L'action à appliquer.</param>
        public void SetAction(RuleAction action)
        {
            SelectedActionType = action.Type;
            ActionParameter = action.Parameter;
        }

        /// <summary>
        /// Sauvegarde la règle en base de données si elle est correctement configurée.
        /// </summary>
        public async Task SaveRuleAsync()
        {
            var finalActionToSave = FinalAction;
            if (string.IsNullOrWhiteSpace(RuleName) || finalActionToSave == null)
            {
                return;
            }

            var executionRule = new ExecutionRule(RuleName, RootNode, finalActionToSave);
            await _ruleRepository.AddExecutionRuleAsync(executionRule);
        }
    }
}