// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-09
//     Historique :
//         - 2026-09-09 : Création initiale pour J3-S3-T1 (Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.Application.ViewModels
{
    /// <summary>
    /// ViewModel responsable de l'affichage et de la gestion des statistiques du Shadow Mode.
    /// </summary>
    public class ShadowModeDashboardViewModel
    {
        private readonly IShadowModeService _shadowModeService;

        /// <summary>
        /// Obtient le nombre de correspondances exactes validées par la télémétrie.
        /// </summary>
        public int MatchCount { get; private set; }

        /// <summary>
        /// Obtient le nombre de catégories distinctes validées par la télémétrie.
        /// </summary>
        public int CategoryCount { get; private set; }

        /// <summary>
        /// Obtient un indicateur précisant si l'écriture automatique est activée.
        /// </summary>
        public bool IsAutoWriteEnabled { get; private set; }

        /// <summary>
        /// Initialise une nouvelle instance de <see cref="ShadowModeDashboardViewModel"/>.
        /// </summary>
        /// <param name="shadowModeService">Le service de gestion du Shadow Mode.</param>
        public ShadowModeDashboardViewModel(IShadowModeService shadowModeService)
        {
            _shadowModeService = shadowModeService;
        }

        /// <summary>
        /// Charge les statistiques actuelles depuis le service.
        /// </summary>
        public async Task InitializeAsync()
        {
            var stats = await _shadowModeService.GetTelemetryStatsAsync();
            MatchCount = stats.MatchCount;
            CategoryCount = stats.CategoryCount;
            IsAutoWriteEnabled = stats.IsAutoWriteEnabled;
        }

        /// <summary>
        /// Active ou désactive l'écriture automatique et met à jour l'état.
        /// </summary>
        /// <param name="enabled">L'état cible de l'activation.</param>
        public async Task ToggleAutoWriteAsync(bool enabled)
        {
            await _shadowModeService.SetAutoWriteEnabledAsync(enabled);
            await InitializeAsync();
        }
    }
}