#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale (J4-S2-T1 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

using Catamailer.Domain.Sync;

namespace Catamailer.Application.ViewModels
{
    /// <summary>
    /// Enveloppe un écart de synchronisation avec un état de sélection booléen pour le binding IHM.
    /// </summary>
    public class SyncDeltaOption
    {
        /// <summary>
        /// Obtient l'écart de synchronisation sous-jacent.
        /// </summary>
        public CategoryDelta Delta { get; }

        /// <summary>
        /// Obtient ou définit une valeur indiquant si cet écart doit être résolu. Coché par défaut.
        /// </summary>
        public bool IsSelected { get; set; } = true;

        /// <summary>
        /// Initialise une nouvelle instance de <see cref="SyncDeltaOption"/>.
        /// </summary>
        /// <param name="delta">Le delta de synchronisation à encapsuler.</param>
        public SyncDeltaOption(CategoryDelta delta)
        {
            Delta = delta;
        }
    }
}