#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale (J4-S2-T1).
//         - 2026-09-16 : Ajout de la profondeur (Depth), du nom court (ShortName) et du flag IsFolder pour l'IHM (J4-S4-T2).
//         - 2026-09-16 : Ajout du Trim sur le nom court pour gérer les séparateurs avec espaces (J4-S4-T2).
//         - 2026-09-17 : Délégation de l'indicateur IsImplicit à l'entité Domain (J4-S4-T2 - Phase Bleue).
// </auto-generated>
// ------------------------------------------------------------------------------

using Catamailer.Domain.Sync;

namespace Catamailer.Application.ViewModels
{
    public class SyncDeltaOption
    {
        public CategoryDelta Delta { get; }
        public bool IsSelected { get; set; } = true;
        public int Depth { get; }
        public string ShortName { get; }
        public bool IsImplicitParent => Delta.IsImplicit;
        public bool IsFolder { get; set; }

        public SyncDeltaOption(CategoryDelta delta, string separator)
        {
            Delta = delta;
            
            string cleanSeparator = separator.Trim();

            if (string.IsNullOrEmpty(cleanSeparator))
            {
                Depth = 0;
                ShortName = delta.CategoryName.Trim();
            }
            else
            {
                var parts = delta.CategoryName.Split(new[] { cleanSeparator }, System.StringSplitOptions.None);
                Depth = parts.Length - 1;
                ShortName = parts[Depth].Trim();
            }
        }
    }
}