// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-25
//     Historique :
//         - 2026-09-25 : Création de l'interface IMigrationOrchestrator (J6-S2-T1 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;

namespace Catamailer.Migrator.Orchestration
{
    /// <summary>
    /// Définit le contrat pour l'orchestration globale du processus de migration CSV vers la base de données.
    /// </summary>
    public interface IMigrationOrchestrator
    {
        /// <summary>
        /// Exécute la chaîne complète de migration (Parsing, Mapping, Sauvegarde).
        /// </summary>
        /// <param name="csvFilePath">Le chemin absolu ou relatif vers le fichier CSV source.</param>
        Task MigrateAsync(string csvFilePath);
    }
}