// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-25
//     Historique :
//         - 2026-09-25 : Création de l'orchestrateur bouchonné pour TDD (J6-S2-T1 - Phase Rouge).
//         - 2026-09-25 : Implémentation du cycle Parse, Map, Save (J6-S2-T1 - Phase Verte).
//         - 2026-09-25 : Correction de l'appel via File.ReadLines et ParseLines (J6-S2-T1 - Phase Verte Correction).
//         - 2026-09-25 : Remplacement par File.ReadAllLines pour éviter les locks I/O (J6-S2-T1 - Phase Verte Fix Lock).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.IO;
using System.Threading.Tasks;
using Catamailer.Infrastructure;
using Catamailer.Migrator.Mapping;
using Catamailer.Migrator.Parsing;

namespace Catamailer.Migrator.Orchestration
{
    /// <summary>
    /// Implémentation par défaut de l'orchestrateur coordonnant le parser, le mapper et la base de données.
    /// </summary>
    public class MigrationOrchestrator : IMigrationOrchestrator
    {
        private readonly ICsvParser _parser;
        private readonly IRuleMapper _mapper;
        private readonly CatamailerDbContext _dbContext;

        /// <summary>
        /// Initialise une nouvelle instance de la classe <see cref="MigrationOrchestrator"/>.
        /// </summary>
        /// <param name="parser">Le parseur de fichier CSV.</param>
        /// <param name="mapper">Le mappeur de règles.</param>
        /// <param name="dbContext">Le contexte de base de données cible.</param>
        public MigrationOrchestrator(ICsvParser parser, IRuleMapper mapper, CatamailerDbContext dbContext)
        {
            _parser = parser ?? throw new ArgumentNullException(nameof(parser));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        /// <inheritdoc />
        public async Task MigrateAsync(string csvFilePath)
        {
            if (string.IsNullOrWhiteSpace(csvFilePath))
            {
                throw new ArgumentException("Le chemin du fichier CSV ne peut pas être nul ou vide.", nameof(csvFilePath));
            }

            if (!File.Exists(csvFilePath))
            {
                throw new FileNotFoundException($"Le fichier spécifié est introuvable : {csvFilePath}");
            }

            // Utilisation de ReadAllLines pour libérer immédiatement le verrou sur le fichier
            var lines = File.ReadAllLines(csvFilePath);
            var records = _parser.ParseLines(lines);
            var dictionaryRules = _mapper.Map(records);

            await _dbContext.DictionaryRules.AddRangeAsync(dictionaryRules);
            await _dbContext.SaveChangesAsync();
        }
    }
}