// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale pour J2-S2-T2 (Phase Rouge).
//         - 2026-09-07 : Implémentation du calcul du délai et de la vérification (Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.Application
{
    /// <summary>
    /// Service gérant la suspension temporaire de l'analyse d'historique lors des modifications de règles.
    /// </summary>
    public class DebounceService : IDebounceService
    {
        private readonly IAppSettingsRepository _appSettingsRepository;
        private readonly IHistoryStateRepository _historyStateRepository;
        private readonly TimeProvider _timeProvider;

        public const string DebounceSettingKey = "HistoryDebounceDelayMinutes";
        public const string SuspendedUntilStateKey = "AnalysisSuspendedUntil";
        public const int DefaultDebounceMinutes = 30;

        /// <summary>
        /// Initialise une nouvelle instance de DebounceService.
        /// </summary>
        /// <param name="appSettingsRepository">Dépôt des paramètres d'application.</param>
        /// <param name="historyStateRepository">Dépôt des états système.</param>
        /// <param name="timeProvider">Fournisseur de temps abstrait pour la testabilité.</param>
        public DebounceService(
            IAppSettingsRepository appSettingsRepository,
            IHistoryStateRepository historyStateRepository,
            TimeProvider timeProvider)
        {
            _appSettingsRepository = appSettingsRepository;
            _historyStateRepository = historyStateRepository;
            _timeProvider = timeProvider;
        }

        /// <inheritdoc />
        public async Task SuspendAnalysisAsync()
        {
            var delayString = await _appSettingsRepository.GetSettingAsync(DebounceSettingKey);
            
            if (!int.TryParse(delayString, NumberStyles.Integer, CultureInfo.InvariantCulture, out var delayMinutes))
            {
                delayMinutes = DefaultDebounceMinutes;
            }

            var targetTime = _timeProvider.GetUtcNow().AddMinutes(delayMinutes);
            await _historyStateRepository.SetStateAsync(SuspendedUntilStateKey, targetTime.ToString("o", CultureInfo.InvariantCulture));
        }

        /// <inheritdoc />
        public async Task<bool> IsAnalysisSuspendedAsync()
        {
            var rawValue = await _historyStateRepository.GetStateAsync(SuspendedUntilStateKey);

            if (string.IsNullOrWhiteSpace(rawValue))
            {
                return false;
            }

            if (DateTimeOffset.TryParse(rawValue, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out var suspendedUntil))
            {
                return _timeProvider.GetUtcNow() < suspendedUntil;
            }

            return false;
        }
    }
}