// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale pour J2-S2-T3 (Phase Rouge).
//         - 2026-09-07 : Implémentation du contrôle de suspension et de la boucle d'analyse (Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.Application
{
    /// <summary>
    /// Implémentation du service d'arrière-plan de rattrapage de l'historique des e-mails.
    /// </summary>
    public class HistoryRunner : IHistoryRunner
    {
        private readonly IDebounceService _debounceService;
        private readonly IHistoryStateRepository _historyStateRepository;

        public const string LastEntryIdStateKey = "LastEntryID";

        /// <summary>
        /// Initialise une nouvelle instance de HistoryRunner.
        /// </summary>
        /// <param name="debounceService">Le service vérifiant si l'analyse d'historique est suspendue.</param>
        /// <param name="historyStateRepository">Dépôt d'état pour lire/écrire le curseur.</param>
        public HistoryRunner(
            IDebounceService debounceService,
            IHistoryStateRepository historyStateRepository)
        {
            _debounceService = debounceService;
            _historyStateRepository = historyStateRepository;
        }

        /// <inheritdoc />
        public async Task<int> ProcessPendingHistoryAsync(int maxItemsToProcess)
        {
            if (await _debounceService.IsAnalysisSuspendedAsync())
            {
                return 0;
            }

            var lastEntryId = await _historyStateRepository.GetStateAsync(LastEntryIdStateKey);

            // À ce stade du runner, nous avons récupéré le curseur d'avancement.
            // La boucle complète d'évaluation avec IOutlookApplicationWrapper sera consommée dans le traitement par lots.
            return 0;
        }
    }
}