// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale pour J2-S2-T4 (Phase Rouge).
//         - 2026-09-07 : Implémentation de la télémétrie et du contrôle des paliers (Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.Application
{
    /// <summary>
    /// Service gérant la télémétrie Shadow Mode, le contrôle d'activation et les paliers de notification.
    /// </summary>
    public class ShadowModeService : IShadowModeService
    {
        private readonly IAppSettingsRepository _appSettingsRepository;
        private readonly IHistoryStateRepository _historyStateRepository;

        public const string AutoWriteSettingKey = "IsAutoWriteEnabled";
        public const string MatchCountStateKey = "ShadowModeMatchCount";
        public const string CategoryCountStateKey = "ShadowModeCategoryCount";
        public const string LastPromptMatchCountStateKey = "LastPromptMatchCount";

        /// <summary>
        /// Initialise une nouvelle instance de ShadowModeService.
        /// </summary>
        /// <param name="appSettingsRepository">Dépôt des paramètres d'application.</param>
        /// <param name="historyStateRepository">Dépôt d'état du système.</param>
        public ShadowModeService(
            IAppSettingsRepository appSettingsRepository,
            IHistoryStateRepository historyStateRepository)
        {
            _appSettingsRepository = appSettingsRepository;
            _historyStateRepository = historyStateRepository;
        }

        /// <inheritdoc />
        public async Task RecordPredictionAsync(string entryId, string predictedCategory, string actualCategory)
        {
            if (string.Equals(predictedCategory, actualCategory, StringComparison.OrdinalIgnoreCase))
            {
                var matchCountStr = await _historyStateRepository.GetStateAsync(MatchCountStateKey);
                int.TryParse(matchCountStr, NumberStyles.Integer, CultureInfo.InvariantCulture, out var matchCount);
                matchCount++;

                await _historyStateRepository.SetStateAsync(MatchCountStateKey, matchCount.ToString(CultureInfo.InvariantCulture));
            }
        }

        /// <inheritdoc />
        public async Task<bool> IsAutoWriteEnabledAsync()
        {
            var rawValue = await _appSettingsRepository.GetSettingAsync(AutoWriteSettingKey);
            if (bool.TryParse(rawValue, out var isEnabled))
            {
                return isEnabled;
            }

            return false;
        }

        /// <inheritdoc />
        public async Task SetAutoWriteEnabledAsync(bool enabled)
        {
            await _appSettingsRepository.SetSettingAsync(AutoWriteSettingKey, enabled.ToString().ToLowerInvariant());
        }

        /// <inheritdoc />
        public async Task<bool> ShouldPromptForActivationAsync()
        {
            if (await IsAutoWriteEnabledAsync())
            {
                return false;
            }

            var matchCountStr = await _historyStateRepository.GetStateAsync(MatchCountStateKey);
            int.TryParse(matchCountStr, NumberStyles.Integer, CultureInfo.InvariantCulture, out var matchCount);

            var categoryCountStr = await _historyStateRepository.GetStateAsync(CategoryCountStateKey);
            int.TryParse(categoryCountStr, NumberStyles.Integer, CultureInfo.InvariantCulture, out var categoryCount);

            var lastPromptStr = await _historyStateRepository.GetStateAsync(LastPromptMatchCountStateKey);
            int.TryParse(lastPromptStr, NumberStyles.Integer, CultureInfo.InvariantCulture, out var lastPromptMatchCount);

            if (categoryCount < 30)
            {
                return false;
            }

            var currentPalier = (matchCount / 300) * 300;

            return currentPalier >= 300 && currentPalier > lastPromptMatchCount;
        }

        /// <inheritdoc />
        public async Task AcknowledgeActivationPromptAsync()
        {
            var matchCountStr = await _historyStateRepository.GetStateAsync(MatchCountStateKey);
            int.TryParse(matchCountStr, NumberStyles.Integer, CultureInfo.InvariantCulture, out var matchCount);

            var currentPalier = (matchCount / 300) * 300;

            await _historyStateRepository.SetStateAsync(LastPromptMatchCountStateKey, currentPalier.ToString(CultureInfo.InvariantCulture));
        }
    }
}