// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale (J3-S3-T7).
//         - 2026-09-15 : Ajout de RequestExit et ExitRequested (J3-S3-T7 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;

namespace Catamailer.Application.Services
{
    /// <summary>
    /// Implémentation du service de navigation Blazor déclenché par l'hôte natif.
    /// </summary>
    public class BlazorNavigationService : IBlazorNavigationService
    {
        /// <inheritdoc />
        public event EventHandler<string>? NavigationRequested;

        /// <inheritdoc />
        public event EventHandler? ExitRequested;

        /// <inheritdoc />
        public void RequestNavigation(string uri)
        {
            if (string.IsNullOrWhiteSpace(uri))
            {
                throw new ArgumentNullException(nameof(uri));
            }

            NavigationRequested?.Invoke(this, uri);
        }

        /// <inheritdoc />
        public void RequestExit()
        {
            ExitRequested?.Invoke(this, EventArgs.Empty);
        }
    }
}