#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale de CategorySyncService (J4-S1-T2).
//         - 2026-09-16 : Ajout de la reconstruction d'arbre virtuel et de l'héritage de couleurs (J4-S4-T1).
//         - 2026-09-16 : Transmission simultanée de la couleur brute et de la couleur optimisée (J4-S4-T2).
//         - 2026-09-16 : Application d'un Trim sur le séparateur pour éviter les faux positifs (J4-S4-T2).
//         - 2026-09-17 : Ajout de la remontée de couleur (Bubbling) sur les parents implicites (J4-S4-T2).
//         - 2026-09-17 : Utilisation du FullName pour la résolution croisée et la poussée vers Outlook (J4-S4-T2 - Phase Verte).
//         - 2026-09-17 : Transmission de isImplicit lors de la création du Delta (J4-S4-T2 - Phase Verte).
//         - 2026-09-17 : Ajout de Trim() lors de la remontée hiérarchique pour corriger l'héritage avec espaces (J4-S4-T2 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;
using Catamailer.Domain.Sync;

namespace Catamailer.Application.Services
{
    public class CategorySyncService : ICategorySyncService
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly ICategoryManagerProvider _outlookProvider;

        public CategorySyncService(ICategoryRepository categoryRepository, ICategoryManagerProvider outlookProvider)
        {
            _categoryRepository = categoryRepository;
            _outlookProvider = outlookProvider;
        }

        /// <inheritdoc />
        public async Task<SyncResult> AnalyzeSyncDeltasAsync(string? separator = null)
        {
            var result = new SyncResult();
            var dbCategories = await _categoryRepository.GetAllAsync();
            
            string cleanSeparator = separator?.Trim() ?? "";

            var dbDict = dbCategories.ToDictionary(
                c => string.IsNullOrEmpty(cleanSeparator) ? c.Name : c.GetFullName(cleanSeparator), 
                c => c, 
                StringComparer.OrdinalIgnoreCase);

            var rawOutlookCategories = _outlookProvider.GetAllCategories().ToList();
            var outlookDict = new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase);
            var implicitTracking = new HashSet<string>(StringComparer.OrdinalIgnoreCase); // Track formellement les parents implicites

            foreach (var (Name, ColorCode) in rawOutlookCategories)
            {
                outlookDict[Name] = ColorCode;
            }

            if (!string.IsNullOrEmpty(cleanSeparator))
            {
                var explicitNames = outlookDict.Keys.ToList();
                foreach (var name in explicitNames)
                {
                    var parts = name.Split(new[] { cleanSeparator }, StringSplitOptions.None);
                    string current = "";
                    for (int i = 0; i < parts.Length - 1; i++)
                    {
                        current += (i == 0 ? "" : cleanSeparator) + parts[i].Trim();
                        if (!outlookDict.ContainsKey(current))
                        {
                            outlookDict[current] = null; 
                            implicitTracking.Add(current);
                        }
                    }
                }

                foreach (var parent in implicitTracking)
                {
                    string prefix = parent + cleanSeparator;
                    var physicalDescendants = rawOutlookCategories
                        .Where(c => c.Name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                        .ToList();

                    if (physicalDescendants.Count > 0)
                    {
                        var distinctColors = physicalDescendants
                            .Select(c => c.ColorCode)
                            .Distinct(StringComparer.OrdinalIgnoreCase)
                            .ToList();

                        if (distinctColors.Count == 1 && distinctColors[0] != null)
                        {
                            outlookDict[parent] = distinctColors[0];
                        }
                    }
                }
            }

            foreach (var kvp in outlookDict)
            {
                string outName = kvp.Key;
                string? rawColor = kvp.Value;
                bool isImplicit = implicitTracking.Contains(outName);
                
                string? outOptimizedColor = GetOptimizedOutlookColor(outName, outlookDict, cleanSeparator);

                if (!dbDict.TryGetValue(outName, out var dbCat))
                {
                    result.AddDelta(CategoryDelta.CreateMissingInCatamailer(outName, rawColor, outOptimizedColor, isImplicit));
                }
                else
                {
                    string? dbEff = dbCat.EffectiveColor;
                    string? outEff = GetOutlookEffectiveColor(outName, outlookDict, cleanSeparator);

                    if (!string.Equals(dbEff, outEff, StringComparison.OrdinalIgnoreCase))
                    {
                        result.AddDelta(CategoryDelta.CreateColorMismatch(outName, outEff ?? "", dbEff ?? ""));
                    }
                }
            }

            foreach (var dbCat in dbCategories)
            {
                string dbFullName = string.IsNullOrEmpty(cleanSeparator) ? dbCat.Name : dbCat.GetFullName(cleanSeparator);
                
                if (!outlookDict.ContainsKey(dbFullName))
                {
                    result.AddDelta(CategoryDelta.CreateMissingInOutlook(dbFullName, dbCat.EffectiveColor));
                }
            }

            return result;
        }

        private string? GetOutlookEffectiveColor(string name, Dictionary<string, string?> outlookDict, string cleanSeparator)
        {
            if (string.IsNullOrEmpty(cleanSeparator)) return outlookDict.TryGetValue(name, out var c) ? c : null;
            
            string current = name;
            while (true)
            {
                if (outlookDict.TryGetValue(current, out var color) && color != null)
                    return color;
                
                int lastSep = current.LastIndexOf(cleanSeparator);
                if (lastSep < 0) break;
                current = current.Substring(0, lastSep).Trim(); // Trim ajouté pour s'aligner sur la création des parents virtuels
            }
            return null;
        }

        private string? GetOptimizedOutlookColor(string name, Dictionary<string, string?> outlookDict, string cleanSeparator)
        {
            string? explicitColor = outlookDict[name];
            if (explicitColor == null) return null;
            
            if (string.IsNullOrEmpty(cleanSeparator)) return explicitColor;

            int lastSep = name.LastIndexOf(cleanSeparator);
            if (lastSep < 0) return explicitColor;
            
            string parentName = name.Substring(0, lastSep).Trim(); // Trim ajouté pour la recherche du parent
            string? parentEffective = GetOutlookEffectiveColor(parentName, outlookDict, cleanSeparator);

            if (string.Equals(explicitColor, parentEffective, StringComparison.OrdinalIgnoreCase))
                return null;

            return explicitColor;
        }
    }
}