#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale de CategorySyncService (J4-S1-T2).
//         - 2026-09-16 : Ajout de la reconstruction d'arbre virtuel et de l'héritage de couleurs (J4-S4-T1).
//         - 2026-09-16 : Transmission simultanée de la couleur brute et de la couleur optimisée (J4-S4-T2).
//         - 2026-09-16 : Application d'un Trim sur le séparateur pour éviter les faux positifs (J4-S4-T2).
//         - 2026-09-17 : Ajout de la remontée de couleur (Bubbling) sur les parents implicites (J4-S4-T2).
//         - 2026-09-17 : Utilisation du FullName pour la résolution croisée et la poussée vers Outlook (J4-S4-T2 - Phase Verte).
//         - 2026-09-17 : Transmission de isImplicit lors de la création du Delta (J4-S4-T2 - Phase Verte).
//         - 2026-09-17 : Ajout de Trim() lors de la remontée hiérarchique pour corriger l'héritage avec espaces (J4-S4-T2 - Phase Verte).
//         - 2026-09-17 : Ajout de la création de CategoryDelta.CreateSynchronized pour maintenir le contexte de l'arbre (J4-S4-T4 - Phase Verte).
//         - 2026-09-17 : Suppression de l'héritage simulé pour Outlook afin de révéler les vrais conflits (J4-S4-T5 - Phase Verte).
//         - 2026-09-17 : Ajout de traces Stopwatch pour l'analyse de performance (Diag/Refacto).
//         - 2026-09-23 : Remplacement de Debug.WriteLine par Console.WriteLine pour diagnostic terminal (J4-S4-T7 - Phase Jaune).
//         - 2026-09-23 : Gestion de la suppression logique (IsDeleted) pour générer les Deltas appropriés (J4-S4-T6 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;
using Catamailer.Domain.Sync;

namespace Catamailer.Application.Services
{
    public class CategorySyncService : ICategorySyncService
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly ICategoryManagerProvider _outlookProvider;

        public CategorySyncService(ICategoryRepository categoryRepository, ICategoryManagerProvider outlookProvider)
        {
            _categoryRepository = categoryRepository;
            _outlookProvider = outlookProvider;
        }

        /// <inheritdoc />
        public async Task<SyncResult> AnalyzeSyncDeltasAsync(string? separator = null)
        {
            var sw = Stopwatch.StartNew();
            Console.WriteLine("[CategorySyncService] Début AnalyzeSyncDeltasAsync...");

            var result = new SyncResult();
            
            // On charge TOUTES les catégories SQLite, y compris celles supprimées logiquement, 
            // pour pouvoir les confronter à Outlook.
            var dbCategories = await _categoryRepository.GetAllAsync(includeDeleted: true);
            
            string cleanSeparator = separator?.Trim() ?? "";

            var dbDict = dbCategories.ToDictionary(
                c => string.IsNullOrEmpty(cleanSeparator) ? c.Name : c.GetFullName(cleanSeparator), 
                c => c, 
                StringComparer.OrdinalIgnoreCase);

            Console.WriteLine($"[CategorySyncService] Récupération DB terminée. {dbCategories.Count()} éléments. ({sw.ElapsedMilliseconds}ms)");
            var stepSw = Stopwatch.StartNew();

            var rawOutlookCategories = _outlookProvider.GetAllCategories().ToList();
            var outlookDict = new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase);
            var implicitTracking = new HashSet<string>(StringComparer.OrdinalIgnoreCase); 

            foreach (var (Name, ColorCode) in rawOutlookCategories)
            {
                outlookDict[Name] = ColorCode;
            }

            Console.WriteLine($"[CategorySyncService] Récupération Outlook terminée. {rawOutlookCategories.Count} éléments. ({stepSw.ElapsedMilliseconds}ms)");
            stepSw.Restart();

            if (!string.IsNullOrEmpty(cleanSeparator))
            {
                var explicitNames = outlookDict.Keys.ToList();
                foreach (var name in explicitNames)
                {
                    var parts = name.Split(new[] { cleanSeparator }, StringSplitOptions.None);
                    string current = "";
                    for (int i = 0; i < parts.Length - 1; i++)
                    {
                        current += (i == 0 ? "" : cleanSeparator) + parts[i].Trim();
                        if (!outlookDict.ContainsKey(current))
                        {
                            outlookDict[current] = null; 
                            implicitTracking.Add(current);
                        }
                    }
                }

                foreach (var parent in implicitTracking)
                {
                    string prefix = parent + cleanSeparator;
                    var physicalDescendants = rawOutlookCategories
                        .Where(c => c.Name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                        .ToList();

                    if (physicalDescendants.Count > 0)
                    {
                        var distinctColors = physicalDescendants
                            .Select(c => c.ColorCode)
                            .Distinct(StringComparer.OrdinalIgnoreCase)
                            .ToList();

                        if (distinctColors.Count == 1 && distinctColors[0] != null)
                        {
                            outlookDict[parent] = distinctColors[0];
                        }
                    }
                }
            }

            Console.WriteLine($"[CategorySyncService] Calcul des parents virtuels (Bubbling) terminé. ({stepSw.ElapsedMilliseconds}ms)");
            stepSw.Restart();

            foreach (var kvp in outlookDict)
            {
                string outName = kvp.Key;
                string? rawColor = kvp.Value;
                bool isImplicit = implicitTracking.Contains(outName);
                
                string? outOptimizedColor = GetOptimizedOutlookColor(outName, outlookDict, cleanSeparator);

                if (!dbDict.TryGetValue(outName, out var dbCat))
                {
                    result.AddDelta(CategoryDelta.CreateMissingInCatamailer(outName, rawColor, outOptimizedColor, isImplicit));
                }
                else
                {
                    if (dbCat.IsDeleted)
                    {
                        // Si Outlook connaît la catégorie mais que Catamailer l'a supprimée logiquement
                        result.AddDelta(CategoryDelta.CreateDeletedInCatamailer(outName, rawColor));
                    }
                    else
                    {
                        string? dbEff = dbCat.EffectiveColor;
                        string? outEff = rawColor;

                        if (!string.Equals(dbEff, outEff, StringComparison.OrdinalIgnoreCase))
                        {
                            result.AddDelta(CategoryDelta.CreateColorMismatch(outName, outEff ?? "", dbEff ?? ""));
                        }
                        else
                        {
                            result.AddDelta(CategoryDelta.CreateSynchronized(outName, outEff ?? ""));
                        }
                    }
                }
            }

            foreach (var dbCat in dbCategories)
            {
                if (dbCat.IsDeleted) continue; // Les suppressions logiques non présentes dans Outlook sont déjà réglées
                
                string dbFullName = string.IsNullOrEmpty(cleanSeparator) ? dbCat.Name : dbCat.GetFullName(cleanSeparator);
                
                if (!outlookDict.ContainsKey(dbFullName))
                {
                    result.AddDelta(CategoryDelta.CreateMissingInOutlook(dbFullName, dbCat.EffectiveColor));
                }
            }

            Console.WriteLine($"[CategorySyncService] Comparaison croisée terminée. {result.Deltas.Count} deltas générés. ({stepSw.ElapsedMilliseconds}ms)");
            sw.Stop();
            Console.WriteLine($"[CategorySyncService] AnalyzeSyncDeltasAsync Global : {sw.ElapsedMilliseconds}ms");

            return result;
        }

        private string? GetOptimizedOutlookColor(string name, Dictionary<string, string?> outlookDict, string cleanSeparator)
        {
            string? explicitColor = outlookDict[name];
            if (explicitColor == null) return null;
            
            if (string.IsNullOrEmpty(cleanSeparator)) return explicitColor;

            int lastSep = name.LastIndexOf(cleanSeparator);
            if (lastSep < 0) return explicitColor;
            
            string parentName = name.Substring(0, lastSep).Trim(); 
            
            string? parentEffective = null;
            string current = parentName;
            while(true)
            {
                if (outlookDict.TryGetValue(current, out var color) && color != null)
                {
                    parentEffective = color;
                    break;
                }
                int sep = current.LastIndexOf(cleanSeparator);
                if (sep < 0) break;
                current = current.Substring(0, sep).Trim();
            }

            if (string.Equals(explicitColor, parentEffective, StringComparison.OrdinalIgnoreCase))
                return null;

            return explicitColor;
        }
    }
}