#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale de CategorySyncService (J4-S1-T2 - Phase Verte).
//         - 2026-09-15 : Ajout de l'implémentation de l'interface ICategorySyncService.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;
using Catamailer.Domain.Sync;

namespace Catamailer.Application.Services
{
    /// <summary>
    /// Service responsable de l'analyse et de la synchronisation des catégories entre Outlook et la base de données.
    /// </summary>
    public class CategorySyncService : ICategorySyncService
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly ICategoryManagerProvider _outlookProvider;

        /// <summary>
        /// Initialise une nouvelle instance de <see cref="CategorySyncService"/>.
        /// </summary>
        /// <param name="categoryRepository">Le dépôt des catégories Catamailer (SQLite).</param>
        /// <param name="outlookProvider">Le fournisseur de la Master Category List d'Outlook.</param>
        public CategorySyncService(ICategoryRepository categoryRepository, ICategoryManagerProvider outlookProvider)
        {
            _categoryRepository = categoryRepository;
            _outlookProvider = outlookProvider;
        }

        /// <inheritdoc />
        public async Task<SyncResult> AnalyzeSyncDeltasAsync()
        {
            var result = new SyncResult();

            var dbCategories = await _categoryRepository.GetAllAsync();
            var outlookCategories = _outlookProvider.GetAllCategories();

            var dbDict = dbCategories.ToDictionary(c => c.Name, c => c, StringComparer.OrdinalIgnoreCase);
            var outlookDict = outlookCategories.ToDictionary(c => c.Name, c => c, StringComparer.OrdinalIgnoreCase);

            // 1. Détection : Présent dans Outlook mais absent/différent dans Catamailer
            foreach (var outlookCat in outlookCategories)
            {
                if (!dbDict.TryGetValue(outlookCat.Name, out var dbCat))
                {
                    result.AddDelta(CategoryDelta.CreateMissingInCatamailer(outlookCat.Name, outlookCat.ColorCode));
                }
                else
                {
                    // Comparaison des couleurs (en ignorant la casse pour l'hexa)
                    string? dbColor = dbCat.EffectiveColor;
                    string? outColor = outlookCat.ColorCode;

                    if (!string.Equals(dbColor, outColor, StringComparison.OrdinalIgnoreCase))
                    {
                        result.AddDelta(CategoryDelta.CreateColorMismatch(outlookCat.Name, outColor ?? "", dbColor ?? ""));
                    }
                }
            }

            // 2. Détection : Présent dans Catamailer mais absent d'Outlook
            foreach (var dbCat in dbCategories)
            {
                if (!outlookDict.ContainsKey(dbCat.Name))
                {
                    result.AddDelta(CategoryDelta.CreateMissingInOutlook(dbCat.Name, dbCat.EffectiveColor));
                }
            }

            return result;
        }
    }
}