// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale (J3-S3-T7).
//         - 2026-09-15 : Ajout de RequestExit et ExitRequested (J3-S3-T8 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;

namespace Catamailer.Application.Services
{
    /// <summary>
    /// Contrat définissant le pont de navigation depuis le code natif (MAUI) vers la vue Blazor.
    /// </summary>
    public interface IBlazorNavigationService
    {
        /// <summary>
        /// Événement déclenché lorsqu'une demande de navigation est émise.
        /// La charge utile (string) contient l'URI de destination.
        /// </summary>
        event EventHandler<string>? NavigationRequested;

        /// <summary>
        /// Événement déclenché lorsqu'une demande de fermeture de l'application est émise.
        /// </summary>
        event EventHandler? ExitRequested;

        /// <summary>
        /// Publie une demande de navigation vers une URI spécifique.
        /// </summary>
        /// <param name="uri">L'URI de destination (ex: "/preferences").</param>
        void RequestNavigation(string uri);

        /// <summary>
        /// Publie une demande de fermeture de l'application.
        /// </summary>
        void RequestExit();
    }
}