#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création de l'interface pour le mock UI (J4-S1-T2).
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Threading.Tasks;
using Catamailer.Domain.Sync;

namespace Catamailer.Application.Services
{
    /// <summary>
    /// Contrat du service d'analyse et de synchronisation des catégories.
    /// </summary>
    public interface ICategorySyncService
    {
        /// <summary>
        /// Analyse les différences de catégories entre Outlook et Catamailer.
        /// </summary>
        /// <returns>Un objet contenant les écarts détectés.</returns>
        Task<SyncResult> AnalyzeSyncDeltasAsync();
    }
}