// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale (J3-S3-T7).
//         - 2026-09-15 : Ajout des tests pour RequestExit (J3-S3-T7 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using Catamailer.Application.Services;
using Xunit;

namespace Catamailer.Application.Tests.Services
{
    public class BlazorNavigationServiceTests
    {
        [Fact]
        public void RequestNavigation_ShouldRaiseNavigationRequestedEvent_WithCorrectUri()
        {
            // Arrange
            var service = new BlazorNavigationService();
            string? receivedUri = null;
            
            service.NavigationRequested += (sender, uri) => 
            {
                receivedUri = uri;
            };

            // Act
            service.RequestNavigation("/preferences");

            // Assert
            Assert.Equal("/preferences", receivedUri);
        }

        [Fact]
        public void RequestNavigation_WithNullUri_ShouldThrowArgumentNullException()
        {
            // Arrange
            var service = new BlazorNavigationService();

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => service.RequestNavigation(null!));
        }

        [Fact]
        public void RequestExit_ShouldRaiseExitRequestedEvent()
        {
            // Arrange
            var service = new BlazorNavigationService();
            bool eventRaised = false;

            service.ExitRequested += (sender, e) =>
            {
                eventRaised = true;
            };

            // Act
            service.RequestExit();

            // Assert
            Assert.True(eventRaised);
        }
    }
}