#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale des tests pour CategorySyncService (J4-S1-T2 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;
using Catamailer.Domain.Sync;
using Catamailer.Application.Services;
using Moq;
using Xunit;

namespace Catamailer.Application.Tests.Services
{
    public class CategorySyncServiceTests
    {
        private readonly Mock<ICategoryRepository> _categoryRepositoryMock;
        private readonly Mock<ICategoryManagerProvider> _outlookProviderMock;
        private readonly CategorySyncService _sut; // System Under Test

        public CategorySyncServiceTests()
        {
            _categoryRepositoryMock = new Mock<ICategoryRepository>();
            _outlookProviderMock = new Mock<ICategoryManagerProvider>();
            _sut = new CategorySyncService(_categoryRepositoryMock.Object, _outlookProviderMock.Object);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldReturnNoConflicts_WhenRepositoriesMatchPerfectly()
        {
            // Arrange
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("Cat1", "#000000"), ("Cat2", "#FFFFFF") });

            var dbCategories = new List<CategoryNode>
            {
                new CategoryNode("Cat1", "#000000"),
                new CategoryNode("Cat2", "#FFFFFF")
            };
            _categoryRepositoryMock.Setup(r => r.GetAllAsync()).ReturnsAsync(dbCategories);

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync();

            // Assert
            Assert.False(result.HasConflicts);
            Assert.Empty(result.Deltas);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectMissingInCatamailer()
        {
            // Arrange
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("OutlookOnly", "#FF0000") });

            _categoryRepositoryMock.Setup(r => r.GetAllAsync()).ReturnsAsync(new List<CategoryNode>());

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync();

            // Assert
            Assert.True(result.HasConflicts);
            Assert.Single(result.GetMissingInCatamailer());
            Assert.Equal("OutlookOnly", result.GetMissingInCatamailer().First().CategoryName);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectMissingInOutlook()
        {
            // Arrange
            _outlookProviderMock.Setup(p => p.GetAllCategories()).Returns(new List<(string, string?)>());

            var dbCategories = new List<CategoryNode> { new CategoryNode("DbOnly", "#00FF00") };
            _categoryRepositoryMock.Setup(r => r.GetAllAsync()).ReturnsAsync(dbCategories);

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync();

            // Assert
            Assert.True(result.HasConflicts);
            Assert.Single(result.GetMissingInOutlook());
            Assert.Equal("DbOnly", result.GetMissingInOutlook().First().CategoryName);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectColorMismatch()
        {
            // Arrange
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("SharedCat", "#OUTLOOK") });

            var dbCategories = new List<CategoryNode> { new CategoryNode("SharedCat", "#DBCOLOR") };
            _categoryRepositoryMock.Setup(r => r.GetAllAsync()).ReturnsAsync(dbCategories);

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync();

            // Assert
            Assert.True(result.HasConflicts);
            Assert.Single(result.GetColorConflicts());
            
            var conflict = result.GetColorConflicts().First();
            Assert.Equal("SharedCat", conflict.CategoryName);
            Assert.Equal("#OUTLOOK", conflict.OutlookColor);
            Assert.Equal("#DBCOLOR", conflict.CatamailerColor);
        }
    }
}