#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale des tests pour CategorySyncService (J4-S1-T2).
//         - 2026-09-16 : Ajout des tests de hiérarchie implicite et séparateur dynamique (J4-S4-T1).
//         - 2026-09-16 : Mise à jour des assertions pour utiliser OptimizedColor (J4-S4-T2).
//         - 2026-09-17 : Ajout de la remontée de couleur (Bubbling) sur les parents implicites (J4-S4-T2).
//         - 2026-09-17 : Ajout des tests pour le Trim du séparateur et le FullName vers Outlook (J4-S4-T2).
//         - 2026-09-17 : Ajout d'assertions sur la propriété IsImplicit même après bubbling de couleur (J4-S4-T2).
//         - 2026-09-17 : Renforcement du test Trim pour valider la bonne application de l'héritage (J4-S4-T2).
//         - 2026-09-17 : Ajout du test de détection des catégories synchronisées (J4-S4-T4 - Phase Rouge).
//         - 2026-09-17 : Ajout du test de détection de conflit d'héritage avec Outlook (J4-S4-T5 - Phase Rouge).
//         - 2026-09-23 : Ajout du test de détection des catégories supprimées logiquement (J4-S4-T6 - Phase Rouge).
//         - 2026-09-23 : Mise à jour des Setup Moq pour supporter le paramètre includeDeleted (J4-S4-T6 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;
using Catamailer.Domain.Sync;
using Catamailer.Application.Services;
using Moq;
using Xunit;

namespace Catamailer.Application.Tests.Services
{
    public class CategorySyncServiceTests
    {
        private readonly Mock<ICategoryRepository> _categoryRepositoryMock;
        private readonly Mock<ICategoryManagerProvider> _outlookProviderMock;
        private readonly CategorySyncService _sut;

        public CategorySyncServiceTests()
        {
            _categoryRepositoryMock = new Mock<ICategoryRepository>();
            _outlookProviderMock = new Mock<ICategoryManagerProvider>();
            _sut = new CategorySyncService(_categoryRepositoryMock.Object, _outlookProviderMock.Object);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldReturnNoConflicts_WhenRepositoriesMatchPerfectly()
        {
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("Cat1", "#000000"), ("Cat2", "#FFFFFF") });

            var dbCategories = new List<CategoryNode>
            {
                new CategoryNode("Cat1", "#000000"),
                new CategoryNode("Cat2", "#FFFFFF")
            };
            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(dbCategories);

            var result = await _sut.AnalyzeSyncDeltasAsync();

            Assert.False(result.HasConflicts);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectSynchronizedCategories_ToMaintainTreeContext()
        {
            // Arrange
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("Cat1", "#000000") });

            var dbCategories = new List<CategoryNode> { new CategoryNode("Cat1", "#000000") };
            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(dbCategories);

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync();

            // Assert : Le moteur doit inclure les catégories synchronisées pour que l'IHM puisse dessiner l'arbre complet
            var synchronized = result.GetSynchronized().ToList();
            Assert.Single(synchronized);
            Assert.Equal("Cat1", synchronized[0].CategoryName);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectMissingInCatamailer()
        {
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("OutlookOnly", "#FF0000") });

            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(new List<CategoryNode>());

            var result = await _sut.AnalyzeSyncDeltasAsync();

            Assert.True(result.HasConflicts);
            Assert.Single(result.GetMissingInCatamailer());
            Assert.Equal("OutlookOnly", result.GetMissingInCatamailer().First().CategoryName);
            Assert.False(result.GetMissingInCatamailer().First().IsImplicit);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectMissingInOutlook()
        {
            _outlookProviderMock.Setup(p => p.GetAllCategories()).Returns(new List<(string, string?)>());

            var dbCategories = new List<CategoryNode> { new CategoryNode("DbOnly", "#00FF00") };
            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(dbCategories);

            var result = await _sut.AnalyzeSyncDeltasAsync();

            Assert.True(result.HasConflicts);
            Assert.Single(result.GetMissingInOutlook());
            Assert.Equal("DbOnly", result.GetMissingInOutlook().First().CategoryName);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectColorMismatch()
        {
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("SharedCat", "#OUTLOOK") });

            var dbCategories = new List<CategoryNode> { new CategoryNode("SharedCat", "#DBCOLOR") };
            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(dbCategories);

            var result = await _sut.AnalyzeSyncDeltasAsync();

            Assert.True(result.HasConflicts);
            Assert.Single(result.GetColorConflicts());
            
            var conflict = result.GetColorConflicts().First();
            Assert.Equal("SharedCat", conflict.CategoryName);
            Assert.Equal("#OUTLOOK", conflict.OutlookColor);
            Assert.Equal("#DBCOLOR", conflict.CatamailerColor);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectColorMismatch_WhenOutlookLacksInheritedColor()
        {
            // Arrange
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> 
                { 
                    ("Parent", "#FF0000"),
                    ("Parent-Child", null) // Outlook n'a pas la couleur explicitement
                });

            var parent = new CategoryNode("Parent", "#FF0000");
            var child = new CategoryNode("Child", null);
            parent.AddChild(child); // EffectiveColor de l'enfant devient #FF0000
            
            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(new List<CategoryNode> { parent, child });

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync("-");

            // Assert
            Assert.True(result.HasConflicts);
            var mismatches = result.GetColorConflicts().ToList();
            
            // Actuellement le test va échouer car Catamailer simule l'héritage pour Outlook (faux-positif de Synchronized)
            Assert.Single(mismatches);
            Assert.Equal("Parent-Child", mismatches[0].CategoryName);
            Assert.Equal("", mismatches[0].OutlookColor);
            Assert.Equal("#FF0000", mismatches[0].CatamailerColor);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldCreateImplicitParent_WhenOnlyChildExistsInOutlook()
        {
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("CCOEN-Voyage", "#1ABC9C") });

            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(new List<CategoryNode>());

            var result = await _sut.AnalyzeSyncDeltasAsync("-");

            Assert.True(result.HasConflicts);
            var missing = result.GetMissingInCatamailer().ToList();
            
            Assert.Equal(2, missing.Count);
            
            var parentDelta = missing.FirstOrDefault(m => m.CategoryName == "CCOEN");
            Assert.NotNull(parentDelta);
            Assert.Equal("#1ABC9C", parentDelta.OutlookColor);
            Assert.Equal("#1ABC9C", parentDelta.OptimizedColor);
            Assert.True(parentDelta.IsImplicit);

            var childDelta = missing.FirstOrDefault(m => m.CategoryName == "CCOEN-Voyage");
            Assert.NotNull(childDelta);
            Assert.Equal("#1ABC9C", childDelta.OutlookColor);
            Assert.Null(childDelta.OptimizedColor); 
            Assert.False(childDelta.IsImplicit);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldApplyInheritance_WhenOutlookReturnsSameColorForHierarchy()
        {
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> 
                { 
                    ("CCOEN", "#1ABC9C"),
                    ("CCOEN-Voyage", "#1ABC9C") 
                });

            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(new List<CategoryNode>());

            var result = await _sut.AnalyzeSyncDeltasAsync("-");

            var missing = result.GetMissingInCatamailer().ToList();
            Assert.Equal(2, missing.Count);

            var childDelta = missing.First(m => m.CategoryName == "CCOEN-Voyage");
            Assert.Equal("#1ABC9C", childDelta.OutlookColor); 
            Assert.Null(childDelta.OptimizedColor); 
            Assert.False(childDelta.IsImplicit);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldBubbleUpColorToImplicitParents_WhenAllChildrenShareSameColor()
        {
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> 
                { 
                    ("DAMSI-DA-AE-EAEA", "#800000"),
                    ("DAMSI-DA-AE-Equipiers", "#800000") 
                });

            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(new List<CategoryNode>());

            var result = await _sut.AnalyzeSyncDeltasAsync("-");

            var missing = result.GetMissingInCatamailer().ToList();
            Assert.Equal(5, missing.Count);

            var damsi = missing.First(m => m.CategoryName == "DAMSI");
            Assert.Equal("#800000", damsi.OutlookColor);
            Assert.Equal("#800000", damsi.OptimizedColor);
            Assert.True(damsi.IsImplicit); 

            var eaea = missing.First(m => m.CategoryName == "DAMSI-DA-AE-EAEA");
            Assert.False(eaea.IsImplicit); 
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldTrimSpacesAroundSeparator_ToGroupCorrectly()
        {
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> 
                { 
                    ("Cercle A", "#0000FF"),
                    ("Cercle A - PAG", "#0000FF") 
                });

            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(new List<CategoryNode>());

            var result = await _sut.AnalyzeSyncDeltasAsync("-");

            var missing = result.GetMissingInCatamailer().ToList();
            
            Assert.Equal(2, missing.Count);
            Assert.Contains(missing, m => m.CategoryName == "Cercle A");
            
            var child = missing.FirstOrDefault(m => m.CategoryName == "Cercle A - PAG");
            Assert.NotNull(child);
            Assert.Null(child.OptimizedColor); 
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldUseFullName_WhenPushingToOutlook()
        {
            _outlookProviderMock.Setup(p => p.GetAllCategories()).Returns(new List<(string, string?)>());

            var parent = new CategoryNode("Projet Alpha", "#0000FF");
            var child = new CategoryNode("Design", null);
            parent.AddChild(child);

            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(new List<CategoryNode> { parent, child });

            var result = await _sut.AnalyzeSyncDeltasAsync("-");

            var missingInOutlook = result.GetMissingInOutlook().ToList();
            Assert.Equal(2, missingInOutlook.Count);
            
            Assert.Contains(missingInOutlook, m => m.CategoryName == "Projet Alpha");
            Assert.Contains(missingInOutlook, m => m.CategoryName == "Projet Alpha-Design");
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectDeletedInCatamailer_WhenCategoryIsLogicallyDeleted()
        {
            // Arrange
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("DeletedCat", "#000000") });

            var deletedNode = new CategoryNode("DeletedCat", "#000000");
            deletedNode.MarkAsDeleted(); // IsDeleted = true

            _categoryRepositoryMock.Setup(r => r.GetAllAsync(It.IsAny<bool>())).ReturnsAsync(new List<CategoryNode> { deletedNode });

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync();

            // Assert
            Assert.True(result.HasConflicts);
            var deletedDeltas = result.GetDeletedInCatamailer().ToList();
            Assert.Single(deletedDeltas);
            Assert.Equal("DeletedCat", deletedDeltas[0].CategoryName);
            Assert.Equal("#000000", deletedDeltas[0].OutlookColor);
            
            // Ne doit pas apparaître dans les synchronisés ni dans les manquants dans Catamailer
            Assert.Empty(result.GetSynchronized());
            Assert.Empty(result.GetMissingInCatamailer());
        }
    }
}