#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale des tests pour CategorySyncService (J4-S1-T2 - Phase Rouge).
//         - 2026-09-16 : Ajout des tests de hiérarchie implicite et séparateur dynamique (J4-S4-T1 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;
using Catamailer.Domain.Sync;
using Catamailer.Application.Services;
using Moq;
using Xunit;

namespace Catamailer.Application.Tests.Services
{
    public class CategorySyncServiceTests
    {
        private readonly Mock<ICategoryRepository> _categoryRepositoryMock;
        private readonly Mock<ICategoryManagerProvider> _outlookProviderMock;
        private readonly CategorySyncService _sut; // System Under Test

        public CategorySyncServiceTests()
        {
            _categoryRepositoryMock = new Mock<ICategoryRepository>();
            _outlookProviderMock = new Mock<ICategoryManagerProvider>();
            _sut = new CategorySyncService(_categoryRepositoryMock.Object, _outlookProviderMock.Object);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldReturnNoConflicts_WhenRepositoriesMatchPerfectly()
        {
            // Arrange
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("Cat1", "#000000"), ("Cat2", "#FFFFFF") });

            var dbCategories = new List<CategoryNode>
            {
                new CategoryNode("Cat1", "#000000"),
                new CategoryNode("Cat2", "#FFFFFF")
            };
            _categoryRepositoryMock.Setup(r => r.GetAllAsync()).ReturnsAsync(dbCategories);

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync();

            // Assert
            Assert.False(result.HasConflicts);
            Assert.Empty(result.Deltas);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectMissingInCatamailer()
        {
            // Arrange
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("OutlookOnly", "#FF0000") });

            _categoryRepositoryMock.Setup(r => r.GetAllAsync()).ReturnsAsync(new List<CategoryNode>());

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync();

            // Assert
            Assert.True(result.HasConflicts);
            Assert.Single(result.GetMissingInCatamailer());
            Assert.Equal("OutlookOnly", result.GetMissingInCatamailer().First().CategoryName);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectMissingInOutlook()
        {
            // Arrange
            _outlookProviderMock.Setup(p => p.GetAllCategories()).Returns(new List<(string, string?)>());

            var dbCategories = new List<CategoryNode> { new CategoryNode("DbOnly", "#00FF00") };
            _categoryRepositoryMock.Setup(r => r.GetAllAsync()).ReturnsAsync(dbCategories);

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync();

            // Assert
            Assert.True(result.HasConflicts);
            Assert.Single(result.GetMissingInOutlook());
            Assert.Equal("DbOnly", result.GetMissingInOutlook().First().CategoryName);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldDetectColorMismatch()
        {
            // Arrange
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("SharedCat", "#OUTLOOK") });

            var dbCategories = new List<CategoryNode> { new CategoryNode("SharedCat", "#DBCOLOR") };
            _categoryRepositoryMock.Setup(r => r.GetAllAsync()).ReturnsAsync(dbCategories);

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync();

            // Assert
            Assert.True(result.HasConflicts);
            Assert.Single(result.GetColorConflicts());
            
            var conflict = result.GetColorConflicts().First();
            Assert.Equal("SharedCat", conflict.CategoryName);
            Assert.Equal("#OUTLOOK", conflict.OutlookColor);
            Assert.Equal("#DBCOLOR", conflict.CatamailerColor);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldCreateImplicitParent_WhenOnlyChildExistsInOutlook()
        {
            // Arrange
            // Outlook retourne uniquement l'enfant "CCOEN-Voyage", le parent "CCOEN" n'existe pas physiquement dans Outlook
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> { ("CCOEN-Voyage", "#1ABC9C") });

            _categoryRepositoryMock.Setup(r => r.GetAllAsync()).ReturnsAsync(new List<CategoryNode>());

            // Act
            // On passe le séparateur "-" pour déclencher la détection d'arborescence
            var result = await _sut.AnalyzeSyncDeltasAsync("-");

            // Assert
            Assert.True(result.HasConflicts);
            var missing = result.GetMissingInCatamailer().ToList();
            
            // Il doit proposer d'importer le parent IMPLICITE ET l'enfant EXPLICITE
            Assert.Equal(2, missing.Count);
            
            var parentDelta = missing.FirstOrDefault(m => m.CategoryName == "CCOEN");
            Assert.NotNull(parentDelta);
            Assert.Null(parentDelta.OutlookColor); // Le parent implicite n'a pas de couleur propre lue dans Outlook

            var childDelta = missing.FirstOrDefault(m => m.CategoryName == "CCOEN-Voyage");
            Assert.NotNull(childDelta);
            Assert.Equal("#1ABC9C", childDelta.OutlookColor);
        }

        [Fact]
        public async Task AnalyzeSyncDeltasAsync_ShouldApplyInheritance_WhenOutlookReturnsSameColorForHierarchy()
        {
            // Arrange
            // Outlook retourne le parent et l'enfant avec la même couleur
            _outlookProviderMock.Setup(p => p.GetAllCategories())
                .Returns(new List<(string, string?)> 
                { 
                    ("CCOEN", "#1ABC9C"),
                    ("CCOEN-Voyage", "#1ABC9C") 
                });

            _categoryRepositoryMock.Setup(r => r.GetAllAsync()).ReturnsAsync(new List<CategoryNode>());

            // Act
            var result = await _sut.AnalyzeSyncDeltasAsync("-");

            // Assert
            var missing = result.GetMissingInCatamailer().ToList();
            Assert.Equal(2, missing.Count);

            var childDelta = missing.First(m => m.CategoryName == "CCOEN-Voyage");
            // S'il a la même couleur que son parent dans l'arborescence reconstruite,
            // Catamailer devrait optimiser en utilisant l'héritage (donc null explicitement)
            Assert.Null(childDelta.OutlookColor); 
        }
    }
}