// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-09
//     Historique :
//         - 2026-09-09 : Création initiale du faux dépôt pour DictionaryRule (J3-S2-T2-ST2).
//         - 2026-09-11 : Ajout des méthodes pour ExecutionRule (J3-S3-T3-ST2 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.UI.Dummies
{
    /// <summary>
    /// Dépôt factice pour fournir des règles en l'absence de base de données.
    /// </summary>
    public class DummyRuleRepository : IRuleRepository
    {
        private readonly List<DictionaryRule> _dictionaryRules = new();
        private readonly List<ExecutionRule> _executionRules = new();

        public Task<IEnumerable<DictionaryRule>> GetAllDictionaryRulesAsync()
        {
            return Task.FromResult(_dictionaryRules.AsEnumerable());
        }

        public Task AddDictionaryRuleAsync(DictionaryRule rule)
        {
            _dictionaryRules.Add(rule);
            return Task.CompletedTask;
        }

        public Task DeleteDictionaryRuleAsync(DictionaryRule rule)
        {
            _dictionaryRules.Remove(rule);
            return Task.CompletedTask;
        }

        public Task<IEnumerable<ExecutionRule>> GetAllExecutionRulesAsync()
        {
            return Task.FromResult(_executionRules.AsEnumerable());
        }

        public Task AddExecutionRuleAsync(ExecutionRule rule)
        {
            _executionRules.Add(rule);
            return Task.CompletedTask;
        }

        public Task DeleteExecutionRuleAsync(ExecutionRule rule)
        {
            _executionRules.Remove(rule);
            return Task.CompletedTask;
        }
    }
}