// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-08
//     Historique :
//         - 2026-09-08 : Création initiale dans MauiProgram.
//         - 2026-09-09 : Extraction vers un fichier dédié (J3-S3-T0 - Phase Orange).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Threading.Tasks;
using Catamailer.Domain;

namespace Catamailer.UI.Dummies
{
    /// <summary>
    /// Dépôt factice pour fournir des règles en l'absence de base de données implémentée pour DictionaryRule.
    /// TODO: À supprimer une fois le vrai dépôt implémenté.
    /// </summary>
    public class DummyRuleRepository : IRuleRepository
    {
        /// <inheritdoc />
        public Task<IEnumerable<DictionaryRule>> GetAllDictionaryRulesAsync()
        {
            var dummyRule = new DictionaryRule(
                new CategoryNode("Urgent"), 
                subjectKeywords: new[] { "Urgent" });
                
            return Task.FromResult<IEnumerable<DictionaryRule>>(new List<DictionaryRule> { dummyRule });
        }
    }
}