// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-09
//     Historique :
//         - 2026-09-09 : Création pour isoler le jeu de test factice (J3-S3-T0 - Phase Orange).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Linq;
using Catamailer.Domain;
using Catamailer.Infrastructure;
using Microsoft.Extensions.DependencyInjection;

namespace Catamailer.UI.Dummies
{
    /// <summary>
    /// Injecte un jeu de catégories factices pour le développement.
    /// TODO: À supprimer une fois l'import depuis Outlook implémenté.
    /// </summary>
    public static class DummyCategorySeeder
    {
        /// <summary>
        /// Injecte les catégories de test si la base est vide.
        /// </summary>
        /// <param name="serviceProvider">Le fournisseur de services de l'application.</param>
        public static void SeedDummyCategories(this IServiceProvider serviceProvider)
        {
            using var scope = serviceProvider.CreateScope();
            var dbContext = scope.ServiceProvider.GetRequiredService<CatamailerDbContext>();
            
            if (!dbContext.Categories.Any())
            {
                var urgent = new CategoryNode("Urgent", "#dc3545");
                var alpha = new CategoryNode("Projet Alpha", "#0d6efd");
                var alphaDesign = new CategoryNode("Projet Alpha - Design"); // Sans couleur
                
                alpha.AddChild(alphaDesign); // Héritage de la couleur de "Projet Alpha"

                var beta = new CategoryNode("Projet Beta", "#198754");
                var aLire = new CategoryNode("A Lire", "#ffc107");

                dbContext.Categories.AddRange(urgent, alpha, alphaDesign, beta, aLire);
                dbContext.SaveChanges();
            }
        }
    }
}