// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-08
//     Historique :
//         - 2026-09-08 : Création initiale dans MauiProgram.
//         - 2026-09-09 : Extraction vers un fichier dédié (J3-S3-T0 - Phase Orange).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using Catamailer.Domain;

namespace Catamailer.UI.Dummies
{
    /// <summary>
    /// Fournisseur factice pour valider l'IHM sans dépendre d'Outlook en phase de développement.
    /// TODO: À supprimer une fois l'intégration Outlook finalisée.
    /// </summary>
    public class DummySelectionProvider : ISelectionProvider
    {
        /// <inheritdoc />
        public MailMetadata? GetSelectedMail()
        {
            return new MailMetadata(
                "dummy-id", 
                "[Urgent] Réunion Projet Alpha", 
                "client@important.com", 
                "assistant@important.com",
                new List<string>(),
                new List<string> { "team@important.com" });
        }
    }
}