#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création pour permettre le test de la modale de synchro (J4-S2 - Phase Orange).
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Catamailer.Domain;

namespace Catamailer.UI.Dummies
{
    /// <summary>
    /// Fournisseur factice simulant les retours d'Outlook pour tester l'IHM de synchronisation.
    /// </summary>
    public class DummyCategoryManagerProvider : ICategoryManagerProvider
    {
        /// <inheritdoc />
        public IEnumerable<(string Name, string? ColorCode)> GetAllCategories()
        {
            // Retourne un jeu de données conçu pour déclencher les 3 types de conflits :
            // 1. "Projet Alpha" (déjà dans SQLite via Seeder, mais on simule une couleur différente = Conflit Couleur)
            // 2. "Urgent" (déjà dans SQLite via Seeder avec couleur différente = Conflit Couleur)
            // 3. "Réunion CODIR" (absent de SQLite = Manquant dans Catamailer)
            // Note: "Projet Beta" (présent dans SQLite via Seeder) n'est pas ici = Manquant dans Outlook
            return new List<(string Name, string? ColorCode)>
            {
                ("Projet Alpha", "#000000"), // Noir au lieu de rouge
                ("Urgent", "#00FF00"), // Vert au lieu de rouge
                ("Réunion CODIR", "#0000FF"),
                ("Catégorie Outlook Obsolète", "#CCCCCC")
            };
        }

        /// <inheritdoc />
        public void AddCategory(string name, string colorCode)
        {
            // Ne fait rien en mode Dummy
            System.Diagnostics.Debug.WriteLine($"[DUMMY] AddCategory: {name} ({colorCode})");
        }

        /// <inheritdoc />
        public void UpdateCategoryColor(string name, string newColorCode)
        {
            // Ne fait rien en mode Dummy
            System.Diagnostics.Debug.WriteLine($"[DUMMY] UpdateCategoryColor: {name} ({newColorCode})");
        }

        /// <inheritdoc />
        public void RemoveCategory(string name)
        {
            // Ne fait rien en mode Dummy
            System.Diagnostics.Debug.WriteLine($"[DUMMY] RemoveCategory: {name}");
        }
    }
}