// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

namespace Catamailer.Domain
{
    /// <summary>
    /// Représente un paramètre de configuration globale de l'application.
    /// </summary>
    public class AppSetting
    {
        /// <summary>
        /// La clé unique du paramètre (ex: "HistoryDebounceDelayMinutes").
        /// </summary>
        public string Key { get; set; } = string.Empty;

        /// <summary>
        /// La valeur du paramètre stockée sous forme de chaîne.
        /// </summary>
        public string Value { get; set; } = string.Empty;
    }
}