#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Historique :
//         - 2026-09-07 : Création de l'entité CategoryNode (J1-S1-T1).
//         - 2026-09-07 : Ajout du constructeur protégé pour compatibilité avec Entity Framework Core (J1-S1-T3).
//         - 2026-09-11 : Ajout de Depth et GetFullName pour le rendu hiérarchique (J3-S3-T3-ST2).
//         - 2026-09-17 : Ajout de la méthode UpdateColor pour résolution de conflit (J4-S4-T4 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Catamailer.Domain
{
    /// <summary>
    /// Représente un nœud dans l'arbre hiérarchique des catégories, agissant comme vérité absolue (Master Data Management).
    /// </summary>
    public class CategoryNode
    {
        private readonly List<CategoryNode> _children = new();

        /// <summary>
        /// Obtient le nom de la catégorie.
        /// </summary>
        public string Name { get; private set; }

        /// <summary>
        /// Obtient la couleur explicitement définie pour cette catégorie, ou null si elle doit hériter de son parent.
        /// </summary>
        public string? Color { get; private set; }

        /// <summary>
        /// Obtient le parent de cette catégorie dans l'arbre.
        /// </summary>
        public CategoryNode? Parent { get; private set; }

        /// <summary>
        /// Obtient la liste en lecture seule des enfants de cette catégorie.
        /// </summary>
        public IReadOnlyList<CategoryNode> Children => _children.AsReadOnly();

        /// <summary>
        /// Obtient la couleur effective de la catégorie, en héritant de son ascendance si aucune couleur explicite n'est définie.
        /// </summary>
        public string? EffectiveColor => Color ?? Parent?.EffectiveColor;

        /// <summary>
        /// Obtient la profondeur du nœud dans l'arborescence (0 pour un nœud racine).
        /// </summary>
        public int Depth => Parent == null ? 0 : Parent.Depth + 1;

        /// <summary>
        /// Constructeur sans paramètre requis par Entity Framework Core pour la matérialisation.
        /// </summary>
        protected CategoryNode()
        {
            Name = null!; // EF Core se chargera d'affecter la valeur via réflexion.
        }

        /// <summary>
        /// Initialise une nouvelle instance de la classe <see cref="CategoryNode"/>.
        /// </summary>
        /// <param name="name">Le nom de la catégorie.</param>
        /// <param name="color">La couleur explicite au format hexadécimal (optionnelle).</param>
        public CategoryNode(string name, string? color = null)
        {
            Name = name;
            Color = color;
        }

        /// <summary>
        /// Ajoute un nœud enfant à cette catégorie et lie automatiquement ce nœud à ce parent.
        /// </summary>
        /// <param name="child">Le nœud enfant à ajouter.</param>
        public void AddChild(CategoryNode child)
        {
            child.Parent = this;
            _children.Add(child);
        }

        /// <summary>
        /// Met à jour la couleur explicite de la catégorie.
        /// </summary>
        /// <param name="newColor">La nouvelle couleur au format hexadécimal, ou null pour forcer l'héritage.</param>
        public void UpdateColor(string? newColor)
        {
            Color = newColor;
        }

        /// <summary>
        /// Récupère la chaîne d'ascendance complète depuis la racine jusqu'à ce nœud inclus.
        /// </summary>
        /// <returns>Une énumération des nœuds de la racine vers la feuille.</returns>
        public IEnumerable<CategoryNode> GetAscendanceChain()
        {
            var chain = new List<CategoryNode>();
            var current = this;

            while (current != null)
            {
                chain.Add(current);
                current = current.Parent;
            }

            chain.Reverse();
            return chain;
        }

        /// <summary>
        /// Génère le nom complet de la catégorie incluant toute son ascendance, séparée par le caractère spécifié.
        /// </summary>
        /// <param name="separator">Le séparateur (par défaut "-").</param>
        /// <returns>Le nom complet (ex: "Projet Alpha-Design").</returns>
        public string GetFullName(string separator = "-")
        {
            return string.Join(separator, GetAscendanceChain().Select(c => c.Name));
        }
    }
}