// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;

namespace Catamailer.Domain
{
    /// <summary>
    /// Contrat pour la gestion des paramètres globaux de l'application.
    /// </summary>
    public interface IAppSettingsRepository
    {
        /// <summary>
        /// Récupère la valeur d'un paramètre.
        /// </summary>
        /// <param name="key">La clé du paramètre.</param>
        /// <returns>La valeur si trouvée, null sinon.</returns>
        Task<string?> GetSettingAsync(string key);

        /// <summary>
        /// Enregistre ou met à jour la valeur d'un paramètre.
        /// </summary>
        /// <param name="key">La clé du paramètre.</param>
        /// <param name="value">La nouvelle valeur.</param>
        Task SetSettingAsync(string key, string value);
    }
}