// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

namespace Catamailer.Domain
{
    /// <summary>
    /// Définit le contrat permettant de gérer les catégories au sein du fournisseur de messagerie (ex: Master Category List).
    /// </summary>
    public interface ICategoryManagerProvider
    {
        /// <summary>
        /// Ajoute une nouvelle catégorie.
        /// </summary>
        /// <param name="name">Le nom de la catégorie.</param>
        /// <param name="colorCode">Le code couleur associé.</param>
        void AddCategory(string name, string colorCode);

        /// <summary>
        /// Met à jour la couleur d'une catégorie existante.
        /// </summary>
        /// <param name="name">Le nom de la catégorie.</param>
        /// <param name="newColorCode">Le nouveau code couleur.</param>
        void UpdateCategoryColor(string name, string newColorCode);

        /// <summary>
        /// Supprime une catégorie existante.
        /// </summary>
        /// <param name="name">Le nom de la catégorie à supprimer.</param>
        void RemoveCategory(string name);
    }
}