// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale de ICategoryRepository (J1-S1-T3).
//         - 2026-09-17 : Implémentation de UpdateAsync (J4-S4-T4).
//         - 2026-09-23 : Ajout des opérations par lots AddRangeAsync et UpdateRangeAsync (J4-S4-T7 - Phase Verte).
//         - 2026-09-23 : Modification de GetAllAsync pour supporter le filtre IsDeleted (J4-S4-T6 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Catamailer.Domain
{
    /// <summary>
    /// Définit le contrat pour l'accès aux données de l'entité CategoryNode.
    /// </summary>
    public interface ICategoryRepository
    {
        /// <summary>
        /// Ajoute une nouvelle catégorie dans le référentiel.
        /// </summary>
        /// <param name="category">La catégorie à ajouter.</param>
        Task AddAsync(CategoryNode category);

        /// <summary>
        /// Ajoute une liste de nouvelles catégories en lot dans le référentiel.
        /// </summary>
        /// <param name="categories">Les catégories à ajouter.</param>
        Task AddRangeAsync(IEnumerable<CategoryNode> categories);

        /// <summary>
        /// Met à jour une catégorie existante dans le référentiel.
        /// </summary>
        /// <param name="category">La catégorie à mettre à jour.</param>
        Task UpdateAsync(CategoryNode category);

        /// <summary>
        /// Met à jour une liste de catégories en lot dans le référentiel.
        /// </summary>
        /// <param name="categories">Les catégories à mettre à jour.</param>
        Task UpdateRangeAsync(IEnumerable<CategoryNode> categories);

        /// <summary>
        /// Récupère une catégorie par son nom exact.
        /// </summary>
        /// <param name="name">Le nom de la catégorie.</param>
        /// <returns>La catégorie correspondante, ou null si elle n'existe pas.</returns>
        Task<CategoryNode?> GetByNameAsync(string name);

        /// <summary>
        /// Récupère toutes les catégories du référentiel.
        /// </summary>
        /// <param name="includeDeleted">Si vrai, inclut les catégories marquées comme supprimées logiquement (IsDeleted = true).</param>
        /// <returns>Une collection de toutes les catégories.</returns>
        Task<IEnumerable<CategoryNode>> GetAllAsync(bool includeDeleted = false);
    }
}