#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-15 : Ajout de GetAllCategories pour la synchronisation (J4-S1-T2).
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Catamailer.Domain
{
    /// <summary>
    /// Définit le contrat permettant de gérer les catégories au sein du fournisseur de messagerie (ex: Master Category List).
    /// </summary>
    public interface ICategoryManagerProvider
    {
        /// <summary>
        /// Récupère l'intégralité des catégories existantes dans le fournisseur (Outlook).
        /// </summary>
        /// <returns>Une collection de tuples contenant le nom et la couleur de chaque catégorie.</returns>
        IEnumerable<(string Name, string? ColorCode)> GetAllCategories();

        /// <summary>
        /// Ajoute une nouvelle catégorie.
        /// </summary>
        /// <param name="name">Le nom de la catégorie.</param>
        /// <param name="colorCode">Le code couleur associé.</param>
        void AddCategory(string name, string colorCode);

        /// <summary>
        /// Met à jour la couleur d'une catégorie existante.
        /// </summary>
        /// <param name="name">Le nom de la catégorie.</param>
        /// <param name="newColorCode">Le nouveau code couleur.</param>
        void UpdateCategoryColor(string name, string newColorCode);

        /// <summary>
        /// Supprime une catégorie existante.
        /// </summary>
        /// <param name="name">Le nom de la catégorie à supprimer.</param>
        void RemoveCategory(string name);
    }
}