// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale pour J2-S2-T2 (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;

namespace Catamailer.Domain
{
    /// <summary>
    /// Définit le contrat permettant de gérer la suspension temporaire des traitements d'arrière-plan (Debounce).
    /// </summary>
    public interface IDebounceService
    {
        /// <summary>
        /// Déclenche la suspension de l'analyse d'historique en fonction du délai configuré dans l'application.
        /// </summary>
        /// <returns>Une tâche représentant l'opération asynchrone.</returns>
        Task SuspendAnalysisAsync();

        /// <summary>
        /// Indique si l'analyse d'historique est actuellement suspendue.
        /// </summary>
        /// <returns>Vrai si l'analyse est suspendue, faux sinon.</returns>
        Task<bool> IsAnalysisSuspendedAsync();
    }
}