// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-24
//     Historique :
//         - 2026-09-24 : Création de l'interface d'abstraction des ressources externes (J6-S1-T1 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Catamailer.Domain
{
    /// <summary>
    /// Fournit l'accès aux ressources externes nécessaires à la configuration des règles (ex: dossiers, signatures),
    /// de manière agnostique vis-à-vis de l'infrastructure sous-jacente (Outlook).
    /// </summary>
    public interface IExternalResourceProvider
    {
        /// <summary>
        /// Récupère la liste des chemins de dossiers disponibles.
        /// </summary>
        Task<IEnumerable<string>> GetAvailableFolderPathsAsync();

        /// <summary>
        /// Récupère la liste des noms de signatures configurées sur le poste.
        /// </summary>
        Task<IEnumerable<string>> GetAvailableSignaturesAsync();
    }
}