// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale pour J2-S2-T3 (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;

namespace Catamailer.Domain
{
    /// <summary>
    /// Définit le contrat du service d'arrière-plan analysant le stock d'e-mails historiques.
    /// </summary>
    public interface IHistoryRunner
    {
        /// <summary>
        /// Traite un lot d'e-mails d'historique non encore analysés.
        /// </summary>
        /// <param name="maxItemsToProcess">Le nombre maximal d'e-mails à traiter dans ce lot.</param>
        /// <returns>Le nombre effectif d'e-mails traités.</returns>
        Task<int> ProcessPendingHistoryAsync(int maxItemsToProcess);
    }
}