// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;

namespace Catamailer.Domain
{
    /// <summary>
    /// Contrat pour la gestion des états systèmes internes.
    /// </summary>
    public interface IHistoryStateRepository
    {
        /// <summary>
        /// Récupère la valeur d'un état système.
        /// </summary>
        /// <param name="key">La clé de l'état.</param>
        /// <returns>La valeur si trouvée, null sinon.</returns>
        Task<string?> GetStateAsync(string key);

        /// <summary>
        /// Enregistre ou met à jour la valeur d'un état système.
        /// </summary>
        /// <param name="key">La clé de l'état.</param>
        /// <param name="value">La nouvelle valeur.</param>
        Task SetStateAsync(string key, string value);
    }
}