// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace Catamailer.Domain
{
    /// <summary>
    /// Définit le contrat d'écoute et d'interaction avec le fournisseur de messagerie.
    /// </summary>
    public interface IMailProvider
    {
        /// <summary>
        /// Événement déclenché lors de la réception d'un nouvel e-mail.
        /// </summary>
        event EventHandler<MailMetadata> NewMailReceived;

        /// <summary>
        /// Démarre l'écoute des nouveaux e-mails.
        /// </summary>
        void StartListening();

        /// <summary>
        /// Arrête l'écoute des nouveaux e-mails.
        /// </summary>
        void StopListening();
    }
}