// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

namespace Catamailer.Domain
{
    /// <summary>
    /// Définit le contrat permettant la mise à jour en masse (renommage rétroactif) des catégories sur les e-mails existants.
    /// </summary>
    public interface IMassUpdateProvider
    {
        /// <summary>
        /// Parcourt l'historique des e-mails et remplace une ancienne catégorie par une nouvelle.
        /// </summary>
        /// <param name="oldCategoryName">Le nom de la catégorie à remplacer.</param>
        /// <param name="newCategoryName">Le nom de la nouvelle catégorie.</param>
        void UpdateCategoryNameOnItems(string oldCategoryName, string newCategoryName);
    }
}