// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

namespace Catamailer.Domain
{
    /// <summary>
    /// Définit le contrat permettant de récupérer l'élément actuellement sélectionné dans le client de messagerie.
    /// </summary>
    public interface ISelectionProvider
    {
        /// <summary>
        /// Récupère les métadonnées de l'e-mail actuellement sélectionné dans l'interface utilisateur.
        /// </summary>
        /// <returns>Les métadonnées de l'e-mail sélectionné, ou null si aucun e-mail n'est sélectionné.</returns>
        MailMetadata? GetSelectedMail();
    }
}