// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale pour J2-S2-T4 (Phase Rouge).
//         - 2026-09-09 : Ajout de GetTelemetryStatsAsync pour le Dashboard (J3-S3-T1 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;

namespace Catamailer.Domain
{
    /// <summary>
    /// Définit le contrat du service de Shadow Mode et de contrôle des autorisations d'écriture dans Outlook.
    /// </summary>
    public interface IShadowModeService
    {
        /// <summary>
        /// Enregistre une prédiction et vérifie la correspondance avec l'action réelle.
        /// </summary>
        /// <param name="entryId">L'identifiant du mail.</param>
        /// <param name="predictedCategory">La catégorie prédite par C#.</param>
        /// <param name="actualCategory">La catégorie appliquée réellement.</param>
        Task RecordPredictionAsync(string entryId, string predictedCategory, string actualCategory);

        /// <summary>
        /// Indique si l'écriture automatique dans Outlook est activée par l'utilisateur.
        /// </summary>
        Task<bool> IsAutoWriteEnabledAsync();

        /// <summary>
        /// Active ou désactive l'écriture automatique dans Outlook.
        /// </summary>
        Task SetAutoWriteEnabledAsync(bool enabled);

        /// <summary>
        /// Vérifie si une notification d'activation doit être présentée à l'utilisateur (paliers de 300 correspondances sur 30 catégories).
        /// </summary>
        Task<bool> ShouldPromptForActivationAsync();

        /// <summary>
        /// Marque la notification comme vue pour le palier courant afin d'attendre le prochain palier (+300).
        /// </summary>
        Task AcknowledgeActivationPromptAsync();

        /// <summary>
        /// Récupère les statistiques actuelles de la télémétrie du Shadow Mode.
        /// </summary>
        /// <returns>Un tuple contenant le nombre de correspondances, de catégories validées et l'état de l'écriture automatique.</returns>
        Task<(int MatchCount, int CategoryCount, bool IsAutoWriteEnabled)> GetTelemetryStatsAsync();
    }
}