// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Catamailer.Domain
{
    /// <summary>
    /// Représente les métadonnées agnostiques extraites d'un e-mail.
    /// </summary>
    /// <param name="EntryId">L'identifiant unique de l'e-mail dans le système source.</param>
    /// <param name="Subject">Le sujet de l'e-mail.</param>
    /// <param name="Sender">L'adresse de l'expéditeur.</param>
    /// <param name="Recipients">La liste des adresses des destinataires.</param>
    public record MailMetadata(string EntryId, string Subject, string Sender, IEnumerable<string> Recipients);
}