// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

namespace Catamailer.Domain
{
    /// <summary>
    /// Représente un état système interne (ex: curseur d'avancement).
    /// </summary>
    public class SystemState
    {
        /// <summary>
        /// La clé unique identifiant l'état (ex: "LastEntryID").
        /// </summary>
        public string Key { get; set; } = string.Empty;

        /// <summary>
        /// La valeur associée à l'état.
        /// </summary>
        public string Value { get; set; } = string.Empty;
    }
}