// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale de l'application console.
//         - 2026-09-25 : Câblage final avec l'orchestrateur et gestion IoC (J6-S2-T3 - Phase Bleue).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.IO;
using System.Threading.Tasks;
using Catamailer.Migrator.Orchestration;
using Microsoft.Extensions.DependencyInjection;

namespace Catamailer.Migrator
{
    /// <summary>
    /// Point d'entrée de l'outil de migration en ligne de commande.
    /// </summary>
    public class Program
    {
        /// <summary>
        /// Méthode principale exécutant la migration.
        /// </summary>
        /// <param name="args">Arguments de la ligne de commande. Attend le chemin du fichier CSV en premier argument.</param>
        /// <returns>0 en cas de succès, 1 ou -1 en cas d'erreur.</returns>
        public static async Task<int> Main(string[] args)
        {
            if (args.Length == 0)
            {
                Console.WriteLine("Usage: Catamailer.Migrator <chemin_vers_Configuration_Regles.csv>");
                return 1;
            }

            var csvFilePath = args[0];
            var dbFilePath = Path.Combine(Directory.GetCurrentDirectory(), "catamailer.db");

            try
            {
                Console.WriteLine("========================================");
                Console.WriteLine("  Catamailer - Outil de Migration CSV   ");
                Console.WriteLine("========================================");
                Console.WriteLine($"[INFO] Fichier source : {csvFilePath}");
                Console.WriteLine($"[INFO] Base de données cible : {dbFilePath}");
                Console.WriteLine("[INFO] Démarrage de la migration...");

                var services = new ServiceCollection();
                services.AddMigratorServices(dbFilePath);

                using var provider = services.BuildServiceProvider();
                
                var orchestrator = provider.GetRequiredService<IMigrationOrchestrator>();
                await orchestrator.MigrateAsync(csvFilePath);

                Console.WriteLine("[SUCCES] Migration terminée avec succès !");
                return 0;
            }
            catch (Exception ex)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine($"[ERREUR] Une exception s'est produite lors de la migration :");
                Console.WriteLine(ex.Message);
                Console.ResetColor();
                return -1;
            }
        }
    }
}