// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-25
//     Historique :
//         - 2026-09-25 : Création de la classe d'extension bouchonnée (J6-S2-T3 - Phase Rouge).
//         - 2026-09-25 : Implémentation de l'enregistrement des services (J6-S2-T3 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using Catamailer.Infrastructure;
using Catamailer.Migrator.Mapping;
using Catamailer.Migrator.Orchestration;
using Catamailer.Migrator.Parsing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Catamailer.Migrator
{
    /// <summary>
    /// Fournit des méthodes d'extension pour configurer l'injection de dépendances du Migrator.
    /// </summary>
    public static class ServiceCollectionExtensions
    {
        /// <summary>
        /// Enregistre l'ensemble des services nécessaires à l'exécution de la migration CSV.
        /// </summary>
        /// <param name="services">La collection de services.</param>
        /// <param name="dbFilePath">Le chemin vers le fichier de base de données SQLite cible.</param>
        /// <returns>La collection de services mise à jour.</returns>
        public static IServiceCollection AddMigratorServices(this IServiceCollection services, string dbFilePath)
        {
            // Enregistrement du contexte de base de données SQLite
            services.AddDbContext<CatamailerDbContext>(options =>
                options.UseSqlite($"Data Source={dbFilePath}"));

            // Enregistrement des composants de la chaîne de migration
            services.AddTransient<ICsvParser, CsvParser>();
            services.AddTransient<IRuleMapper, RuleMapper>();
            services.AddTransient<IMigrationOrchestrator, MigrationOrchestrator>();

            return services;
        }
    }
}