// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale des tests pour ActivationPromptViewModel (J3-S3-T5 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Threading.Tasks;
using Catamailer.Application.ViewModels;
using Catamailer.Domain;
using Xunit;

namespace Catamailer.Application.Tests.ViewModels
{
    public class ActivationPromptViewModelTests
    {
        private class FakeShadowModeService : IShadowModeService
        {
            public bool ShouldPrompt { get; set; }
            public bool AutoWriteEnabled { get; private set; }
            public bool Acknowledged { get; private set; }

            public Task<bool> ShouldPromptForActivationAsync() => Task.FromResult(ShouldPrompt);

            public Task SetAutoWriteEnabledAsync(bool enabled)
            {
                AutoWriteEnabled = enabled;
                return Task.CompletedTask;
            }

            public Task AcknowledgeActivationPromptAsync()
            {
                Acknowledged = true;
                return Task.CompletedTask;
            }

            // Membres non utilisés dans ce ViewModel
            public Task RecordPredictionAsync(string entryId, string predictedCategory, string actualCategory) => throw new NotImplementedException();
            public Task<bool> IsAutoWriteEnabledAsync() => throw new NotImplementedException();
            public Task<(int MatchCount, int CategoryCount, bool IsAutoWriteEnabled)> GetTelemetryStatsAsync() => throw new NotImplementedException();
        }

        [Fact]
        public async Task InitializeAsync_ShouldSetShouldShowPrompt_WhenServiceReturnsTrue()
        {
            // Arrange
            var fakeService = new FakeShadowModeService { ShouldPrompt = true };
            var viewModel = new ActivationPromptViewModel(fakeService);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.True(viewModel.ShouldShowPrompt);
        }

        [Fact]
        public async Task InitializeAsync_ShouldNotSetShouldShowPrompt_WhenServiceReturnsFalse()
        {
            // Arrange
            var fakeService = new FakeShadowModeService { ShouldPrompt = false };
            var viewModel = new ActivationPromptViewModel(fakeService);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.False(viewModel.ShouldShowPrompt);
        }

        [Fact]
        public async Task ActivateAsync_ShouldEnableAutoWrite_AndHidePrompt()
        {
            // Arrange
            var fakeService = new FakeShadowModeService { ShouldPrompt = true };
            var viewModel = new ActivationPromptViewModel(fakeService);
            await viewModel.InitializeAsync();

            // Act
            await viewModel.ActivateAsync();

            // Assert
            Assert.True(fakeService.AutoWriteEnabled);
            Assert.False(viewModel.ShouldShowPrompt);
        }

        [Fact]
        public async Task AcknowledgeAsync_ShouldAcknowledgePrompt_AndHidePrompt()
        {
            // Arrange
            var fakeService = new FakeShadowModeService { ShouldPrompt = true };
            var viewModel = new ActivationPromptViewModel(fakeService);
            await viewModel.InitializeAsync();

            // Act
            await viewModel.AcknowledgeAsync();

            // Assert
            Assert.True(fakeService.Acknowledged);
            Assert.False(viewModel.ShouldShowPrompt);
        }
    }
}