#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale des tests pour CategorySyncViewModel (J4-S2-T1).
//         - 2026-09-16 : Mise à jour suite au changement de signature du Domain et séparateur dynamique (J4-S4-T2).
//         - 2026-09-17 : Ajustement signature isImplicit (J4-S4-T2 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Linq;
using System.Threading.Tasks;
using Catamailer.Application.Services;
using Catamailer.Application.ViewModels;
using Catamailer.Domain;
using Catamailer.Domain.Sync;
using Moq;
using Xunit;

namespace Catamailer.Application.Tests.ViewModels
{
    public class CategorySyncViewModelTests
    {
        private readonly Mock<ICategorySyncService> _syncServiceMock;
        private readonly Mock<ICategoryRepository> _categoryRepositoryMock;
        private readonly Mock<ICategoryManagerProvider> _outlookProviderMock;
        private readonly CategorySyncViewModel _sut;

        public CategorySyncViewModelTests()
        {
            _syncServiceMock = new Mock<ICategorySyncService>();
            _categoryRepositoryMock = new Mock<ICategoryRepository>();
            _outlookProviderMock = new Mock<ICategoryManagerProvider>();

            _sut = new CategorySyncViewModel(
                _syncServiceMock.Object,
                _categoryRepositoryMock.Object,
                _outlookProviderMock.Object);
        }

        [Fact]
        public async Task InitializeAsync_ShouldPopulateOptions_WhenConflictsExist()
        {
            // Arrange
            var syncResult = new SyncResult();
            syncResult.AddDelta(CategoryDelta.CreateMissingInCatamailer("Cat1", "#000000", "#000000", false));
            syncResult.AddDelta(CategoryDelta.CreateMissingInOutlook("Cat2", "#FFFFFF"));
            syncResult.AddDelta(CategoryDelta.CreateColorMismatch("Cat3", "#111111", "#222222"));

            _syncServiceMock.Setup(s => s.AnalyzeSyncDeltasAsync(It.IsAny<string?>())).ReturnsAsync(syncResult);

            // Act
            await _sut.InitializeAsync();

            // Assert
            Assert.True(_sut.HasConflicts);
            Assert.Single(_sut.MissingInCatamailerOptions);
            Assert.Single(_sut.MissingInOutlookOptions);
            Assert.Single(_sut.ColorMismatchOptions);
            
            Assert.True(_sut.MissingInCatamailerOptions.First().IsSelected);
        }

        [Fact]
        public async Task ApplyResolutionsAsync_ShouldAddMissingInCatamailer_WhenSelected()
        {
            // Arrange
            var syncResult = new SyncResult();
            syncResult.AddDelta(CategoryDelta.CreateMissingInCatamailer("Cat1", "#000000", "#000000", false));
            _syncServiceMock.Setup(s => s.AnalyzeSyncDeltasAsync(It.IsAny<string?>())).ReturnsAsync(syncResult);
            
            await _sut.InitializeAsync();

            // Act
            await _sut.ApplyResolutionsAsync();

            // Assert
            _categoryRepositoryMock.Verify(r => r.AddAsync(It.Is<CategoryNode>(c => c.Name == "Cat1" && c.EffectiveColor == "#000000")), Times.Once);
        }

        [Fact]
        public async Task ApplyResolutionsAsync_ShouldNotProcess_WhenNotSelected()
        {
            // Arrange
            var syncResult = new SyncResult();
            syncResult.AddDelta(CategoryDelta.CreateMissingInOutlook("Cat2", "#FFFFFF"));
            _syncServiceMock.Setup(s => s.AnalyzeSyncDeltasAsync(It.IsAny<string?>())).ReturnsAsync(syncResult);
            
            await _sut.InitializeAsync();
            
            // Act: l'utilisateur décoche l'option
            _sut.MissingInOutlookOptions.First().IsSelected = false;
            await _sut.ApplyResolutionsAsync();

            // Assert
            _outlookProviderMock.Verify(p => p.AddCategory(It.IsAny<string>(), It.IsAny<string>()), Times.Never);
        }

        [Fact]
        public async Task ApplyResolutionsAsync_ShouldPushCatamailerColorToOutlook_ForMismatches()
        {
            // Arrange
            var syncResult = new SyncResult();
            syncResult.AddDelta(CategoryDelta.CreateColorMismatch("Cat3", "#OUTLOOK", "#CATAMAILER"));
            _syncServiceMock.Setup(s => s.AnalyzeSyncDeltasAsync(It.IsAny<string?>())).ReturnsAsync(syncResult);
            
            await _sut.InitializeAsync();

            // Act
            await _sut.ApplyResolutionsAsync();

            // Assert
            _outlookProviderMock.Verify(p => p.UpdateCategoryColor("Cat3", "#CATAMAILER"), Times.Once);
        }
    }
}