// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-09
//     Historique :
//         - 2026-09-09 : Création initiale pour J3-S3-T2 (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Application.ViewModels;
using Catamailer.Domain;
using Moq;
using Xunit;

namespace Catamailer.Application.Tests.ViewModels
{
    /// <summary>
    /// Tests unitaires pour la classe CategoryTreeViewModel.
    /// </summary>
    public class CategoryTreeViewModelTests
    {
        [Fact]
        public async Task InitializeAsync_ShouldLoadOnlyRootCategories()
        {
            // Arrange
            var mockRepo = new Mock<ICategoryRepository>();
            
            var root1 = new CategoryNode("Root 1");
            var child1 = new CategoryNode("Child 1");
            root1.AddChild(child1); // Lie child1 à root1

            var root2 = new CategoryNode("Root 2");

            // Le repository renvoie la liste à plat de toutes les catégories en base
            mockRepo.Setup(r => r.GetAllAsync())
                    .ReturnsAsync(new List<CategoryNode> { root1, child1, root2 });

            var viewModel = new CategoryTreeViewModel(mockRepo.Object);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.NotNull(viewModel.RootCategories);
            Assert.Equal(2, viewModel.RootCategories.Count);
            
            // Vérifie que seuls les nœuds racines sont exposés au niveau supérieur
            Assert.Contains(viewModel.RootCategories, c => c.Name == "Root 1");
            Assert.Contains(viewModel.RootCategories, c => c.Name == "Root 2");
            Assert.DoesNotContain(viewModel.RootCategories, c => c.Name == "Child 1");
        }
    }
}