// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-11
//     Historique :
//         - 2026-09-11 : Création initiale et tests CRUD (J3-S3-T3-ST1).
//         - 2026-09-25 : Ajout du test de compatibilité pour Virtualization (J6-S3-T1 - Phase Rouge).
//         - 2026-09-25 : Suppression du using UI invalide (J6-S3-T1 - Phase Rouge Correction).
//         - 2026-09-25 : Ajout des tests pour le mode édition (J6-S3-T6 - Phase Rouge).
//         - 2026-09-25 : Ajout des tests pour la recherche multi-critères (J6-S3-T2 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Application.ViewModels;
using Catamailer.Domain;
using Moq;
using Xunit;

namespace Catamailer.Application.Tests.ViewModels
{
    public class DictionaryEditorViewModelTests
    {
        [Fact]
        public async Task InitializeAsync_ShouldLoadDictionaryRules_FromRepository()
        {
            // Arrange
            var mockRuleRepo = new Mock<IRuleRepository>();
            var mockCatRepo = new Mock<ICategoryRepository>();
            
            var category = new CategoryNode("TestCategory");
            var rule = new DictionaryRule(category, new[] { "Keyword1" });
            
            mockRuleRepo.Setup(r => r.GetAllDictionaryRulesAsync())
                .ReturnsAsync(new List<DictionaryRule> { rule });
            mockCatRepo.Setup(r => r.GetAllAsync(It.IsAny<bool>()))
                .ReturnsAsync(new List<CategoryNode> { category });

            var viewModel = new DictionaryEditorViewModel(mockRuleRepo.Object, mockCatRepo.Object);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.Single(viewModel.Rules);
            Assert.Equal("TestCategory", viewModel.Rules.First().TargetCategory.Name);
        }

        [Fact]
        public async Task AddRuleAsync_ShouldCallRepository_AndRefreshList()
        {
            // Arrange
            var mockRuleRepo = new Mock<IRuleRepository>();
            var mockCatRepo = new Mock<ICategoryRepository>();
            var viewModel = new DictionaryEditorViewModel(mockRuleRepo.Object, mockCatRepo.Object);
            
            var category = new CategoryNode("NewCategory");
            var rule = new DictionaryRule(category, new[] { "NewKeyword" });

            // Act
            await viewModel.AddRuleAsync(rule);

            // Assert
            mockRuleRepo.Verify(r => r.AddDictionaryRuleAsync(rule), Times.Once);
            Assert.Single(viewModel.Rules);
            Assert.Contains(rule, viewModel.Rules);
        }

        [Fact]
        public async Task DeleteRuleAsync_ShouldCallRepository_AndRefreshList()
        {
            // Arrange
            var mockRuleRepo = new Mock<IRuleRepository>();
            var mockCatRepo = new Mock<ICategoryRepository>();
            
            var category = new CategoryNode("TestCategory");
            var rule = new DictionaryRule(category, new[] { "Keyword" });
            
            mockRuleRepo.Setup(r => r.GetAllDictionaryRulesAsync())
                .ReturnsAsync(new List<DictionaryRule> { rule });

            var viewModel = new DictionaryEditorViewModel(mockRuleRepo.Object, mockCatRepo.Object);
            await viewModel.InitializeAsync();

            // Act
            await viewModel.DeleteRuleAsync(rule);

            // Assert
            mockRuleRepo.Verify(r => r.DeleteDictionaryRuleAsync(rule), Times.Once);
            Assert.Empty(viewModel.Rules);
        }

        [Fact]
        public async Task InitializeAsync_ShouldLoadCategories_FromCategoryRepository()
        {
            // Arrange
            var mockRuleRepo = new Mock<IRuleRepository>();
            var mockCatRepo = new Mock<ICategoryRepository>();
            
            var category = new CategoryNode("TestCategory");
            
            mockCatRepo.Setup(r => r.GetAllAsync(It.IsAny<bool>()))
                .ReturnsAsync(new List<CategoryNode> { category });

            var viewModel = new DictionaryEditorViewModel(mockRuleRepo.Object, mockCatRepo.Object);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.Single(viewModel.AvailableCategories);
            Assert.Equal("TestCategory", viewModel.AvailableCategories.First().Name);
        }

        [Fact]
        public async Task CreateRuleFromFormAsync_ShouldAddRule_AndClearForm_WhenValid()
        {
            // Arrange
            var mockRuleRepo = new Mock<IRuleRepository>();
            var mockCatRepo = new Mock<ICategoryRepository>();
            
            var category = new CategoryNode("TestCategory");
            
            mockCatRepo.Setup(r => r.GetAllAsync(It.IsAny<bool>()))
                .ReturnsAsync(new List<CategoryNode> { category });

            var viewModel = new DictionaryEditorViewModel(mockRuleRepo.Object, mockCatRepo.Object);
            await viewModel.InitializeAsync();

            // Act
            viewModel.SelectedCategory = category;
            viewModel.SubjectKeywordsInput = " keyword1 , keyword2 ";
            viewModel.SenderKeywordsInput = "boss@corp.com";
            
            await viewModel.CreateRuleFromFormAsync();

            // Assert
            mockRuleRepo.Verify(r => r.AddDictionaryRuleAsync(It.Is<DictionaryRule>(rule => 
                rule.TargetCategory == category &&
                rule.SubjectKeywords.Count == 2 &&
                rule.SubjectKeywords.Contains("keyword1") &&
                rule.SubjectKeywords.Contains("keyword2") &&
                rule.SenderKeywords.Count == 1 &&
                rule.SenderKeywords.Contains("boss@corp.com")
            )), Times.Once);

            Assert.Null(viewModel.SelectedCategory);
            Assert.Empty(viewModel.SubjectKeywordsInput);
            Assert.Empty(viewModel.SenderKeywordsInput);
        }

        [Fact]
        public async Task RulesCollection_ShouldBeCompatibleWithVirtualization()
        {
            // Arrange
            var mockRuleRepo = new Mock<IRuleRepository>();
            var mockCatRepo = new Mock<ICategoryRepository>();

            var rules = new List<DictionaryRule>();
            for (int i = 0; i < 1000; i++)
            {
                rules.Add(new DictionaryRule(new CategoryNode($"Cat{i}")));
            }

            mockRuleRepo.Setup(r => r.GetAllDictionaryRulesAsync()).ReturnsAsync(rules);
            var viewModel = new DictionaryEditorViewModel(mockRuleRepo.Object, mockCatRepo.Object);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.IsAssignableFrom<ICollection<DictionaryRule>>(viewModel.Rules);
        }

        [Fact]
        public async Task EditRule_ShouldPopulateForm_AndSetIsEditing()
        {
            // Arrange
            var mockRuleRepo = new Mock<IRuleRepository>();
            var mockCatRepo = new Mock<ICategoryRepository>();
            
            var category = new CategoryNode("TestCategory");
            var rule = new DictionaryRule(category, new[] { "urgent", "test" }, new[] { "boss@corp.com" }, System.Array.Empty<string>());
            
            mockCatRepo.Setup(r => r.GetAllAsync(It.IsAny<bool>()))
                .ReturnsAsync(new List<CategoryNode> { category });

            var viewModel = new DictionaryEditorViewModel(mockRuleRepo.Object, mockCatRepo.Object);
            await viewModel.InitializeAsync();

            // Act
            viewModel.EditRule(rule);

            // Assert
            Assert.True(viewModel.IsEditing);
            Assert.Same(rule, viewModel.EditingRule);
            Assert.Same(category, viewModel.SelectedCategory);
            Assert.Equal("urgent, test", viewModel.SubjectKeywordsInput);
            Assert.Equal("boss@corp.com", viewModel.SenderKeywordsInput);
            Assert.Empty(viewModel.RecipientKeywordsInput);
        }

        [Fact]
        public void CancelEdit_ShouldClearForm_AndResetIsEditing()
        {
            // Arrange
            var mockRuleRepo = new Mock<IRuleRepository>();
            var mockCatRepo = new Mock<ICategoryRepository>();
            var viewModel = new DictionaryEditorViewModel(mockRuleRepo.Object, mockCatRepo.Object);
            
            viewModel.EditRule(new DictionaryRule(new CategoryNode("Test")));

            // Act
            viewModel.CancelEdit();

            // Assert
            Assert.False(viewModel.IsEditing);
            Assert.Null(viewModel.EditingRule);
            Assert.Null(viewModel.SelectedCategory);
            Assert.Empty(viewModel.SubjectKeywordsInput);
        }

        [Fact]
        public async Task UpdateRuleFromFormAsync_ShouldCallRepository_AndClearForm_WhenValid()
        {
            // Arrange
            var mockRuleRepo = new Mock<IRuleRepository>();
            var mockCatRepo = new Mock<ICategoryRepository>();
            
            var oldCategory = new CategoryNode("OldCategory");
            var newCategory = new CategoryNode("NewCategory");
            var rule = new DictionaryRule(oldCategory, new[] { "oldKeyword" });
            
            mockCatRepo.Setup(r => r.GetAllAsync(It.IsAny<bool>()))
                .ReturnsAsync(new List<CategoryNode> { oldCategory, newCategory });

            var viewModel = new DictionaryEditorViewModel(mockRuleRepo.Object, mockCatRepo.Object);
            await viewModel.InitializeAsync();
            viewModel.EditRule(rule);

            // Act
            viewModel.SelectedCategory = newCategory;
            viewModel.SubjectKeywordsInput = "newKeyword1, newKeyword2";
            
            await viewModel.UpdateRuleFromFormAsync();

            // Assert
            mockRuleRepo.Verify(r => r.UpdateDictionaryRuleAsync(It.Is<DictionaryRule>(r => 
                r.TargetCategory == newCategory &&
                r.SubjectKeywords.Count == 2 &&
                r.SubjectKeywords.Contains("newKeyword1") &&
                r.SubjectKeywords.Contains("newKeyword2")
            )), Times.Once);

            Assert.False(viewModel.IsEditing);
            Assert.Null(viewModel.EditingRule);
            Assert.Null(viewModel.SelectedCategory);
            Assert.Empty(viewModel.SubjectKeywordsInput);
        }

        [Fact]
        public async Task FilteredRules_ShouldReturnAllRules_WhenSearchTextIsEmpty()
        {
            // Arrange
            var mockRuleRepo = new Mock<IRuleRepository>();
            var mockCatRepo = new Mock<ICategoryRepository>();
            
            var rules = new List<DictionaryRule>
            {
                new DictionaryRule(new CategoryNode("CatA"), new[] { "key1" }),
                new DictionaryRule(new CategoryNode("CatB"), new[] { "key2" })
            };
            
            mockRuleRepo.Setup(r => r.GetAllDictionaryRulesAsync()).ReturnsAsync(rules);
            var viewModel = new DictionaryEditorViewModel(mockRuleRepo.Object, mockCatRepo.Object);
            await viewModel.InitializeAsync();

            // Act
            viewModel.SearchText = "   ";

            // Assert
            Assert.Equal(2, viewModel.FilteredRules.Count);
        }

        [Fact]
        public async Task FilteredRules_ShouldFilterByCategoryOrKeywords_IgnoringCase()
        {
            // Arrange
            var mockRuleRepo = new Mock<IRuleRepository>();
            var mockCatRepo = new Mock<ICategoryRepository>();
            
            var rules = new List<DictionaryRule>
            {
                new DictionaryRule(new CategoryNode("Finance"), new[] { "facture", "devis" }),
                new DictionaryRule(new CategoryNode("RH"), null, new[] { "boss@corp.com" }),
                new DictionaryRule(new CategoryNode("IT"), null, null, new[] { "support@corp.com" })
            };
            
            mockRuleRepo.Setup(r => r.GetAllDictionaryRulesAsync()).ReturnsAsync(rules);
            var viewModel = new DictionaryEditorViewModel(mockRuleRepo.Object, mockCatRepo.Object);
            await viewModel.InitializeAsync();

            // Act & Assert
            // Recherche par catégorie (insensible à la casse)
            viewModel.SearchText = "fIna";
            Assert.Single(viewModel.FilteredRules);
            Assert.Equal("Finance", viewModel.FilteredRules.First().TargetCategory.Name);

            // Recherche par mot-clé sujet
            viewModel.SearchText = "FACT";
            Assert.Single(viewModel.FilteredRules);
            Assert.Equal("Finance", viewModel.FilteredRules.First().TargetCategory.Name);

            // Recherche par mot-clé expéditeur
            viewModel.SearchText = "BOSS";
            Assert.Single(viewModel.FilteredRules);
            Assert.Equal("RH", viewModel.FilteredRules.First().TargetCategory.Name);

            // Recherche par mot-clé destinataire
            viewModel.SearchText = "SUPPORT";
            Assert.Single(viewModel.FilteredRules);
            Assert.Equal("IT", viewModel.FilteredRules.First().TargetCategory.Name);
        }
    }
}