// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-11
//     Historique :
//         - 2026-09-11 : Création initiale des tests pour DictionaryEditorViewModel (J3-S3-T3-ST1 - Phase Rouge).
//         - 2026-09-11 : Ajout des tests pour le formulaire de création et l'injection de ICategoryRepository (Phase Orange/Rouge).
//         - 2026-09-11 : Ajout des tests pour les champs Expéditeur et Destinataire (Phase Orange/Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Application.ViewModels;
using Catamailer.Domain;
using Xunit;

namespace Catamailer.Application.Tests.ViewModels
{
    public class DictionaryEditorViewModelTests
    {
        private class FakeRuleRepository : IRuleRepository
        {
            public List<DictionaryRule> Rules = new();
            public bool AddCalled = false;
            public bool DeleteCalled = false;

            public Task<IEnumerable<DictionaryRule>> GetAllDictionaryRulesAsync()
            {
                return Task.FromResult<IEnumerable<DictionaryRule>>(Rules);
            }

            public Task AddDictionaryRuleAsync(DictionaryRule rule)
            {
                AddCalled = true;
                Rules.Add(rule);
                return Task.CompletedTask;
            }

            public Task DeleteDictionaryRuleAsync(DictionaryRule rule)
            {
                DeleteCalled = true;
                Rules.Remove(rule);
                return Task.CompletedTask;
            }
        }

        private class FakeCategoryRepository : ICategoryRepository
        {
            public Task AddAsync(CategoryNode category) => Task.CompletedTask;
            public Task<CategoryNode?> GetByNameAsync(string name) => Task.FromResult<CategoryNode?>(null);
            
            public Task<IEnumerable<CategoryNode>> GetAllAsync()
            {
                return Task.FromResult<IEnumerable<CategoryNode>>(new[] 
                { 
                    new CategoryNode("Test Category") 
                });
            }
        }

        [Fact]
        public async Task InitializeAsync_ShouldLoadDictionaryRules_FromRepository()
        {
            // Arrange
            var fakeRepo = new FakeRuleRepository();
            var fakeCatRepo = new FakeCategoryRepository();
            var category = new CategoryNode("Test Category");
            fakeRepo.Rules.Add(new DictionaryRule(category, subjectKeywords: new[] { "keyword" }));
            var viewModel = new DictionaryEditorViewModel(fakeRepo, fakeCatRepo);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.Single(viewModel.Rules);
            Assert.Equal("Test Category", viewModel.Rules.First().TargetCategory.Name);
        }

        [Fact]
        public async Task AddRuleAsync_ShouldCallRepository_AndRefreshList()
        {
            // Arrange
            var fakeRepo = new FakeRuleRepository();
            var fakeCatRepo = new FakeCategoryRepository();
            var viewModel = new DictionaryEditorViewModel(fakeRepo, fakeCatRepo);
            var category = new CategoryNode("New Category");
            var newRule = new DictionaryRule(category, subjectKeywords: new[] { "urgent" });

            // Act
            await viewModel.AddRuleAsync(newRule);

            // Assert
            Assert.True(fakeRepo.AddCalled);
            Assert.Single(viewModel.Rules);
            Assert.Contains(viewModel.Rules, r => r.TargetCategory.Name == "New Category");
        }

        [Fact]
        public async Task DeleteRuleAsync_ShouldCallRepository_AndRefreshList()
        {
            // Arrange
            var fakeRepo = new FakeRuleRepository();
            var fakeCatRepo = new FakeCategoryRepository();
            var category = new CategoryNode("To Delete");
            var ruleToDelete = new DictionaryRule(category, subjectKeywords: new[] { "delete_me" });
            fakeRepo.Rules.Add(ruleToDelete);
            
            var viewModel = new DictionaryEditorViewModel(fakeRepo, fakeCatRepo);
            await viewModel.InitializeAsync();

            // Act
            await viewModel.DeleteRuleAsync(ruleToDelete);

            // Assert
            Assert.True(fakeRepo.DeleteCalled);
            Assert.Empty(viewModel.Rules);
        }

        [Fact]
        public async Task InitializeAsync_ShouldLoadCategories_FromCategoryRepository()
        {
            // Arrange
            var fakeRepo = new FakeRuleRepository();
            var fakeCatRepo = new FakeCategoryRepository();
            var viewModel = new DictionaryEditorViewModel(fakeRepo, fakeCatRepo);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.Single(viewModel.AvailableCategories);
            Assert.Equal("Test Category", viewModel.AvailableCategories.First().Name);
        }

        [Fact]
        public async Task CreateRuleFromFormAsync_ShouldAddRule_AndClearForm_WhenValid()
        {
            // Arrange
            var fakeRepo = new FakeRuleRepository();
            var fakeCatRepo = new FakeCategoryRepository();
            var viewModel = new DictionaryEditorViewModel(fakeRepo, fakeCatRepo);
            await viewModel.InitializeAsync();

            viewModel.SelectedCategory = viewModel.AvailableCategories.First();
            viewModel.SubjectKeywordsInput = "urgent, important";
            viewModel.SenderKeywordsInput = "boss@company.com";
            viewModel.RecipientKeywordsInput = "team@company.com";
            
            // Act
            await viewModel.CreateRuleFromFormAsync();

            // Assert
            Assert.True(fakeRepo.AddCalled);
            Assert.Single(viewModel.Rules);
            var rule = viewModel.Rules.First();
            
            Assert.Equal("Test Category", rule.TargetCategory.Name);
            Assert.Contains("urgent", rule.SubjectKeywords);
            Assert.Contains("important", rule.SubjectKeywords);
            Assert.Contains("boss@company.com", rule.SenderKeywords);
            Assert.Contains("team@company.com", rule.RecipientKeywords);

            // Check if form is cleared
            Assert.Null(viewModel.SelectedCategory);
            Assert.Empty(viewModel.SubjectKeywordsInput);
            Assert.Empty(viewModel.SenderKeywordsInput);
            Assert.Empty(viewModel.RecipientKeywordsInput);
        }
    }
}