// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-15
//     Historique :
//         - 2026-09-15 : Création initiale des tests pour PreferencesViewModel (J3-S3-T4 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Threading.Tasks;
using Catamailer.Application.ViewModels;
using Catamailer.Domain;
using Xunit;

namespace Catamailer.Application.Tests.ViewModels
{
    public class PreferencesViewModelTests
    {
        private class FakeAppSettingsRepository : IAppSettingsRepository
        {
            private readonly Dictionary<string, string> _settings = new();

            public Task<string?> GetSettingAsync(string key)
            {
                _settings.TryGetValue(key, out var value);
                return Task.FromResult(value);
            }

            public Task SetSettingAsync(string key, string value)
            {
                _settings[key] = value;
                return Task.CompletedTask;
            }

            // Helper pour injecter des données dans le test
            public void InjectSetting(string key, string value)
            {
                _settings[key] = value;
            }
        }

        [Fact]
        public async Task InitializeAsync_ShouldLoadDebounceDelay_WhenSettingExists()
        {
            // Arrange
            var repo = new FakeAppSettingsRepository();
            repo.InjectSetting("HistoryDebounceDelayMinutes", "45");
            var viewModel = new PreferencesViewModel(repo);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.Equal(45, viewModel.DebounceDelayMinutes);
        }

        [Fact]
        public async Task InitializeAsync_ShouldSetDefaultDebounceDelay_WhenSettingDoesNotExist()
        {
            // Arrange
            var repo = new FakeAppSettingsRepository();
            var viewModel = new PreferencesViewModel(repo);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.Equal(30, viewModel.DebounceDelayMinutes); // 30 est la valeur par défaut métier
        }

        [Fact]
        public async Task SaveAsync_ShouldPersistDebounceDelayToRepository()
        {
            // Arrange
            var repo = new FakeAppSettingsRepository();
            var viewModel = new PreferencesViewModel(repo);
            await viewModel.InitializeAsync(); // Setup initial
            
            // Act
            viewModel.DebounceDelayMinutes = 60;
            await viewModel.SaveAsync();

            // Assert
            var savedValue = await repo.GetSettingAsync("HistoryDebounceDelayMinutes");
            Assert.Equal("60", savedValue);
        }
    }
}