// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-11
//     Historique :
//         - 2026-09-11 : Création initiale des tests pour RuleBuilderViewModel (J3-S3-T3-ST2).
//         - 2026-09-11 : Ajout des tests pour la mutation (J3-S3-T3-ST2).
//         - 2026-09-11 : Ajout du test SaveRuleAsync et de l'injection du repository (J3-S3-T3-ST2).
//         - 2026-09-11 : Ajout du test d'initialisation des catégories (J3-S3-T3-ST2 - Phase Rouge).
//         - 2026-09-17 : Implémentation de UpdateAsync dans FakeCategoryRepository (J4-S4-T4 - Phase Verte).
//         - 2026-09-23 : Ajout des méthodes AddRangeAsync et UpdateRangeAsync dans FakeCategoryRepository (J4-S4-T7 - Phase Verte).
//         - 2026-09-23 : Mise à jour de GetAllAsync dans FakeCategoryRepository pour supporter includeDeleted (J4-S4-T6 - Phase Verte).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catamailer.Application.ViewModels;
using Catamailer.Domain;
using Xunit;

namespace Catamailer.Application.Tests.ViewModels
{
    public class RuleBuilderViewModelTests
    {
        private class FakeRuleRepository : IRuleRepository
        {
            public List<DictionaryRule> DictionaryRules { get; } = new();
            public List<ExecutionRule> ExecutionRules { get; } = new();

            public Task<IEnumerable<DictionaryRule>> GetAllDictionaryRulesAsync() => Task.FromResult(DictionaryRules.AsEnumerable());
            public Task AddDictionaryRuleAsync(DictionaryRule rule)
            {
                DictionaryRules.Add(rule);
                return Task.CompletedTask;
            }
            public Task DeleteDictionaryRuleAsync(DictionaryRule rule)
            {
                DictionaryRules.Remove(rule);
                return Task.CompletedTask;
            }

            public Task<IEnumerable<ExecutionRule>> GetAllExecutionRulesAsync() => Task.FromResult(ExecutionRules.AsEnumerable());
            public Task AddExecutionRuleAsync(ExecutionRule rule)
            {
                ExecutionRules.Add(rule);
                return Task.CompletedTask;
            }
            public Task DeleteExecutionRuleAsync(ExecutionRule rule)
            {
                ExecutionRules.Remove(rule);
                return Task.CompletedTask;
            }
        }

        private class FakeCategoryRepository : ICategoryRepository
        {
            public Task AddAsync(CategoryNode category) => Task.CompletedTask;
            public Task AddRangeAsync(IEnumerable<CategoryNode> categories) => Task.CompletedTask;
            public Task UpdateAsync(CategoryNode category) => Task.CompletedTask;
            public Task UpdateRangeAsync(IEnumerable<CategoryNode> categories) => Task.CompletedTask;
            public Task<CategoryNode?> GetByNameAsync(string name) => Task.FromResult<CategoryNode?>(null);
            
            public Task<IEnumerable<CategoryNode>> GetAllAsync(bool includeDeleted = false)
            {
                return Task.FromResult<IEnumerable<CategoryNode>>(new[] 
                { 
                    new CategoryNode("Test Category 1"),
                    new CategoryNode("Test Category 2")
                });
            }
        }

        [Fact]
        public void Constructor_ShouldInitializeRootNode()
        {
            // Arrange & Act
            var repo = new FakeRuleRepository();
            var catRepo = new FakeCategoryRepository();
            var viewModel = new RuleBuilderViewModel(repo, catRepo);

            // Assert
            Assert.NotNull(viewModel.RootNode);
            Assert.Equal(LogicalOperator.And, viewModel.RootNode.Operator);
            Assert.Null(viewModel.FinalAction);
            Assert.Empty(viewModel.RuleName);
            Assert.Empty(viewModel.AvailableCategories);
        }

        [Fact]
        public async Task InitializeAsync_ShouldLoadCategories_FromCategoryRepository()
        {
            // Arrange
            var repo = new FakeRuleRepository();
            var catRepo = new FakeCategoryRepository();
            var viewModel = new RuleBuilderViewModel(repo, catRepo);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.Equal(2, viewModel.AvailableCategories.Count());
            Assert.Equal("Test Category 1", viewModel.AvailableCategories.First().Name);
        }

        [Fact]
        public void AddCriterion_ShouldAddCriterionToTargetNode()
        {
            // Arrange
            var repo = new FakeRuleRepository();
            var catRepo = new FakeCategoryRepository();
            var viewModel = new RuleBuilderViewModel(repo, catRepo);
            var criterion = new RuleCriterion(MailField.Subject, MatchOperator.Contains, "test");
            
            // Act
            viewModel.AddCriterion(viewModel.RootNode, criterion);

            // Assert
            Assert.Single(viewModel.RootNode.Criteria);
            Assert.Equal("test", viewModel.RootNode.Criteria.First().Value);
        }

        [Fact]
        public void RemoveCriterion_ShouldRemoveCriterionFromTargetNode()
        {
            // Arrange
            var repo = new FakeRuleRepository();
            var catRepo = new FakeCategoryRepository();
            var viewModel = new RuleBuilderViewModel(repo, catRepo);
            var criterion = new RuleCriterion(MailField.Subject, MatchOperator.Contains, "test");
            viewModel.AddCriterion(viewModel.RootNode, criterion);
            
            // Act
            viewModel.RemoveCriterion(viewModel.RootNode, criterion);

            // Assert
            Assert.Empty(viewModel.RootNode.Criteria);
        }

        [Fact]
        public void AddChildNode_ShouldAddNodeToTargetNode()
        {
            // Arrange
            var repo = new FakeRuleRepository();
            var catRepo = new FakeCategoryRepository();
            var viewModel = new RuleBuilderViewModel(repo, catRepo);
            var child = new RuleNode(LogicalOperator.Or);
            
            // Act
            viewModel.AddChildNode(viewModel.RootNode, child);

            // Assert
            Assert.Single(viewModel.RootNode.ChildNodes);
            Assert.Equal(LogicalOperator.Or, viewModel.RootNode.ChildNodes.First().Operator);
        }

        [Fact]
        public void SetAction_ShouldUpdateFinalActionProperty()
        {
            // Arrange
            var repo = new FakeRuleRepository();
            var catRepo = new FakeCategoryRepository();
            var viewModel = new RuleBuilderViewModel(repo, catRepo);
            var action = new RuleAction(ActionType.MoveToFolder, "Archives");
            
            // Act
            viewModel.SetAction(action);

            // Assert
            Assert.NotNull(viewModel.FinalAction);
            Assert.Equal(ActionType.MoveToFolder, viewModel.FinalAction.Type);
            Assert.Equal("Archives", viewModel.FinalAction.Parameter);
        }

        [Fact]
        public void SetOperator_ShouldUpdateTargetNodeOperator()
        {
            // Arrange
            var repo = new FakeRuleRepository();
            var catRepo = new FakeCategoryRepository();
            var viewModel = new RuleBuilderViewModel(repo, catRepo);
            
            // Act
            viewModel.SetOperator(viewModel.RootNode, LogicalOperator.Or);

            // Assert
            Assert.Equal(LogicalOperator.Or, viewModel.RootNode.Operator);
        }

        [Fact]
        public void UpdateCriterion_ShouldReplaceCriterionInTargetNode()
        {
            // Arrange
            var repo = new FakeRuleRepository();
            var catRepo = new FakeCategoryRepository();
            var viewModel = new RuleBuilderViewModel(repo, catRepo);
            var oldCriterion = new RuleCriterion(MailField.Subject, MatchOperator.Contains, "old");
            var newCriterion = new RuleCriterion(MailField.Subject, MatchOperator.Contains, "new");
            viewModel.AddCriterion(viewModel.RootNode, oldCriterion);
            
            // Act
            viewModel.UpdateCriterion(viewModel.RootNode, oldCriterion, newCriterion);

            // Assert
            Assert.Single(viewModel.RootNode.Criteria);
            Assert.Equal("new", viewModel.RootNode.Criteria.First().Value);
            Assert.DoesNotContain(oldCriterion, viewModel.RootNode.Criteria);
        }

        [Fact]
        public async Task SaveRuleAsync_ShouldCallRepository_WhenNameAndActionAreSet()
        {
            // Arrange
            var repo = new FakeRuleRepository();
            var catRepo = new FakeCategoryRepository();
            var viewModel = new RuleBuilderViewModel(repo, catRepo)
            {
                RuleName = "Test Execution Rule"
            };
            viewModel.SetAction(new RuleAction(ActionType.MoveToFolder, "Inbox"));

            // Act
            await viewModel.SaveRuleAsync();

            // Assert
            Assert.Single(repo.ExecutionRules);
            Assert.Equal("Test Execution Rule", repo.ExecutionRules.First().Name);
        }
    }
}