// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-09
//     Historique :
//         - 2026-09-09 : Création initiale pour J3-S3-T1 (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;
using Catamailer.Application.ViewModels;
using Catamailer.Domain;
using Moq;
using Xunit;

namespace Catamailer.Application.Tests.ViewModels
{
    /// <summary>
    /// Tests unitaires pour la classe ShadowModeDashboardViewModel.
    /// </summary>
    public class ShadowModeDashboardViewModelTests
    {
        [Fact]
        public async Task InitializeAsync_ShouldLoadTelemetryStats_FromService()
        {
            // Arrange
            var mockService = new Mock<IShadowModeService>();
            mockService.Setup(s => s.GetTelemetryStatsAsync())
                       .ReturnsAsync((MatchCount: 150, CategoryCount: 10, IsAutoWriteEnabled: false));

            var viewModel = new ShadowModeDashboardViewModel(mockService.Object);

            // Act
            await viewModel.InitializeAsync();

            // Assert
            Assert.Equal(150, viewModel.MatchCount);
            Assert.Equal(10, viewModel.CategoryCount);
            Assert.False(viewModel.IsAutoWriteEnabled);
        }

        [Fact]
        public async Task ToggleAutoWriteAsync_ShouldUpdateService_AndRefreshStats()
        {
            // Arrange
            var mockService = new Mock<IShadowModeService>();
            
            // Le service retourne 'false' initialement
            mockService.SetupSequence(s => s.GetTelemetryStatsAsync())
                       .ReturnsAsync((MatchCount: 150, CategoryCount: 10, IsAutoWriteEnabled: false))
                       .ReturnsAsync((MatchCount: 150, CategoryCount: 10, IsAutoWriteEnabled: true)); // Puis 'true' après le toggle

            var viewModel = new ShadowModeDashboardViewModel(mockService.Object);
            await viewModel.InitializeAsync();

            // Act
            await viewModel.ToggleAutoWriteAsync(true);

            // Assert
            mockService.Verify(s => s.SetAutoWriteEnabledAsync(true), Times.Once);
            Assert.True(viewModel.IsAutoWriteEnabled); // Vérifie que le ViewModel s'est bien rechargé
        }
    }
}