// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale pour J2-S2-T2 (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Threading.Tasks;
using Catamailer.Application;
using Catamailer.Domain;
using Microsoft.Extensions.Time.Testing;
using Moq;
using Xunit;

namespace Catamailer.Application.Tests
{
    /// <summary>
    /// Classe de tests validant le comportement du service de Debounce de l'analyse d'historique.
    /// </summary>
    public class DebounceServiceTests
    {
        [Fact]
        public async Task IsAnalysisSuspendedAsync_ShouldReturnFalse_WhenNoSuspensionRecorded()
        {
            // Arrange
            var mockSettings = new Mock<IAppSettingsRepository>();
            var mockState = new Mock<IHistoryStateRepository>();
            var fakeTime = new FakeTimeProvider();

            mockState.Setup(s => s.GetStateAsync(DebounceService.SuspendedUntilStateKey))
                     .ReturnsAsync((string?)null);

            var service = new DebounceService(mockSettings.Object, mockState.Object, fakeTime);

            // Act
            var isSuspended = await service.IsAnalysisSuspendedAsync();

            // Assert
            Assert.False(isSuspended);
        }

        [Fact]
        public async Task SuspendAnalysisAsync_ShouldSaveTargetTimeBasedOnConfiguredDelay()
        {
            // Arrange
            var mockSettings = new Mock<IAppSettingsRepository>();
            var mockState = new Mock<IHistoryStateRepository>();
            var fakeTime = new FakeTimeProvider(new DateTimeOffset(2026, 9, 7, 10, 0, 0, TimeSpan.Zero));

            mockSettings.Setup(s => s.GetSettingAsync(DebounceService.DebounceSettingKey))
                        .ReturnsAsync("15");

            string? savedStateValue = null;
            mockState.Setup(s => s.SetStateAsync(DebounceService.SuspendedUntilStateKey, It.IsAny<string>()))
                     .Callback<string, string>((_, val) => savedStateValue = val)
                     .Returns(Task.CompletedTask);

            var service = new DebounceService(mockSettings.Object, mockState.Object, fakeTime);

            // Act
            await service.SuspendAnalysisAsync();

            // Assert
            Assert.NotNull(savedStateValue);
            var expectedTime = fakeTime.GetUtcNow().AddMinutes(15).ToString("o");
            Assert.Equal(expectedTime, savedStateValue);
        }

        [Fact]
        public async Task IsAnalysisSuspendedAsync_ShouldReturnFalse_WhenTimeHasPassed()
        {
            // Arrange
            var mockSettings = new Mock<IAppSettingsRepository>();
            var mockState = new Mock<IHistoryStateRepository>();
            var fakeTime = new FakeTimeProvider(new DateTimeOffset(2026, 9, 7, 10, 0, 0, TimeSpan.Zero));

            var pastTime = fakeTime.GetUtcNow().AddMinutes(-5).ToString("o");
            mockState.Setup(s => s.GetStateAsync(DebounceService.SuspendedUntilStateKey))
                     .ReturnsAsync(pastTime);

            var service = new DebounceService(mockSettings.Object, mockState.Object, fakeTime);

            // Act
            var isSuspended = await service.IsAnalysisSuspendedAsync();

            // Assert
            Assert.False(isSuspended);
        }
    }
}