// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale pour J2-S2-T3 (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;
using Catamailer.Application;
using Catamailer.Domain;
using Moq;
using Xunit;

namespace Catamailer.Application.Tests
{
    /// <summary>
    /// Classe de tests unitaires pour la tâche J2-S2-T3 (HistoryRunner).
    /// </summary>
    public class HistoryRunnerTests
    {
        [Fact]
        public async Task ProcessPendingHistoryAsync_ShouldReturnZero_WhenAnalysisIsSuspended()
        {
            // Arrange
            var mockDebounce = new Mock<IDebounceService>();
            var mockStateRepo = new Mock<IHistoryStateRepository>();

            mockDebounce.Setup(d => d.IsAnalysisSuspendedAsync()).ReturnsAsync(true);

            var runner = new HistoryRunner(mockDebounce.Object, mockStateRepo.Object);

            // Act
            var processedCount = await runner.ProcessPendingHistoryAsync(10);

            // Assert
            Assert.Equal(0, processedCount);
            mockStateRepo.Verify(s => s.GetStateAsync(It.IsAny<string>()), Times.Never);
        }

        [Fact]
        public async Task ProcessPendingHistoryAsync_ShouldFetchCursorAndProcess_WhenNotSuspended()
        {
            // Arrange
            var mockDebounce = new Mock<IDebounceService>();
            var mockStateRepo = new Mock<IHistoryStateRepository>();

            mockDebounce.Setup(d => d.IsAnalysisSuspendedAsync()).ReturnsAsync(false);
            mockStateRepo.Setup(s => s.GetStateAsync(HistoryRunner.LastEntryIdStateKey))
                         .ReturnsAsync("ENTRY-100");

            var runner = new HistoryRunner(mockDebounce.Object, mockStateRepo.Object);

            // Act
            var processedCount = await runner.ProcessPendingHistoryAsync(10);

            // Assert
            mockStateRepo.Verify(s => s.GetStateAsync(HistoryRunner.LastEntryIdStateKey), Times.Once);
        }
    }
}