// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale pour J2-S2-T4 (Phase Rouge).
//         - 2026-09-09 : Ajout des tests pour GetTelemetryStatsAsync (J3-S3-T1 - Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Threading.Tasks;
using Catamailer.Application;
using Catamailer.Domain;
using Moq;
using Xunit;

namespace Catamailer.Application.Tests
{
    /// <summary>
    /// Tests unitaires pour le service ShadowModeService.
    /// </summary>
    public class ShadowModeServiceTests
    {
        [Fact]
        public async Task IsAutoWriteEnabledAsync_ShouldReturnFalse_ByDefault()
        {
            // Arrange
            var mockSettings = new Mock<IAppSettingsRepository>();
            var mockState = new Mock<IHistoryStateRepository>();

            mockSettings.Setup(s => s.GetSettingAsync(ShadowModeService.AutoWriteSettingKey))
                        .ReturnsAsync((string?)null);

            var service = new ShadowModeService(mockSettings.Object, mockState.Object);

            // Act
            var isEnabled = await service.IsAutoWriteEnabledAsync();

            // Assert
            Assert.False(isEnabled);
        }

        [Fact]
        public async Task ShouldPromptForActivationAsync_ShouldReturnTrue_WhenPalierReached()
        {
            // Arrange
            var mockSettings = new Mock<IAppSettingsRepository>();
            var mockState = new Mock<IHistoryStateRepository>();

            mockSettings.Setup(s => s.GetSettingAsync(ShadowModeService.AutoWriteSettingKey))
                        .ReturnsAsync("false");

            mockState.Setup(s => s.GetStateAsync(ShadowModeService.MatchCountStateKey)).ReturnsAsync("300");
            mockState.Setup(s => s.GetStateAsync(ShadowModeService.CategoryCountStateKey)).ReturnsAsync("30");
            mockState.Setup(s => s.GetStateAsync(ShadowModeService.LastPromptMatchCountStateKey)).ReturnsAsync("0");

            var service = new ShadowModeService(mockSettings.Object, mockState.Object);

            // Act
            var shouldPrompt = await service.ShouldPromptForActivationAsync();

            // Assert
            Assert.True(shouldPrompt);
        }

        [Fact]
        public async Task ShouldPromptForActivationAsync_ShouldReturnFalse_WhenPromptAlreadyAcknowledgedForCurrentPalier()
        {
            // Arrange
            var mockSettings = new Mock<IAppSettingsRepository>();
            var mockState = new Mock<IHistoryStateRepository>();

            mockSettings.Setup(s => s.GetSettingAsync(ShadowModeService.AutoWriteSettingKey))
                        .ReturnsAsync("false");

            mockState.Setup(s => s.GetStateAsync(ShadowModeService.MatchCountStateKey)).ReturnsAsync("350");
            mockState.Setup(s => s.GetStateAsync(ShadowModeService.CategoryCountStateKey)).ReturnsAsync("30");
            mockState.Setup(s => s.GetStateAsync(ShadowModeService.LastPromptMatchCountStateKey)).ReturnsAsync("300");

            var service = new ShadowModeService(mockSettings.Object, mockState.Object);

            // Act
            var shouldPrompt = await service.ShouldPromptForActivationAsync();

            // Assert
            Assert.False(shouldPrompt);
        }

        [Fact]
        public async Task GetTelemetryStatsAsync_ShouldReturnParsedValues_FromRepositories()
        {
            // Arrange
            var mockSettings = new Mock<IAppSettingsRepository>();
            var mockState = new Mock<IHistoryStateRepository>();

            mockSettings.Setup(s => s.GetSettingAsync(ShadowModeService.AutoWriteSettingKey))
                        .ReturnsAsync("true");

            mockState.Setup(s => s.GetStateAsync(ShadowModeService.MatchCountStateKey))
                     .ReturnsAsync("420");
            mockState.Setup(s => s.GetStateAsync(ShadowModeService.CategoryCountStateKey))
                     .ReturnsAsync("15");

            var service = new ShadowModeService(mockSettings.Object, mockState.Object);

            // Act
            var stats = await service.GetTelemetryStatsAsync();

            // Assert
            Assert.Equal(420, stats.MatchCount);
            Assert.Equal(15, stats.CategoryCount);
            Assert.True(stats.IsAutoWriteEnabled);
        }
    }
}