// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-07 : Correction nullable (Phase Verte).
//         - 2026-09-09 : Adaptation à la refonte de MailMetadata (J3-S2-T2-ST1).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using Catamailer.Domain;
using Catamailer.Infrastructure;
using Moq;
using Xunit;

namespace Catamailer.Infrastructure.Tests
{
    /// <summary>
    /// Classe de tests validant le comportement du fournisseur Outlook COM.
    /// </summary>
    public class OutlookMailProviderTests
    {
        [Fact]
        public void StartListening_ShouldTriggerNewMailReceived_WhenOutlookRaisesNewMailEx()
        {
            // Arrange
            var mockWrapper = new Mock<IOutlookApplicationWrapper>();
            var expectedEntryId = "12345-ABCDE";
            var expectedMetadata = new MailMetadata(
                expectedEntryId, 
                "Test Subject", 
                "sender@test.com", 
                null,
                new List<string>(),
                new List<string> { "recipient@test.com" }
            );

            mockWrapper.Setup(w => w.GetMailMetadata(expectedEntryId)).Returns(expectedMetadata);

            var provider = new OutlookMailProvider(mockWrapper.Object);
            
            MailMetadata? receivedMetadata = null;
            provider.NewMailReceived += (sender, metadata) => receivedMetadata = metadata;

            // Act
            provider.StartListening();
            
            // Simulation du déclenchement de l'événement COM par Outlook
            mockWrapper.Raise(w => w.OnNewMailEx += null, expectedEntryId);

            // Assert
            Assert.NotNull(receivedMetadata);
            Assert.Equal(expectedEntryId, receivedMetadata!.EntryId);
            Assert.Equal("Test Subject", receivedMetadata.Subject);
            Assert.Equal("sender@test.com", receivedMetadata.Sender);
        }
    }
}