// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-15 : Ajout du test GetAllCategories_ShouldReturnMappedCategories_FromWrapper (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Linq;
using Catamailer.Infrastructure;
using Moq;
using Xunit;

namespace Catamailer.Infrastructure.Tests
{
    /// <summary>
    /// Classe de tests validant le comportement du gestionnaire de catégories Outlook.
    /// </summary>
    public class OutlookCategoryManagerProviderTests
    {
        [Fact]
        public void GetAllCategories_ShouldReturnMappedCategories_FromWrapper()
        {
            // Arrange
            var mockWrapper = new Mock<IOutlookApplicationWrapper>();
            var expectedCategories = new List<(string Name, string? ColorCode)>
            {
                ("Urba-Veille", "#FF0000"),
                ("Comitologie", "#00FF00")
            };
            mockWrapper.Setup(w => w.GetMasterCategories()).Returns(expectedCategories);

            var provider = new OutlookCategoryManagerProvider(mockWrapper.Object);

            // Act
            var result = provider.GetAllCategories().ToList();

            // Assert
            Assert.Equal(2, result.Count);
            Assert.Contains(result, c => c.Name == "Urba-Veille" && c.ColorCode == "#FF0000");
            Assert.Contains(result, c => c.Name == "Comitologie" && c.ColorCode == "#00FF00");
            mockWrapper.Verify(w => w.GetMasterCategories(), Times.Once);
        }

        [Fact]
        public void AddCategory_ShouldCallWrapperAdd_WhenCategoryDoesNotExist()
        {
            // Arrange
            var mockWrapper = new Mock<IOutlookApplicationWrapper>();
            mockWrapper.Setup(w => w.CategoryExists("TestCategory")).Returns(false);
            
            var provider = new OutlookCategoryManagerProvider(mockWrapper.Object);

            // Act
            provider.AddCategory("TestCategory", "ColorRed");

            // Assert
            mockWrapper.Verify(w => w.AddCategory("TestCategory", "ColorRed"), Times.Once);
        }

        [Fact]
        public void UpdateCategoryColor_ShouldCallWrapperUpdate_WhenCategoryExists()
        {
            // Arrange
            var mockWrapper = new Mock<IOutlookApplicationWrapper>();
            mockWrapper.Setup(w => w.CategoryExists("TestCategory")).Returns(true);
            
            var provider = new OutlookCategoryManagerProvider(mockWrapper.Object);

            // Act
            provider.UpdateCategoryColor("TestCategory", "ColorBlue");

            // Assert
            mockWrapper.Verify(w => w.UpdateCategory("TestCategory", "ColorBlue"), Times.Once);
        }

        [Fact]
        public void RemoveCategory_ShouldCallWrapperRemove_WhenCategoryExists()
        {
            // Arrange
            var mockWrapper = new Mock<IOutlookApplicationWrapper>();
            mockWrapper.Setup(w => w.CategoryExists("TestCategory")).Returns(true);
            
            var provider = new OutlookCategoryManagerProvider(mockWrapper.Object);

            // Act
            provider.RemoveCategory("TestCategory");

            // Assert
            mockWrapper.Verify(w => w.RemoveCategory("TestCategory"), Times.Once);
        }
    }
}