// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using Catamailer.Infrastructure;
using Moq;
using Xunit;

namespace Catamailer.Infrastructure.Tests
{
    /// <summary>
    /// Classe de tests validant le comportement du gestionnaire de catégories Outlook.
    /// </summary>
    public class OutlookCategoryManagerProviderTests
    {
        [Fact]
        public void AddCategory_ShouldCallWrapperAdd_WhenCategoryDoesNotExist()
        {
            // Arrange
            var mockWrapper = new Mock<IOutlookApplicationWrapper>();
            mockWrapper.Setup(w => w.CategoryExists("TestCategory")).Returns(false);
            
            var provider = new OutlookCategoryManagerProvider(mockWrapper.Object);

            // Act
            provider.AddCategory("TestCategory", "ColorRed");

            // Assert
            mockWrapper.Verify(w => w.AddCategory("TestCategory", "ColorRed"), Times.Once);
        }

        [Fact]
        public void UpdateCategoryColor_ShouldCallWrapperUpdate_WhenCategoryExists()
        {
            // Arrange
            var mockWrapper = new Mock<IOutlookApplicationWrapper>();
            mockWrapper.Setup(w => w.CategoryExists("TestCategory")).Returns(true);
            
            var provider = new OutlookCategoryManagerProvider(mockWrapper.Object);

            // Act
            provider.UpdateCategoryColor("TestCategory", "ColorBlue");

            // Assert
            mockWrapper.Verify(w => w.UpdateCategory("TestCategory", "ColorBlue"), Times.Once);
        }

        [Fact]
        public void RemoveCategory_ShouldCallWrapperRemove_WhenCategoryExists()
        {
            // Arrange
            var mockWrapper = new Mock<IOutlookApplicationWrapper>();
            mockWrapper.Setup(w => w.CategoryExists("TestCategory")).Returns(true);
            
            var provider = new OutlookCategoryManagerProvider(mockWrapper.Object);

            // Act
            provider.RemoveCategory("TestCategory");

            // Assert
            mockWrapper.Verify(w => w.RemoveCategory("TestCategory"), Times.Once);
        }
    }
}