// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using Catamailer.Infrastructure;
using Moq;
using Xunit;

namespace Catamailer.Infrastructure.Tests
{
    /// <summary>
    /// Classe de tests validant le comportement du fournisseur de mise à jour en masse Outlook.
    /// </summary>
    public class OutlookMassUpdateProviderTests
    {
        [Fact]
        public void UpdateCategoryNameOnItems_ShouldCallWrapperReplaceCategory()
        {
            // Arrange
            var mockWrapper = new Mock<IOutlookApplicationWrapper>();
            var provider = new OutlookMassUpdateProvider(mockWrapper.Object);
            
            var oldCategory = "AncienneCategorie";
            var newCategory = "NouvelleCategorie";

            // Act
            provider.UpdateCategoryNameOnItems(oldCategory, newCategory);

            // Assert
            mockWrapper.Verify(w => w.ReplaceCategoryOnAllItems(oldCategory, newCategory), Times.Once);
        }
    }
}