// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
//         - 2026-09-09 : Adaptation à la refonte de MailMetadata (J3-S2-T2-ST1).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using Catamailer.Domain;
using Catamailer.Infrastructure;
using Moq;
using Xunit;

namespace Catamailer.Infrastructure.Tests
{
    /// <summary>
    /// Classe de tests validant le comportement du fournisseur de sélection Outlook.
    /// </summary>
    public class OutlookSelectionProviderTests
    {
        [Fact]
        public void GetSelectedMail_ShouldReturnNull_WhenNoMailIsSelected()
        {
            // Arrange
            var mockWrapper = new Mock<IOutlookApplicationWrapper>();
            mockWrapper.Setup(w => w.GetSelectedEntryId()).Returns((string?)null);

            var provider = new OutlookSelectionProvider(mockWrapper.Object);

            // Act
            var result = provider.GetSelectedMail();

            // Assert
            Assert.Null(result);
        }

        [Fact]
        public void GetSelectedMail_ShouldReturnMetadata_WhenMailIsSelected()
        {
            // Arrange
            var expectedEntryId = "SEL-98765";
            var expectedMetadata = new MailMetadata(
                expectedEntryId, 
                "Selected Subject", 
                "sender@sel.com", 
                null,
                new List<string>(),
                new List<string>()
            );

            var mockWrapper = new Mock<IOutlookApplicationWrapper>();
            mockWrapper.Setup(w => w.GetSelectedEntryId()).Returns(expectedEntryId);
            mockWrapper.Setup(w => w.GetMailMetadata(expectedEntryId)).Returns(expectedMetadata);

            var provider = new OutlookSelectionProvider(mockWrapper.Object);

            // Act
            var result = provider.GetSelectedMail();

            // Assert
            Assert.NotNull(result);
            Assert.Equal(expectedEntryId, result!.EntryId);
            Assert.Equal("Selected Subject", result.Subject);
        }
    }
}