// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-25
//     Historique :
//         - 2026-09-25 : Création des tests de validation CRUD pour RuleRepository (J6-S3-T5 - Phase Rouge).
//         - 2026-09-25 : Correction de la compilation des tests, ajout des paramètres de constructeurs (J6-S3-T5 - Phase Rouge Correction).
//         - 2026-09-25 : Ajout du test UpdateDictionaryRuleAsync (J6-S3-T6 - Phase Rouge).
//         - 2026-09-25 : Correction encapsulation Domain (J6-S3-T6 - Phase Rouge Correction).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System.Linq;
using System.Threading.Tasks;
using Catamailer.Domain;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Catamailer.Infrastructure.Tests
{
    public class RuleRepositoryTests
    {
        private CatamailerDbContext GetInMemoryContext()
        {
            var connection = new SqliteConnection("DataSource=:memory:");
            connection.Open();

            var options = new DbContextOptionsBuilder<CatamailerDbContext>()
                .UseSqlite(connection)
                .Options;

            var context = new CatamailerDbContext(options);
            context.Database.EnsureCreated();

            return context;
        }

        [Fact]
        public async Task AddAndGetAllDictionaryRulesAsync_ShouldPersistAndRetrieveRules()
        {
            // Arrange
            using var context = GetInMemoryContext();
            var repository = new RuleRepository(context);

            var category = new CategoryNode("TestCategory");
            context.Categories.Add(category);
            await context.SaveChangesAsync();

            var rule = new DictionaryRule(category, new[] { "urgent" }, new[] { "boss@corp.com" }, new[] { "team@corp.com" });

            // Act
            await repository.AddDictionaryRuleAsync(rule);
            var result = (await repository.GetAllDictionaryRulesAsync()).ToList();

            // Assert
            Assert.Single(result);
            var savedRule = result.First();
            Assert.Equal("TestCategory", savedRule.TargetCategory.Name);
            Assert.Contains("urgent", savedRule.SubjectKeywords);
            Assert.Contains("boss@corp.com", savedRule.SenderKeywords);
            Assert.Contains("team@corp.com", savedRule.RecipientKeywords);
        }

        [Fact]
        public async Task UpdateDictionaryRuleAsync_ShouldUpdatePersistedRule()
        {
            // Arrange
            using var context = GetInMemoryContext();
            var repository = new RuleRepository(context);

            var category = new CategoryNode("TestCategory");
            context.Categories.Add(category);
            await context.SaveChangesAsync();

            var rule = new DictionaryRule(category, new[] { "initial" });
            await repository.AddDictionaryRuleAsync(rule);

            // Act
            rule.Update(category, new[] { "updated" });
            await repository.UpdateDictionaryRuleAsync(rule);
            
            var result = (await repository.GetAllDictionaryRulesAsync()).ToList();

            // Assert
            Assert.Single(result);
            var updatedRule = result.First();
            Assert.Contains("updated", updatedRule.SubjectKeywords);
            Assert.DoesNotContain("initial", updatedRule.SubjectKeywords);
        }

        [Fact]
        public async Task DeleteDictionaryRuleAsync_ShouldRemoveRule()
        {
            // Arrange
            using var context = GetInMemoryContext();
            var repository = new RuleRepository(context);

            var category = new CategoryNode("TestCategory");
            context.Categories.Add(category);
            await context.SaveChangesAsync();

            var rule = new DictionaryRule(category, new[] { "delete-me" });
            await repository.AddDictionaryRuleAsync(rule);
            
            // Act
            await repository.DeleteDictionaryRuleAsync(rule);
            var result = await repository.GetAllDictionaryRulesAsync();

            // Assert
            Assert.Empty(result);
        }

        [Fact]
        public async Task AddAndGetAllExecutionRulesAsync_ShouldPersistAndRetrieveRules()
        {
            // Arrange
            using var context = GetInMemoryContext();
            var repository = new RuleRepository(context);

            var rootNode = new RuleNode(LogicalOperator.And);
            rootNode.AddCriterion(new RuleCriterion(MailField.Subject, MatchOperator.Contains, "test"));
            
            var action = new RuleAction(ActionType.MoveToFolder, "Archive");
            var rule = new ExecutionRule("MyRule", rootNode, new[] { action });

            // Act
            await repository.AddExecutionRuleAsync(rule);
            var result = (await repository.GetAllExecutionRulesAsync()).ToList();

            // Assert
            Assert.Single(result);
            var savedRule = result.First();
            Assert.Equal("MyRule", savedRule.Name);
            Assert.Single(savedRule.RootNode.Criteria);
            Assert.Equal("test", savedRule.RootNode.Criteria[0].Value);
            Assert.Single(savedRule.Actions);
            Assert.Equal(ActionType.MoveToFolder, savedRule.Actions[0].Type);
            Assert.Equal("Archive", savedRule.Actions[0].Parameter);
        }

        [Fact]
        public async Task DeleteExecutionRuleAsync_ShouldRemoveRule()
        {
            // Arrange
            using var context = GetInMemoryContext();
            var repository = new RuleRepository(context);

            var rule = new ExecutionRule("RuleToDelete", new RuleNode(LogicalOperator.And), new[] { new RuleAction(ActionType.MarkAsRead, string.Empty) });
            await repository.AddExecutionRuleAsync(rule);

            // Act
            await repository.DeleteExecutionRuleAsync(rule);
            var result = await repository.GetAllExecutionRulesAsync();

            // Assert
            Assert.Empty(result);
        }
    }
}