// ------------------------------------------------------------------------------
// <auto-generated>
//     Date de création : 2026-09-07
//     Historique :
//         - 2026-09-07 : Création initiale (Phase Rouge).
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.Threading.Tasks;
using Catamailer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Catamailer.Infrastructure.Tests
{
    /// <summary>
    /// Classe de tests validant le comportement des dépôts de configuration et d'état.
    /// </summary>
    public class StateAndSettingsRepositoriesTests
    {
        private CatamailerDbContext GetInMemoryContext()
        {
            var options = new DbContextOptionsBuilder<CatamailerDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            return new CatamailerDbContext(options);
        }

        [Fact]
        public async Task HistoryStateRepository_ShouldPersistAndRetrieveState()
        {
            // Arrange
            var context = GetInMemoryContext();
            var repository = new HistoryStateRepository(context);
            var key = "LastEntryID";
            var value = "123-ABC";

            // Act
            await repository.SetStateAsync(key, value);
            var result = await repository.GetStateAsync(key);

            // Assert
            Assert.Equal(value, result);
        }

        [Fact]
        public async Task HistoryStateRepository_ShouldUpdateExistingState()
        {
            // Arrange
            var context = GetInMemoryContext();
            var repository = new HistoryStateRepository(context);
            var key = "LastEntryID";

            // Act
            await repository.SetStateAsync(key, "INITIAL");
            await repository.SetStateAsync(key, "UPDATED");
            var result = await repository.GetStateAsync(key);

            // Assert
            Assert.Equal("UPDATED", result);
        }

        [Fact]
        public async Task AppSettingsRepository_ShouldPersistAndRetrieveSetting()
        {
            // Arrange
            var context = GetInMemoryContext();
            var repository = new AppSettingsRepository(context);
            var key = "HistoryDebounceDelayMinutes";
            var value = "30";

            // Act
            await repository.SetSettingAsync(key, value);
            var result = await repository.GetSettingAsync(key);

            // Assert
            Assert.Equal(value, result);
        }
    }
}